
/* SoA Scenery Talk: Self-Talk 

IF
  Global(" ","GLOBAL",1)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  InParty(Player1)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  CombatCounter(0)
  !See([ENEMY])
  

THEN
    RESPONSE #100
             SetGlobal(" ","GLOBAL",1)
             ActionOverride(Player1,StartDialogue("Player1",Player1))
END

*/

/* If the party visits the Trademeet Bar, */
IF
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  InMyArea(Player1)
  TimeofDay(NIGHT)
  Global("c-aranrom","GLOBAL",2)
  Global("c-aranmalcer","GLOBAL",0)
  AreaCheck("AR2010")
THEN
  RESPONSE #100
      SetGlobal("c-aranmalcer","GLOBAL",1)
END

/* then set up a spawn when you go outside into AR2000... */
IF
  InParty(Myself)
  Global("c-aranmalcer","GLOBAL",1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  AreaCheck("AR2000")
THEN
  RESPONSE #100
    StartCutSceneMode()
    CreateCreature("c-malcer",[1874.2195],0)  
    CreateCreature("c-oskut",[1915.2181],0)  
    CreateCreature("c-taman",[1900.2096],0)
    SetGlobal("c-aranmalcer","GLOBAL",2)
    EndCutSceneMode()
END

/* ... and shut it down if you leave the area before things happen. */
IF
  InParty(Myself)
  Global("c-aranmalcer","GLOBAL",1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !AreaCheck("AR2010")
  !AreaCheck("AR2000")
THEN
  RESPONSE #100
      SetGlobal("c-aranmalcer","GLOBAL",0)
END

/* Closing Reaction Blocks (Backup) based on Berelide's work */

/* Backing out RE Reactions */

/* Romantic Encounters: Weathermistress Ada */
IF
  InParty(Myself)
  Global("RE_AdaSex","GLOBAL",1)
  Global("c-arnREAda","LOCALS",0)
  !AreaCheck("AR0904")
  !AreaCheck("AR0900")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnREAda","LOCALS",3)
END
/* Weathermistress Ada Comment */
IF
  InParty(Myself)
  Global("RE_AdaSex","GLOBAL",1)
  Global("c-arnREAda","LOCALS",0)
  AreaCheck("AR0904")
  AreaCheck("AR0900")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnREAda","LOCALS",1)
END
/* Romantic Encounters: Anishai */
IF
  InParty(Myself)
  Global("RE_AnishaiFlirt","GLOBAL",1)
  Global("c-arnREAni","LOCALS",0)
  !AreaCheck("AR0303")
  !AreaCheck("AR0304")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnREAnishai","LOCALS",3)
END
/* Romantic Encounters: Anishai Comment */
IF
  InParty(Myself)
  Global("RE_AnishaiFlirt","GLOBAL",1)
  Global("c-arnREAni","LOCALS",0)
  !AreaCheck("AR0303")
  !AreaCheck("AR0304")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnREAnishai","LOCALS",1)
END
/* Romantic Encounters: Aran Linvale */
IF
  InParty(Myself)
  Global("RE_AranFlirt","GLOBAL",1)
  Global("c-arnREAran","LOCALS",0)
  Gender(Player1,FEMALE)
  !AreaCheck("AR0307")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnREAran","LOCALS",9)
END
/* Romantic Encounters: Aran Linvale Comment */
IF
  InParty(Myself)
  Global("RE_AranFlirt","GLOBAL",1)
  Global("c-arnREAran","LOCALS",0)
  Gender(Player1,FEMALE)
  !AreaCheck("AR0307")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnREAran","LOCALS",9)
END
/* Romantic Encounters: Bjornin  */
IF
  InParty(Myself)
  Global("RE_BjorninFlirt","GLOBAL",1)
  Global("c-arnREBjorn","LOCALS",0)
  Gender(Player1,FEMALE)
  !AreaCheck("AR0903")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnREBjorn","LOCALS",9)
END
/* Romantic Encounters: Bjornin Comment  */
IF
  InParty(Myself)
  Global("RE_BjorninFlirt","GLOBAL",1)
  Global("c-arnREBjorn","LOCALS",0)
  Gender(Player1,FEMALE)
  !AreaCheck("AR0903")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnREBjorn","LOCALS",9)
END
/* Romantic Encounters: Bodhi  */
IF
  InParty(Myself)
  Global("RE_BodhiFlirt","GLOBAL",1)
  Global("c-arnREBodhi","LOCALS",0)
  !AreaCheck("AR0801")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnREBodhi","LOCALS",9)
END
/* Romantic Encounters: Bodhi Comment */
IF
  InParty(Myself)
  Global("RE_BodhiFlirt","GLOBAL",1)
  Global("c-arnREBodhi","LOCALS",0)
  !AreaCheck("AR0801")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnREBodhi","LOCALS",9)
END
/* Romantic Encounters: Chanelle */
IF
  InParty(Myself)
  Global("RE_ChanelleFlirt","GLOBAL",1)
  Global("c-arnREChanelle","LOCALS",0)
  Gender(Player1,FEMALE)
  !AreaCheck("AR1307")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnREChanelle","LOCALS",9)
END
/* Romantic Encounters: Chanelle Comment */
IF
  InParty(Myself)
  Global("RE_ChanelleFlirt","GLOBAL",1)
  Global("c-arnREChanelle","LOCALS",0)
  Gender(Player1,FEMALE)
  !AreaCheck("AR1307")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnREChanelle","LOCALS",9)
END
/* Romantic Encounters: Coran  */
IF
  InParty(Myself)
  Global("RE_CoranSex","GLOBAL",1)
  Global("c-arnRECoran","LOCALS",0)
  !AreaCheck("AR2600")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnRECoran","LOCALS",9)
END
/* Romantic Encounters: Coran Comment */
IF
  InParty(Myself)
  Global("RE_CoranSex","GLOBAL",1)
  Global("c-arnRECoran","LOCALS",0)
  !AreaCheck("AR2600")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnRECoran","LOCALS",9)
END
/* Romantic Encounters: Desharik  */
IF
  InParty(Myself)
  Global("RE_DesharikFlirt","GLOBAL",1)
  Global("c-arnREDesharik","LOCALS",0)
  !AreaCheck("AR1601")
  !AreaCheck("AR1515")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnREDesharik","LOCALS",9)
END
/* Romantic Encounters: Desharik Comment */
IF
  InParty(Myself)
  Global("RE_DesharikFlirt","GLOBAL",1)
  Global("c-arnREDesharik","LOCALS",0)
  !AreaCheck("AR1601")
  !AreaCheck("AR1515")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnREDesharik","LOCALS",9)
END
/* Romantic Encounters: Edwin  */
IF
  InParty(Myself)
  Global("RE_EdwinSex","GLOBAL",1)
  Global("c-arnREEdwin","LOCALS",0)
  !AreaCheck("AR1100")
  !AreaCheck("AR1200")
  !AreaCheck("AR1300")
  !AreaCheck("AR1304")
  !AreaCheck("AR1400")
  !AreaCheck("AR1404")
  !AreaCheck("AR1500")
  !AreaCheck("AR1600")
  !AreaCheck("AR1700")
  !AreaCheck("AR1800")
  !AreaCheck("AR1900")
  !AreaCheck("AR2000")
  !AreaCheck("AR2500")
  !AreaCheck("AR2600")
  !AreaCheck("AR2700")
  !AreaCheck("AR2800")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnREEdwin","LOCALS",9)
END

/* ? Edwin ? */

/* Romantic Encounters: Eldoth  */
IF
  InParty(Myself)
  Global("RE_EldothFlirt","GLOBAL",1)
  Global("c-arnREEldoth","LOCALS",0)
  !AreaCheck("AR0709")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnREEldoth","LOCALS",9)
END
/* Romantic Encounters: Eldoth Comment */
IF
  InParty(Myself)
  Global("RE_EldothFlirt","GLOBAL",1)
  Global("c-arnREEldoth","LOCALS",0)
  !AreaCheck("AR0709")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnREEldoth","LOCALS",9)
END
/* Romantic Encounters: Gaelan Bayle  */
IF
  InParty(Myself)
  Global("RE_GaelanFlirt","GLOBAL",1)
  Global("c-arnREGaelan","LOCALS",0)
  !AreaCheck("AR0311")
  !AreaCheck("AR0400")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnREGaelan","LOCALS",9)
END
/* Romantic Encounters: Gaelan Bayle Comment */
IF
  InParty(Myself)
  Global("RE_GaelanFlirt","GLOBAL",1)
  Global("c-arnREGaelan","LOCALS",0)
  !AreaCheck("AR0311")
  !AreaCheck("AR0400")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnREGaelan","LOCALS",9)
END
/* Romantic Encounters: Garren Windspear  */
IF
  InParty(Myself)
  Global("RE_GarrenFlirt","GLOBAL",1)
  Global("c-arnREGarren","LOCALS",0)
  !AreaCheck("AR1204")
  !AreaCheck("AR1200")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnREGarren","LOCALS",9)
END
/* Romantic Encounters: Garren Windspear Comment */
IF
  InParty(Myself)
  Global("RE_GarrenFlirt","GLOBAL",1)
  Global("c-arnREGarren","LOCALS",0)
  !AreaCheck("AR1204")
  !AreaCheck("AR1200")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnREGarren","LOCALS",9)
END
/* Romantic Encounters: Jarlaxle  */
IF
  InParty(Myself)
  Global("RE_JarlaxleFlirt","GLOBAL",1)
  Global("c-arnREJarlaxle","LOCALS",0)
  !AreaCheck("AR2208")
  !AreaCheck("AR2200")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnREJarlaxle","LOCALS",9)
END
/* Romantic Encounters: Jarlaxle Comment */
IF
  InParty(Myself)
  Global("RE_JarlaxleFlirt","GLOBAL",1)
  Global("c-arnREJarlaxle","LOCALS",0)
  !AreaCheck("AR2208")
  !AreaCheck("AR2200")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnREJarlaxle","LOCALS",9)
END
/* Romantic Encounters: Laran  */
IF
  InParty(Myself)
  Global("RE_LaranFlirt","GLOBAL",1)
  Global("c-arnRELaran","LOCALS",0)
  !AreaCheck("AR0704")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnRELaran","LOCALS",9)
END
/* Romantic Encounters: Laran Comment */
IF
  InParty(Myself)
  Global("RE_LaranFlirt","GLOBAL",1)
  Global("c-arnRELaran","LOCALS",0)
  !AreaCheck("AR0704")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnRELaran","LOCALS",9)
END
/* Romantic Encounters: Logan  */
IF
  InParty(Myself)
  Global("RE_LoganFlirt","GLOBAL",1)
  Global("c-arnRELogan","LOCALS",0)
  !AreaCheck("AR2007")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnRELogan","LOCALS",9)
END
/* Romantic Encounters: Logan Comment */
IF
  InParty(Myself)
  Global("RE_LoganFlirt","GLOBAL",1)
  Global("c-arnRELogan","LOCALS",0)
  !AreaCheck("AR2007")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnRELogan","LOCALS",9)
END
/* Romantic Encounters: Mekrath  */
IF
  InParty(Myself)
  Global("RE_MekrathFlirt","GLOBAL",1)
  Global("c-arnREMekrath","LOCALS",0)
  !AreaCheck("AR0705")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnREMekrath","LOCALS",9)
END
/* Romantic Encounters: Mekrath Comment */
IF
  InParty(Myself)
  Global("RE_MekrathFlirt","GLOBAL",1)
  Global("c-arnREMekrath","LOCALS",0)
  !AreaCheck("AR0705")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnREMekrath","LOCALS",9)
END
/* Romantic Encounters: Noober  */
IF
  InParty(Myself)
  Global("RE_NooberFlirt","GLOBAL",1)
  Global("c-arnRENoober","LOCALS",0)
  !AreaCheck("AR0513")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnRENoober","LOCALS",9)
END
/* Romantic Encounters: Noober Comment */
IF
  InParty(Myself)
  Global("RE_NooberFlirt","GLOBAL",1)
  Global("c-arnRENoober","LOCALS",0)
  !AreaCheck("AR0513")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnRENoober","LOCALS",9)
END

/* Romantic Encounters: Renal less */
IF
  InParty(Myself)
  Global("RE_RenalFlirt","GLOBAL",1)
  Global("c-arnRERenalFlirt","LOCALS",0)
  !AreaCheck("AR0306")
  !AreaCheck("AR0305")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnRERenalFlirt","LOCALS",9)
END
/* Romantic Encounters: Renal Comment less */
IF
  InParty(Myself)
  Global("RE_RenalFlirt","GLOBAL",1)
  Global("c-arnRERenalFlirt","LOCALS",0)
  !AreaCheck("AR0306")
  !AreaCheck("AR0305")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnRERenalFlirt","LOCALS",9)
END
/* Romantic Encounters: Renal more */
IF
  InParty(Myself)
  Global("RE_RenalSex","GLOBAL",1)
  Global("c-arnRERenal","LOCALS",0)
  !AreaCheck("AR0021")     // Crooked Crane, 1st floor
  !AreaCheck("AR0313")     // Sea's Bounty, 1st floor
  !AreaCheck("AR0406")     // Copper Coronet
  !AreaCheck("AR0509")     // Five Flagons, 1st floor
  !AreaCheck("AR0513")     // Delosar's, 1st floor
  !AreaCheck("AR0522")     // Five Flagons, 1st floor (stronghold)
  !AreaCheck("AR0704")     // Mithrest Inn
  !AreaCheck("AR0709")     // Den of the Seven Vales
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnRERenal","LOCALS",9)
END
/* Romantic Encounters: Renal Comment more */
IF
  InParty(Myself)
  Global("RE_RenalSex","GLOBAL",1)
  Global("c-arnRERenal","LOCALS",0)
  !AreaCheck("AR0021")     // Crooked Crane, 1st floor
  !AreaCheck("AR0313")     // Sea's Bounty, 1st floor
  !AreaCheck("AR0406")     // Copper Coronet
  !AreaCheck("AR0509")     // Five Flagons, 1st floor
  !AreaCheck("AR0513")     // Delosar's, 1st floor
  !AreaCheck("AR0522")     // Five Flagons, 1st floor (stronghold)
  !AreaCheck("AR0704")     // Mithrest Inn
  !AreaCheck("AR0709")     // Den of the Seven Vales
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnRERenal","LOCALS",9)
END
/* Romantic Encounters: Ribald  */
IF
  InParty(Myself)
  Global("RE_RibaldFlirt","GLOBAL",1)
  Global("c-arnRERibaldFlirt","LOCALS",0)
  !AreaCheck("AR0702")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnRERibaldFlirt","LOCALS",9)
END
/* Romantic Encounters: Ribald Sex  */
IF
  InParty(Myself)
  Global("RE_RibaldSex","GLOBAL",1)
  Global("c-arnRERibald","LOCALS",0)
  !AreaCheck("AR0702")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnRERibald","LOCALS",9)
END
/* Romantic Encounters: Ribald RA2  */
IF
  InParty(Myself)
  Global("RE_RibaldRomanceActive","GLOBAL",2)
  Global("c-arnRERibaldRA2","LOCALS",0)
  !AreaCheck("AR0702")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnRERibaldRA","LOCALS",9)
END
/* Romantic Encounters: Ryan Trawl  */
IF
  InParty(Myself)
  Global("RE_RyanFlirt","GLOBAL",1)
  Global("c-arnRERyan","LOCALS",0)
  !AreaCheck("AR0903")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnRERyan","LOCALS",9)
END
/* Romantic Encounters: Saemon Havarian  */
IF
  InParty(Myself)
  Global("RE_SaemonFlirt","GLOBAL",1)
  Global("c-arnRESaemon","LOCALS",0)
  !Global("Chapter","GLOBAL",4)
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnRESaemon","LOCALS",9)
END
/* Romantic Encounters: Solaufein  */
IF
  InParty(Myself)
  Global("RE_SolaufeinFlirt","GLOBAL",1)
  Global("c-arnRESolaufein","LOCALS",0)
  !Global("Chapter","GLOBAL",4)
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnRESolaufein","LOCALS",9)
END
/* Romantic Encounters: Talak  */
IF
  InParty(Myself)
  Global("RE_TalakFlirt","GLOBAL",1)
  Global("c-arnRETalak","LOCALS",0)
  !Global("Chapter","GLOBAL",5)
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnRETalak","LOCALS",9)
END
/* Romantic Encounters: Talak  */
IF
  InParty(Myself)
  Global("RE_TeosFlirt","GLOBAL",1)
  Global("c-arnRETeos","LOCALS",0)
  !AreaCheck("AR0411")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnRETeos","LOCALS",9)
END
/* Romantic Encounters: Yoshimo  */
IF
  InParty(Myself)
  Global("RE_YoshimoSex","GLOBAL",1)
  Global("c-arnREYoshimo","LOCALS",0)
  !AreaCheck("AR0021")     // Crooked Crane, 1st floor
  !AreaCheck("AR0313")     // Sea's Bounty, 1st floor
  !AreaCheck("AR0406")     // Copper Coronet
  !AreaCheck("AR0509")     // Five Flagons, 1st floor
  !AreaCheck("AR0513")     // Delosar's, 1st floor
  !AreaCheck("AR0522")     // Five Flagons, 1st floor (stronghold)
  !AreaCheck("AR0704")     // Mithrest Inn
  !AreaCheck("AR0709")     // Den of the Seven Vales
  !AreaCheck("AR1105")     // Imnesvale Inn
  !AreaCheck("AR1602")     // Vulgar Monkey
  !AreaCheck("AR2010")     // Trademeet Inn
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnREYoshimo","LOCALS",9)
END
/* Romantic Encounters: Cernd  */
IF
  InParty(Myself)
  Global("RE_CerndFlirt","GLOBAL",1)
  Global("c-arnRECernd","LOCALS",0)
  !AreaCheck("AR1900")
  !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arnRECernd","LOCALS",9)
END
/* tracking intimacy levels */
/* look for incrementing relationship to kissing */
IF
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  Global("c-aranintimate","GLOBAL",1) // we kissed...
  Global("c-aransex","GLOBAL",0) // not registered...
  Gender(Player1,FEMALE)
  !HasItemEquiped("belt05",Player1)
THEN
  RESPONSE #100
    SetGlobal("c-aransex","GLOBAL",1) // we kissed.
END
/* look for incrementing relationship to kissing + touching */
IF
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  Global("c-aranintimate","GLOBAL",2) // kissed and touched
  Global("c-aransex","GLOBAL",1) // not registered
  Gender(Player1,FEMALE)
  !HasItemEquiped("belt05",Player1)
THEN
  RESPONSE #100
    SetGlobal("c-aransex","GLOBAL",2) // we kissed and touched
END
/* look for incrementing relationship to petting */
IF
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  Global("c-aranintimate","GLOBAL",3) // we went further, but not the big one
  Global("c-aransex","GLOBAL",2) // not registered
  Gender(Player1,FEMALE)
  !HasItemEquiped("belt05",Player1)
THEN
  RESPONSE #100
    SetGlobal("c-aransex","GLOBAL",3) // we went further, but not the big one
END
/* look for incrementing relationship to full intimacy */
IF
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  Global("c-aranintimate","GLOBAL",4)
  Global("c-aransex","GLOBAL",3) // shared everything
  Gender(Player1,FEMALE)
  !HasItemEquiped("belt05",Player1)
THEN
  RESPONSE #100
    SetGlobal("c-aransex","GLOBAL",4) // shared everything
END
/* BCS Blocks for Scroll Creation */
/* c-arSCRL15 Aran PID: Create Scroll of Protection from Petrification */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL15","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    StartCutSceneMode()
    SetGlobal("c-arSCRL15","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL15",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Protection from Petrification be finished, if you want it.~)
    EndCutSceneMode()
END
/*  c-arSCRL1B Aran PID: Create Scroll of Agannazar's Scorcher */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL1B","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL1B","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL1B",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Agannazar's Scorcher be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL1C Aran PID: Create Scroll of Ghoul Touch */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL1C","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL1C","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL1C",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Ghoul Touch be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL1D Aran PID: Create Scroll of Clairvoyance */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL1D","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL1D","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL1D",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Clairvoyance be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL1E Aran PID: Create Scroll of Dispel Magic */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL1E","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL1E","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL1E",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Dispel Magic be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL1F Aran PID: Create Scroll of Flame Arrow */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL1F","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL1F","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL1F",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Flame Arrow be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL1G Aran PID: Create Scroll of Fireball */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL1G","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL1G","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL1G",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Fireball be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL1H Aran PID: Create Scroll of Haste */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL1H","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL1H","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL1H",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Haste be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL1I Aran PID: Create Scroll of Hold Person */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL1I","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL1I","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL1I",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Hold Person be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL1J Aran PID: Create Scroll of Invisibility 10' radius */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL1J","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL1J","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL1J",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Invisibility 10' radius be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL1K Aran PID: Create Scroll of Lightning Bolt */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL1K","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL1K","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL1K",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Lightning Bolt be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL1M Aran PID: Create Scroll of NonDetection */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL1M","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL1M","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL1M",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' NonDetection be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL1N Aran PID: Create Scroll of Protection from Normal Missiles */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL1N","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL1N","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL1N",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Protection from Normal Missiles be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL1O Aran PID: Create Scroll of Slow */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL1O","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL1O","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL1O",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Slow be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL1P Aran PID: Create Scroll of Skull Trap */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL1P","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL1P","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL1P",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Skull Trap be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL1Q Aran PID: Create Scroll of Vampiric Touch */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL1Q","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL1Q","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL1Q",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Vampiric Touch be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL1S Aran PID: Create Scroll of Dire Charm */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL1S","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL1S","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL1S",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Dire Charm be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL1T Aran PID: Create Scroll of Ghost Armor */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL1T","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL1T","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL1T",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Ghost Armor be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL1U Aran PID: Create Scroll of Confusion */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL1U","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL1U","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL1U",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Confusion be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL1V Aran PID: Create Scroll of Stoneskin */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL1V","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL1V","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL1V",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Stoneskin be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL1W Aran PID: Create Scroll of Fireshield (Blue) */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL1W","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL1W","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL1W",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Fireshield (Blue) be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL1X Aran PID: Create Scroll of Ice Storm */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL1X","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL1X","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL1X",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Ice Storm be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL1Y Aran PID: Create Scroll of Improved Invisibility */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL1Y","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
  SetGlobal("c-arSCRL1Y","LOCALS",0)
  SetGlobal("c-aranscribe","GLOBAL",0)
  GiveItemCreate("SCRL1Y",Myself,1,1,1)
  DisplayStringHead(Myself,~Aye, now, that scroll o' Improved Invisibility be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL1Z Aran PID: Create Scroll of Minor Globe of Invulnerability */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL1Z","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL1Z","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL1Z",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Minor Globe of Invulnerability be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL2E Aran PID: Create Scroll of Cloudkill */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL2E","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL2E","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL2E",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Cloudkill be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL2F Aran PID: Create Scroll of Cone of Cold */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL2F","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL2F","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL2F",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Cone of Cold be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL2H Aran PID: Create Scroll of Shadow Door */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL2H","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL2H","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL2H",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Shadow Door be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL3G Aran PID: Create Scroll of Vocalize */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL3G","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL3G","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL3G",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Vocalize be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL5G Aran PID: Create Scroll of Remove Curse */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL5G","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL5G","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL5G",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Remove Curse be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL5H Aran PID: Create Scroll of Emotion */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL5H","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL5H","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL5H",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Emotion be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL5I Aran PID: Create Scroll of Greater Malison */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL5I","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL5I","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL5I",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Greater Malison be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL5J Aran PID: Create Scroll of Otiluke's Resilient Sphere */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL5J","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL5J","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL5J",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Otiluke's Resilient Sphere be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL5K Aran PID: Create Scroll of Spirit Armor */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL5K","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL5K","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL5K",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Spirit Armor be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL5N Aran PID: Create Scroll of Domination */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL5N","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL5N","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL5N",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Domination be finished, if you want it.~)
  EndCutSceneMode()
END

/*  c-arSCRL5P Aran PID: Create Scroll of Chaos */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL5P","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL5P","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL5P",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Chaos be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL5Q Aran PID: Create Scroll of Feeblemind */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL5Q","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL5Q","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL5Q",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Feeblemind be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL5T Aran PID: Create Scroll of Protection from Electricity */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL5T","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL5T","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL5T",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Protection from Electricity be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL5U Aran PID: Create Scroll of Reflected Image */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL5U","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL5U","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL5U",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Reflected Image be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL66 Aran PID: Create Scroll of Grease */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL66","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL66","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL66",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Grease be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL67 Aran PID: Create Scroll of Armor */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL67","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL67","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL67",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Armor be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL68 Aran PID: Create Scroll of Burning Hands */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL68","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL68","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL68",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Burning Hands be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL69 Aran PID: Create Scroll of Charm Person */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL69","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL69","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL69",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Charm Person be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL6D Aran PID: Create Scroll of Find Familiar */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL6D","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL6D","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL6D",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Find Familiar be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL6E Aran PID: Create Scroll of Power Word, Sleep */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL6E","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL6E","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL6E",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Power Word, Sleep be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL6F Aran PID: Create Scroll of Ray of Enfeeblement */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL6F","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL6F","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL6F",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Ray of Enfeeblement be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL6G Aran PID: Create Scroll of Minor Spell Deflection */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL6G","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL6G","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL6G",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Minor Spell Deflection be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL6H Aran PID: Create Scroll of Protection from Fire */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL6H","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL6H","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL6H",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Protection from Fire be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL6I Aran PID: Create Scroll of Protection from Cold */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL6I","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL6I","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL6I",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Protection from Cold be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL6J Aran PID: Create Scroll of Spell Thrust */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL6J","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL6J","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL6J",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Spell Thrust be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL6K Aran PID: Create Scroll of Detect Illusion */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL6K","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL6K","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL6K",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Detect Illusion be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL6L Aran PID: Create Scroll of Hold Undead */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL6L","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL6L","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL6L",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Hold Undead be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL6M Aran PID: Create Scroll of Enchanted Weapon */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL6M","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL6M","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL6M",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Enchanted Weapon be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL6N Aran PID: Create Scroll of Fireshield (Red) */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL6N","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL6N","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL6N",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Fireshield (Red) be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL6O Aran PID: Create Scroll of Secret Word */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL6O","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL6O","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL6O",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Secret Word be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL6P Aran PID: Create Scroll of Minor Sequencer */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL6P","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL6P","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL6P",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Minor Sequencer be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL6S Aran PID: Create Scroll of Spell Immunity */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL6S","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL6S","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL6S",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Spell Immunity be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL6T Aran PID: Create Scroll of Protection from Normal Weapons */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL6T","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL6T","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL6T",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Protection from Normal Weapons be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL6U Aran PID: Create Scroll of Breach */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL6U","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL6U","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL6U",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Breach be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL6V Aran PID: Create Scroll of Lower Resistance */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL6V","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL6V","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL6V",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Lower Resistance be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL6W Aran PID: Create Scroll of Oracle */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL6W","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL6W","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL6W",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Oracle be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL6Y Aran PID: Create Scroll of Protection from Acid */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL6Y","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL6Y","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL6Y",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Protection from Acid be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL6Z Aran PID: Create Scroll of Phantom Blade */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL6Z","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL6Z","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL6Z",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Phantom Blade be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL70 Aran PID: Create Scroll of Color Spray */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL70","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL70","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL70",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Color Spray be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL71 Aran PID: Create Scroll of Blindness */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL71","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL71","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL71",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Blindness be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL72 Aran PID: Create Scroll of Friends */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL72","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL72","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL72",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Friends be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL75 Aran PID: Create Scroll of Identify */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL75","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL75","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL75",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Identify be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL76 Aran PID: Create Scroll of Infravision */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL76","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL76","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL76",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Infravision be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL77 Aran PID: Create Scroll of Magic Missile */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL77","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL77","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL77",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Magic Missile be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL78 Aran PID: Create Scroll of Protection from Evil */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL78","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL78","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL78",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Protection from Evil be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL79 Aran PID: Create Scroll of Shield */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL79","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL79","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL79",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Shield be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL7D Aran PID: Create Scroll of Minor Spell Turning */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL7D","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL7D","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL7D",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Minor Spell Turning be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL7F Aran PID: Create Scroll of Globe of Invulnerability */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL7F","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL7F","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL7F",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Globe of Invulnerability be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL7G Aran PID: Create Scroll of Tenser's Transformation */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL7G","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL7G","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL7G",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Tenser's Transformation be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL7H Aran PID: Create Scroll of Flesh to Stone */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL7H","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL7H","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL7H",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Flesh to Stone be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL7I Aran PID: Create Scroll of Death Spell */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL7I","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL7I","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL7I",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Death Spell be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL7J Aran PID: Create Scroll of Protection from Magic */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL7J","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL7J","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL7J",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Protection from Magic be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL7K Aran PID: Create Scroll of Mislead */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL7K","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL7K","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL7K",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Mislead be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL7L Aran PID: Create Scroll of Pierce Magic */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL7L","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL7L","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL7L",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Pierce Magic be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL7M Aran PID: Create Scroll of True Sight */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL7M","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL7M","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL7M",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' True Sight be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL7O Aran PID: Create Scroll of Protection from Magical Weapons */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL7O","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL7O","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL7O",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Protection from Magical Weapons be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL7P Aran PID: Create Scroll of Power Word, Silence */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL7P","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL7P","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL7P",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Power Word, Silence be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL7Q Aran PID: Create Scroll of Improved Haste */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL7Q","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL7Q","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL7Q",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Improved Haste be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL7R Aran PID: Create Scroll of Death Fog */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL7R","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL7R","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL7R",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Death Fog be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL7S Aran PID: Create Scroll of Chain Lightning */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL7S","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL7S","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL7S",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Chain Lightning be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL7T Aran PID: Create Scroll of Disintegrate */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL7T","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL7T","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL7T",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Disintegrate be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL7U Aran PID: Create Scroll of Contingency */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL7U","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL7U","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL7U",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Contingency be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL7V Aran PID: Create Scroll of Spell Deflection */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL7V","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL7V","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL7V",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Spell Deflection be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL80 Aran PID: Create Scroll of Shocking Grasp */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL80","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL80","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL80",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Shocking Grasp be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL81 Aran PID: Create Scroll of Sleep */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL81","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL81","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL81",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Sleep be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL82 Aran PID: Create Scroll of Chill Touch */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL82","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL82","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL82",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Chill Touch be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL83 Aran PID: Create Scroll of Chromatic Orb */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL83","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL83","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL83",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Chromatic Orb be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL84 Aran PID: Create Scroll of Larloch's Minor Drain */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL84","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL84","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL84",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Larloch's Minor Drain be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL85 Aran PID: Create Scroll of Blur */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL85","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL85","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL85",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Blur be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL86 Aran PID: Create Scroll of Detect Evil */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL86","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL86","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL86",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Detect Evil be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL87 Aran PID: Create Scroll of Detect Invisibility */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL87","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL87","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL87",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Detect Invisibility be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL89 Aran PID: Create Scroll of Horror */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL89","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL89","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL89",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Horror be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL8C Aran PID: Create Scroll of Stone to Flesh */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL8C","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL8C","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL8C",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Stone to Flesh be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL8X Aran PID: Create Scroll of Spell Shield */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL8X","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL8X","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL8X",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Spell Shield be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL90 Aran PID: Create Scroll of Invisibility */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL90","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL90","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL90",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Invisibility be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL91 Aran PID: Create Scroll of Knock */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL91","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL91","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL91",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Knock be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL92 Aran PID: Create Scroll of Know Alignment */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL92","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL92","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL92",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Know Alignment be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL93 Aran PID: Create Scroll of Luck */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL93","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL93","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL93",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Luck be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL94 Aran PID: Create Scroll of Resist Fear */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL94","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL94","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL94",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Resist Fear be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL95 Aran PID: Create Scroll of Melf's Acid Arrow */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL95","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL95","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL95",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Melf's Acid Arrow be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL96 Aran PID: Create Scroll of Mirror Image */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL96","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL96","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL96",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Mirror Image be finished, if you want it.~)
  EndCutSceneMode()
END

/*  c-arSCRL97 Aran PID: Create Scroll of Stinking Cloud */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL97","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL97","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL97",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Stinking Cloud be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL98 Aran PID: Create Scroll of Strength */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL98","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL98","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL98",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Strength be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRL99 Aran PID: Create Scroll of Web */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRL99","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRL99","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRL99",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Web be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRLA1 Aran PID: Create Scroll of Wizard Eye */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRLA1","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRLA1","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRLA1",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Wizard Eye be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRLA2 Aran PID: Create Scroll of Deafness */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRLA2","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRLA2","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRLA2",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Deafness be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRLA3 Aran PID: Create Scroll of Glitterdust */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRLA3","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRLA3","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRLA3",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Glitterdust be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRLA5 Aran PID: Create Scroll of Melf's Minute Meteors */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRLA5","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRLA5","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRLA5",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Melf's Minute Meteors be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRLA6 Aran PID: Create Scroll of Spook */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRLA6","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRLA6","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRLA6",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Spook be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRLA8 Aran PID: Create Scroll of Contagion */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRLA8","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRLA8","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRLA8",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Contagion be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRLAJ Aran PID: Create Scroll of Farsight */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRLAJ","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRLAJ","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRLAJ",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Farsight be finished, if you want it.~)
  EndCutSceneMode()
END
/*  c-arSCRLAL Aran PID: Create Scroll of Sunfire */
IF
  GlobalTimerExpired("c-aranscribing","GLOBAL")
  Global("c-aranscribe","GLOBAL",1)
  Global("c-arSCRLAL","LOCALS",1)
  InParty(Myself)
  InMyArea(Player1)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  StartCutSceneMode()
    SetGlobal("c-arSCRLAL","LOCALS",0)
    SetGlobal("c-aranscribe","GLOBAL",0)
    GiveItemCreate("SCRLAL",Myself,1,1,1)
    DisplayStringHead(Myself,~Aye, now, that scroll o' Sunfire be finished, if you want it.~)
  EndCutSceneMode()
END

/* On waking banter, after Underdark : bcs */ 

IF
  PartyRested()
  !GlobalTimerNotExpired("c-aransmalltalk","GLOBAL")
  InParty(Myself)
  Global("c-aranwakeup","LOCALS",0)
  Global("Chapter","GLOBAL",6)
  CombatCounter(0)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  OR(2)
  AreaType(OUTDOOR)
  AreaType(FOREST)
  !AreaType(DUNGEON)
  See(Player1)
THEN
  RESPONSE #100
  SetGlobal("c-aranwakeup","GLOBAL",1)
  SetGlobalTimer("c-aransmalltalk","GLOBAL",300)
  PlaySong(0)
  PlaySound("c-arnfti")
  StartDialogNoSet(Player1)
END

/* Player Stronghold Reactions */

/* Gaining Stronghold Responses : set from .bcs */
/* 1 possible if played without mods, 2 or 3 for multiclass PC's with mods, all of them if one of the multi-stronghold tweaks are installed */
/* old versions = 
IF
Global("c-arants","LOCALS",0)
GlobalGT("PlayerThiefGuild","GLOBAL",0) 
AreaCheck("AR0322")
THEN
RESPONSE #100
SetGlobal("c-arants","LOCALS",1)
END

IF
Global("c-aranrs","LOCALS",0)
GlobalGT("RangerProtector","GLOBAL",0) 
AreaCheck("AR1100")  
THEN
RESPONSE #100
SetGlobal("c-aranrs","LOCALS",1)
END

IF
Global("c-aranps","LOCALS",0)
GlobalGT("PaladinOrder","GLOBAL",0) 
AreaCheck("AR0903")  
THEN
RESPONSE #100
SetGlobal("c-aranps","LOCALS",1)
END

IF
Global("c-aranms","LOCALS",0)
GlobalGT("PCSphere","GLOBAL",0) 
AreaCheck("AR0411")
THEN
RESPONSE #100
SetGlobal("c-aranms","LOCALS",1)
END

IF
Global("c-aranfs","LOCALS",0)
Global("PCKeepOwner","GLOBAL",1) 
AreaCheck("AR1306")
THEN
RESPONSE #100
SetGlobal("c-aranfs","LOCALS",1)
END

IF
Global("c-arands","LOCALS",0)
GlobalGT("DruidStrongHold","GLOBAL",0) 
AreaCheck("AR1900") 2602 
THEN
RESPONSE #100
SetGlobal("c-arands","LOCALS",1)
END

IF
Global("c-arancs","LOCALS",0)
GlobalGT("JoinLathander","GLOBAL",0) 
AreaCheck("AR0902")

GlobalGT("JoinTalos","GLOBAL",0) 
AreaCheck("AR0904")

GlobalGT("JoinHelm","GLOBAL",0) 
AreaCheck("AR0901")
 
THEN
RESPONSE #100
SetGlobal("c-arancs","LOCALS",1)
END

IF
Global("c-aranbs","LOCALS",0)
GlobalGT("Playhouse","GLOBAL",0) 
AreaCheck("AR0523") 
THEN
RESPONSE #100
SetGlobal("c-aranbs","LOCALS",1)
END

*/

/* Easter Egg for Multi-stronghold folks who get all strongholds at once */
IF
Global("c-aranas","LOCALS",0)
GlobalGT("JoinLathander","GLOBAL",0) 
GlobalGT("JoinTalos","GLOBAL",0) 
GlobalGT("JoinHelm","GLOBAL",0) 
GlobalGT("PaladinOrder","GLOBAL",0) 
GlobalGT("Playhouse","GLOBAL",0) 
GlobalGT("PCKeepOwner","GLOBAL",0) 
GlobalGT("PlayerThiefGuild","GLOBAL",0) 
GlobalGT("DruidStrongHold","GLOBAL",0) 
GlobalGT("PCSphere","GLOBAL",0) 
GlobalGT("RangerProtector","GLOBAL",0)   
THEN
RESPONSE #100
SetGlobal("c-aranas","LOCALS",1)
END

/* Bards : Activate */
IF
  Global("Playhouse","GLOBAL",1)
  Global("c-aranbs","LOCALS",0)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  !See([ENEMY])
  !ActuallyInCombat()
THEN
RESPONSE #100
  SetGlobal("c-aranbs","LOCALS",1)
  RealSetGlobalTimer("c-aranstrong","GLOBAL",180)
END

/* Bards : Initiate */
IF
  Global("c-aranbs","LOCALS",1)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  !See([ENEMY])
  !ActuallyInCombat()
THEN
RESPONSE #100
  PlaySong(0)
  PlaySound("c-arnfth")
  StartDialogueNoSet(Player1)
END

/* Clerics : Activate */
IF
  Global("c-arancs","LOCALS",0)
  OR(3)
  Global("JoinLathander","GLOBAL",1)
  Global("JoinTalos","GLOBAL",1)
  Global("JoinHelm","GLOBAL",1)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  !ActuallyInCombat()
  !See([ENEMY])
THEN
  RESPONSE #100
    SetGlobal("c-arancs","LOCALS",1)
    RealSetGlobalTimer("c-aranstrong","GLOBAL",180)
END

/* Clerics : Initiate */
IF
  Global("c-arancs","LOCALS",1)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  !See([ENEMY])
  !ActuallyInCombat()
THEN
  RESPONSE #100
    PlaySong(0)
    PlaySound("c-arnfth")
    StartDialogueNoSet(Player1)
END

/* Druids : Activate */
IF
  Global("DruidStronghold","GLOBAL",1)
  Global("c-arands","LOCALS",0)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  !ActuallyInCombat()
  !See([ENEMY])
THEN RESPONSE #100
  SetGlobal("c-arands","LOCALS",1)
  RealSetGlobalTimer("c-aranstrong","GLOBAL",180)
END

/* Druids : Activate */
IF
  Global("c-arands","LOCALS",1)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  !See([ENEMY])
  !ActuallyInCombat()
THEN
RESPONSE #100
  PlaySong(0)
  PlaySound("c-arnfth")
  StartDialogueNoSet(Player1)
END

/* Fighters : Activate */
IF
  Global("PCKeepOwner","GLOBAL",1)
  Global("c-aranfs","LOCALS",0)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  !ActuallyInCombat()
  !See([ENEMY])
THEN
  RESPONSE #100
  SetGlobal("c-aranfs","LOCALS",1)
  RealSetGlobalTimer("c-aranstrong","GLOBAL",180)
END

/* Fighters : Initiate */
IF
  Global("c-aranfs","LOCALS",1)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  !See([ENEMY])
  !ActuallyInCombat()
THEN
  RESPONSE #100
  PlaySong(0)
  PlaySound("c-arnfth")
  StartDialogueNoSet(Player1)
END

/* Mages : Activate */
IF
  GlobalGT("GettingApprentices","GLOBAL",0)
  Global("c-aranms","LOCALS",0)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  !ActuallyInCombat()
  !See([ENEMY])
THEN
  RESPONSE #100
  SetGlobal("c-aranms","LOCALS",1)
  RealSetGlobalTimer("c-aranstrong","GLOBAL",180)
END

/* Mages : Activate */
IF
  Global("c-aranms","LOCALS",1)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  !See([ENEMY])
  !ActuallyInCombat()
THEN
  RESPONSE #100
  PlaySong(0)
  PlaySound("c-arnfth")
  StartDialogueNoSet(Player1)
END

/* Paladins : Activate */
IF
  Global("PaladinOrder","GLOBAL",1)
  Global("c-aranps","LOCALS",0)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  !ActuallyInCombat()
  !See([ENEMY])
THEN
  RESPONSE #100
  SetGlobal("c-aranps","LOCALS",1)
  RealSetGlobalTimer("c-aranstrong","GLOBAL",180)
END

/* Paladins : Initiate */
IF
  Global("c-aranps","LOCALS",1)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  !See([ENEMY])
  !ActuallyInCombat()
THEN
  RESPONSE #100
  PlaySong(0)
  PlaySound("c-arnfth")
  StartDialogueNoSet(Player1)
END

/* Rangers : Activate */
IF
  Global("RangerProtector","GLOBAL",1)
  Global("c-aranrs","LOCALS",0)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  !ActuallyInCombat()
  !See([ENEMY])
THEN
  RESPONSE #100
  SetGlobal("c-aranrs","LOCALS",1)
  RealSetGlobalTimer("c-aranstrong","GLOBAL",180)
END

/* Rangers : Activate */
IF
  Global("c-aranrs","LOCALS",1)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  !See([ENEMY])
  !ActuallyInCombat()
THEN
  RESPONSE #100
  PlaySong(0)
  PlaySound("c-arnfth")
  StartDialogueNoSet(Player1)
END

/* Got All Strongholds : Activate */
IF
  RealGlobalTimerExpired("c-aranstrong","GLOBAL")
  Global("c-aranrs","LOCALS",2)
  Global("c-aranps","LOCALS",2)
  Global("c-aranms","LOCALS",2)
  Global("c-aranfs","LOCALS",2)
  Global("c-arands","LOCALS",2)
  Global("c-arancs","LOCALS",2)
  Global("c-aranbs","LOCALS",2)
  Global("c-aranas","LOCALS",0)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  !See([ENEMY])
  !ActuallyInCombat()
THEN
  RESPONSE #100
  SetGlobal("c-aranas","LOCALS",1)
  RealSetGlobalTimer("c-aranstrong","GLOBAL",180)
END

/* Got All Strongholds : Initiate */
IF
  RealGlobalTimerExpired("c-aranstrong","GLOBAL")
  Global("c-aranas","LOCALS",1)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  !See([ENEMY])
  !ActuallyInCombat()
THEN
  RESPONSE #100
  PlaySong(0)
  PlaySound("c-arnfth")
  StartDialogueNoSet(Player1)
END


/* FRIEND TALKS
 * OK let's start with the Friend Talks. The idea here is to set the friendtalks up on a BCS <> DLG "bounce", so
 * 1. set the talk variable to 1 and set a timer.
 * 2. set a block that sees that the timer has expired, and initiates dialog.
 * 3. the game looks for the variable (1), and sees the dialog, and fires it.
 * 4. The dialog line advances the variable to (2), and sets a new timer.
 * 5. The BCS here looks for the timer to expire and the even variable (2), advancing to (3) when the timer expires
 * Then when it sees the conditions are right, repeat sequence from 3.
*/

/* Friend Talks Sequence */

/* Friend Talks Setup  */
IF
  Global("c-aranfriendbg2","GLOBAL",0)   // Not evaluated true yet
  InParty(Myself)            // Aran is here
  !StateCheck(Myself,CD_STATE_NOTVALID)  // Aran is ok
THEN
  RESPONSE #100                // 100% of the time
    SetGlobal("c-aranfriendbg2","GLOBAL",1)     //  set up SoA_FT_1
    SetGlobalTimer("c-aranblush","GLOBAL",TEN_DAYS) // set up delay for embarrassment banters 
    RealSetGlobalTimer("c-aranfriendtimer","GLOBAL",120)  // Minimum Real Time until SoA_FT_1  // set test time  <<<
END

/* Aran's FriendTalks Aim, c-aranfriendbg2, ARAN_FTT */
/* This block takes the even variables set in dialog, and advances them to the odd */
IF
  GlobalLT("c-aranfriendbg2","GLOBAL",32)  // shuts down sequence when finished
  RealGlobalTimerExpired("c-aranfriendtimer","GLOBAL")  // Timer Expired
  !Global("Chapter","GLOBAL",5) // Not in Underdark - specialized talks for that
  OR(15)
    Global("c-aranfriendbg2","GLOBAL",2)  // set up SoA_FT_2
    Global("c-aranfriendbg2","GLOBAL",4)  // set up SoA_FT_3
    Global("c-aranfriendbg2","GLOBAL",6)  // set up SoA_FT_4
    Global("c-aranfriendbg2","GLOBAL",8)  // set up SoA_FT_5
    Global("c-aranfriendbg2","GLOBAL",10) // set up SoA_FT_6
    Global("c-aranfriendbg2","GLOBAL",12) // set up SoA_FT_7
    Global("c-aranfriendbg2","GLOBAL",14) // set up SoA_FT_8
    Global("c-aranfriendbg2","GLOBAL",16) // set up SoA_FT_9
    Global("c-aranfriendbg2","GLOBAL",18) // set up SoA_FT_10
    Global("c-aranfriendbg2","GLOBAL",20) // set up SoA_FT_11
    Global("c-aranfriendbg2","GLOBAL",22) // set up SoA_FT_12
    Global("c-aranfriendbg2","GLOBAL",24) // set up SoA_FT_13
    Global("c-aranfriendbg2","GLOBAL",26) // set up SoA_FT_14
 //   Global("c-aranfriendbg2","GLOBAL",28) // set up SoA_FT_15
 //   Global("c-aranfriendbg2","GLOBAL",30) // set up SoA_FT_16
THEN
  RESPONSE #100
    IncrementGlobal("c-aranfriendbg2","GLOBAL",1)  // move up from even to odd
END

/* Aran's FriendTalks Fire, c-aranfriendbg2, ARAN_FTT */
/* This block takes the odd variables set by the last block, and tries to fire them off.  */
IF
  GlobalLT("c-aranfriendbg2","GLOBAL",32)  // shuts down sequence when finished
  !Global("Chapter","GLOBAL",5) // Not in Underdark - specialized talks for that
  RealGlobalTimerExpired("c-aranfriendtimer","GLOBAL")  // Timer Expired
  InParty(Myself)            // Aran is here
  !StateCheck(Myself,CD_STATE_NOTVALID)  // Aran is ok
  !StateCheck(Player1,CD_STATE_NOTVALID) // Player1 is ok
  !ActuallyInCombat()
  !See([ENEMY])  // Can't see any enemies
  OR(16)
    Global("c-aranfriendbg2","GLOBAL",1)   // fire SoA_FT_1
    Global("c-aranfriendbg2","GLOBAL",3)   // fire SoA_FT_2
    Global("c-aranfriendbg2","GLOBAL",5)   // fire SoA_FT_3
    Global("c-aranfriendbg2","GLOBAL",7)   // fire SoA_FT_4
    Global("c-aranfriendbg2","GLOBAL",9)   // fire SoA_FT_5
    Global("c-aranfriendbg2","GLOBAL",11)  // fire SoA_FT_6
    Global("c-aranfriendbg2","GLOBAL",13)  // fire SoA_FT_7
    Global("c-aranfriendbg2","GLOBAL",15)  // fire SoA_FT_8
    Global("c-aranfriendbg2","GLOBAL",17)  // fire SoA_FT_9
    Global("c-aranfriendbg2","GLOBAL",19)  // fire SoA_FT_10
    Global("c-aranfriendbg2","GLOBAL",21)  // fire SoA_FT_11
    Global("c-aranfriendbg2","GLOBAL",23)  // fire SoA_FT_12
    Global("c-aranfriendbg2","GLOBAL",25)  // fire SoA_FT_13
    Global("c-aranfriendbg2","GLOBAL",27)  // fire SoA_FT_14
//    Global("c-aranfriendbg2","GLOBAL",29)  // fire SoA_FT_15
//    Global("c-aranfriendbg2","GLOBAL",31)  // fire SoA_FT_16
THEN
  RESPONSE #100
    PlaySong(0)  // play a blank reference, stoping the soundtrack
    PlaySound("c-arnfth") // play a .wav or .wavc file
    StartDialogueNoSet(Player1)  // Yo, we are talkin', here...
END

/* Aran's Underdark FriendTalks Aim, c-aranfriendud, ARAN_FTT */
/* This block takes the even variables set in dialog, and advances them to the odd */
IF
  Global("Chapter","GLOBAL",5) // In Underdark - specialized talks
  GlobalLT("c-aranfriendud","GLOBAL",8)  // shuts down sequence when finished
  RealGlobalTimerExpired("c-aranfriendtimer","GLOBAL")  // Timer Expired
  OR(4)
    Global("c-aranfriendud","GLOBAL",0)  // set up SoA_UDFT_1
    Global("c-aranfriendud","GLOBAL",2)  // set up SoA_UDFT_2
    Global("c-aranfriendud","GLOBAL",4)  // set up SoA_UDFT_3
    Global("c-aranfriendud","GLOBAL",6)  // set up SoA_UDFT_4
    Global("c-aranfriendud","GLOBAL",8)  // set up SoA_UDFT_5
THEN
  RESPONSE #100
    IncrementGlobal("c-aranfriendud","GLOBAL",1)  // move up from even to odd
END

/* Aran's UnderDark FriendTalks Fire, c-aranfriendbg2, ARAN_FTT, Underdark */
/* This block takes the odd variables set by the last block, and tries to fire them off.  */
IF
  GlobalLT("c-aranfriendud","GLOBAL",8)  // shuts down sequence when finished
  RealGlobalTimerExpired("c-aranfriendtimer","GLOBAL")  // Timer Expired
  Global("Chapter","GLOBAL",5) // In Underdark
  InParty(Myself)            // Aran is here
  !StateCheck(Myself,CD_STATE_NOTVALID)  // Aran is ok
  !StateCheck(Player1,CD_STATE_NOTVALID) // Player1 is ok
  CombatCounter(0)  // Not in combat
  !See([ENEMY])  // Can't see any enemies
  OR(4)
    Global("c-aranfriendud","GLOBAL",1)   // fire SoA_UDFT_1
    Global("c-aranfriendud","GLOBAL",3)   // fire SoA_UDFT_2
    Global("c-aranfriendud","GLOBAL",5)   // fire SoA_UDFT_3
    Global("c-aranfriendud","GLOBAL",7)   // fire SoA_UDFT_4
    Global("c-aranfriendud","GLOBAL",9)   // fire SoA_UDFT_5
THEN
  RESPONSE #100
    PlaySong(0)  // play a blank reference, stoping the soundtrack
    PlaySound("c-arnfti") // play a .wav or .wavc file
    StartDialogueNoSet(Player1)  // Yo, we are talkin', here...
END


/* ROMANCE TALKS */

/* 
 * Romance Match and Initiation (He is not picky...)
 * One new thing here - Aran is ok if a friend switches genders -
 * but not so much on the romance side. So, we add a blocking variable
 * to make sure nothing progresses while that silly Girdle is in place.
 * He can have some special lines to play during the FT sequence on that.
*/

IF
  Global("c-aranmatch","GLOBAL",0)     // Not evaluated
  InParty(Myself)            // Aran is here
  !StateCheck(Myself,CD_STATE_NOTVALID)  // Aran is ok
  !StateCheck(Player1,CD_STATE_NOTVALID) // Player1 is ok
  Gender(Player1,FEMALE)         // Player1 is female
  !HasItemEquiped("belt05",Player1)	   // Girdle of sex change not on Player1
THEN
  RESPONSE #100                // 100% of the time
    SetGlobal("c-aranmatch","GLOBAL",1)  // Matched
    SetGlobal("c-aranrom","GLOBAL",1)  // Aran is interested
    RealSetGlobalTimer("c-aranromtimer","GLOBAL",ARAN_LTT)  // Minimum Real Time until first LT 
    RealSetGlobalTimer("c-aranflirttimer","GLOBAL",ARAN_FLIRT) // Tee up flirt timer 
    SetGlobal("c-aranbg2rom","GLOBAL",1)     //  Tee up SoA_LT_1
END


/* LOVE TALKS */
/* Romance Talks Sequence */

/* Aran's Romance LoveTalks Aim, c-aranbg2rom, ARAN_LTT */
/* This block takes the even variables set in dialog, and advances them to the odd */
IF
  GlobalLT("c-aranbg2rom","GLOBAL",32)  // shuts down sequence when finished
  RealGlobalTimerExpired("c-aranromtimer","GLOBAL")  // Timer Expired
  !Global("Chapter","GLOBAL",5) // Not in Underdark - specialized talks for that
  !HasItemEquiped("belt05",Player1) // Not using Girdle of sex change
  OR(15)
    Global("c-aranbg2rom","GLOBAL",2)  // set up SoA_LT_2
    Global("c-aranbg2rom","GLOBAL",4)  // set up SoA_LT_3
    Global("c-aranbg2rom","GLOBAL",6)  // set up SoA_LT_4
    Global("c-aranbg2rom","GLOBAL",8)  // set up SoA_LT_5
    Global("c-aranbg2rom","GLOBAL",10) // set up SoA_LT_6
    Global("c-aranbg2rom","GLOBAL",12) // set up SoA_LT_7
    Global("c-aranbg2rom","GLOBAL",14) // set up SoA_LT_8
 //   Global("c-aranbg2rom","GLOBAL",16) // set up SoA_LT_9
 //   Global("c-aranbg2rom","GLOBAL",18) // set up SoA_LT_10
 //   Global("c-aranbg2rom","GLOBAL",20) // set up SoA_LT_11    
 //   Global("c-aranbg2rom","GLOBAL",22) // set up SoA_LT_12
 //   Global("c-aranbg2rom","GLOBAL",24) // set up SoA_LT_13
 //   Global("c-aranbg2rom","GLOBAL",26) // set up SoA_LT_14
 //   Global("c-aranbg2rom","GLOBAL",28) // set up SoA_LT_15
 //   Global("c-aranbg2rom","GLOBAL",30) // set up SoA_LT_16
THEN
  RESPONSE #100
    IncrementGlobal("c-aranbg2rom","GLOBAL",1)
END

/* Aran's Romance LoveTalks Fire, c-aranbg2rom, ARAN_LTT */
/* This block takes the odd variables set by the last block, and tries to fire them off.  */
IF
  InParty(Myself)
  See(Player1)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  !StateCheck("c-aran",CD_STATE_NOTVALID)
  GlobalLT("c-aranbg2rom","GLOBAL",32)  // shuts down sequence when finished
  RealGlobalTimerExpired("c-aranromtimer","GLOBAL")  // Timer Expired
  !Global("Chapter","GLOBAL",5) // Not in Underdark - specialized talks for that
  !HasItemEquiped("belt05",Player1) // Not using Girdle of sex change
  CombatCounter(0)  // Not in combat
  !See([ENEMY])  // Can't see any enemies
  OR(16)
    Global("c-aranbg2rom","GLOBAL",1)   // fire SoA_LT_1
    Global("c-aranbg2rom","GLOBAL",3)   // fire SoA_LT_2
    Global("c-aranbg2rom","GLOBAL",5)   // fire SoA_LT_3
    Global("c-aranbg2rom","GLOBAL",7)   // fire SoA_LT_4
    Global("c-aranbg2rom","GLOBAL",9)   // fire SoA_LT_5
    Global("c-aranbg2rom","GLOBAL",11)  // fire SoA_LT_6
    Global("c-aranbg2rom","GLOBAL",13)  // fire SoA_LT_7
    Global("c-aranbg2rom","GLOBAL",15)  // fire SoA_LT_8
 //   Global("c-aranbg2rom","GLOBAL",17)  // fire SoA_LT_9
 //   Global("c-aranbg2rom","GLOBAL",19)  // fire SoA_LT_10
 //   Global("c-aranbg2rom","GLOBAL",21)  // fire SoA_LT_11
 //   Global("c-aranbg2rom","GLOBAL",23)  // fire SoA_LT_12
 //   Global("c-aranbg2rom","GLOBAL",25)  // fire SoA_LT_13
 //   Global("c-aranbg2rom","GLOBAL",27)  // fire SoA_LT_14
 //   Global("c-aranbg2rom","GLOBAL",29)  // fire SoA_LT_15
 //   Global("c-aranbg2rom","GLOBAL",31)  // fire SoA_LT_16
THEN
  RESPONSE #100
    PlaySong(0)
    PlaySound("c-arnltu")
    StartDialogueNoSet(Player1)
END

/* NPC-Initiated Flirts: */

/* Set up flirting for initial entries -  Set through PID flirting a bunch of times */
IF
  Global("c-aranpcflirtstart","GLOBAL",0)
  GlobalGT("c-aranearlyflirt","LOCALS",12)  // try this value - may be too high or too low
  GlobalLT("c-aranfriendbg2","GLOBAL",7)
  GlobalLT("c-aranbg2rom","GLOBAL",7)
  OR(2)
    Global("c-aranrom","GLOBAL",1)
    Global("c-aranrom","GLOBAL",2)
  !HasItemEquiped("belt05",Player1)
THEN RESPONSE #100
  SetGlobal("c-aranpcflirtstart","GLOBAL",1)
  RealSetGlobalTimer("c-aranflirttimer","GLOBAL",ARAN_FLIRT)
END

/* Set Up Flirting After 3 FTs, if player has not taken a shortcut and flirted alot. */
IF
  Global("c-aranpcflirtstart","GLOBAL",0)
  GlobalGT("c-aranfriendbg2","GLOBAL",6)
  OR(2)
    Global("c-aranrom","GLOBAL",1)
    Global("c-aranrom","GLOBAL",2)
  !HasItemEquiped("belt05",Player1)
THEN RESPONSE #100
  SetGlobal("c-aranpcflirtstart","GLOBAL",1)
  RealSetGlobalTimer("c-aranflirttimer","GLOBAL",ARAN_FLIRT)
END

/* Player likes to flirt, 24 interactions by either Aran or PC without shutting him down */
IF
  Global("c-aranpcflirtstart","GLOBAL",1)
  OR(2)
  Global("c-aranrom","GLOBAL",1)
  Global("c-aranrom","GLOBAL",2)
  GlobalGT("c-aranflirt","GLOBAL",24)
  Gender(Player1,FEMALE)
  !HasItemEquiped("belt05",Player1)
THEN 
  RESPONSE #100
    SetGlobal("c-aranrom","GLOBAL",2)
    SetGlobal("c-aranpcflirtstart","GLOBAL",2)
    RealSetGlobalTimer("c-aranflirttimer","GLOBAL",ARAN_FLIRT)
END

/* Lightweight Flirts */
IF
  InParty(Myself)
  Global("c-aranpcflirtstart","GLOBAL",1)
  RealGlobalTimerExpired("c-aranflirttimer","GLOBAL")
  Global("c-aranflirtstop","GLOBAL",0)
  Global("c-aranfight","GLOBAL",0)
  OR(2)
  Global("c-aranrom","GLOBAL",1)
  Global("c-aranrom","GLOBAL",2)
  See(Player1)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  !StateCheck("c-aran",CD_STATE_NOTVALID)
  !HasItemEquiped("belt05",Player1)
  CombatCounter(0)
  !AreaCheck("AR2100") // Underdark
  !AreaCheck("AR2101") // Beholder Cave in Underdark
  !AreaCheck("AR2102") // Adalon's Cave
  !AreaCheck("AR2200") // Ust Natha
  !AreaCheck("AR2201") // Temple in Ust Natha
  !AreaCheck("AR2202") // Inn in Ust Natha 1st Floor
  !AreaCheck("AR2203") // Inn in Ust Natha; 2nd Floor
  !AreaCheck("AR2204") // House in Ust Natha
  !AreaCheck("AR2205") // House in Ust Natha
  !AreaCheck("AR2206") // Qilue's House in Ust Natha
  !AreaCheck("AR2207") // Deirex's Tower in Ust Natha
  !AreaCheck("AR2208") // Jarlaxle's House wherever
  !AreaCheck("AR2209") // Jae'llat's House
  !AreaCheck("AR2210") // Deirex's Cave
  !AreaCheck("AR2400") // Mind Flayers in Underdark
  !AreaCheck("AR2401") // Cave Between Underdark and Exit from Underdark
  !AreaCheck("AR2402") // Kuo Toa in Underdark
THEN 
  RESPONSE #100
    SetGlobal("c-aranlightflirt","GLOBAL",1)
    PlaySong(0)
    PlaySound("c-arnltu")
    StartDialogNoSet(Player1)
END

/* Heavyweight Flirts */
IF
  InParty(Myself)
  Global("c-aranpcflirtstart","GLOBAL",2)
  RealGlobalTimerExpired("c-aranflirttimer","GLOBAL")
  Global("c-aranflirtstop","GLOBAL",0)
  Global("c-aranfight","GLOBAL",0)
  OR(2)
  Global("c-aranrom","GLOBAL",1)
  Global("c-aranrom","GLOBAL",2)
  See(Player1)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  !StateCheck("c-aran",CD_STATE_NOTVALID)
  !HasItemEquiped("belt05",Player1)
  CombatCounter(0)
  !AreaCheck("AR2100")
  !AreaCheck("AR2101")
  !AreaCheck("AR2102")
  !AreaCheck("AR2200")
  !AreaCheck("AR2201")
  !AreaCheck("AR2202")
  !AreaCheck("AR2203")
  !AreaCheck("AR2204")
  !AreaCheck("AR2205")
  !AreaCheck("AR2206")
  !AreaCheck("AR2207")
  !AreaCheck("AR2208")
  !AreaCheck("AR2209")
  !AreaCheck("AR2210")
  !AreaCheck("AR2400")
  !AreaCheck("AR2401")
  !AreaCheck("AR2402")
THEN 
  RESPONSE #100
    SetGlobal("c-aranheavyflirt","GLOBAL",1)
    PlaySong(0)
    PlaySound("c-arnltl")
    StartDialogNoSet(Player1)
END

/* Bedroll... Flirt?  */
/* Lots of Flirts means Player Wants Action */
IF
  InParty(Myself)
  GlobalGT("c-aranflirt","GLOBAL",40)
  Global("c-aranbedflirt","GLOBAL",0)
  Global("c-aranpcflirtstart","GLOBAL",2)
  Global("c-aranflirtstop","GLOBAL",0)
  Global("c-aranfight","GLOBAL",0)
  OR(2)
  Global("c-aranrom","GLOBAL",1)
  Global("c-aranrom","GLOBAL",2)
  See(Player1)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  !StateCheck("c-aran",CD_STATE_NOTVALID)
  CombatCounter(0)
  !AreaCheck("AR2100")
  !AreaCheck("AR2101")
  !AreaCheck("AR2102")
  !AreaCheck("AR2200")
  !AreaCheck("AR2201")
  !AreaCheck("AR2202")
  !AreaCheck("AR2203")
  !AreaCheck("AR2204")
  !AreaCheck("AR2205")
  !AreaCheck("AR2206")
  !AreaCheck("AR2207")
  !AreaCheck("AR2208")
  !AreaCheck("AR2209")
  !AreaCheck("AR2210")
  !AreaCheck("AR2400")
  !AreaCheck("AR2401")
  !AreaCheck("AR2402")
THEN RESPONSE #100
  SetGlobal("c-aranbedflirt","GLOBAL",1)
  SetGlobal("c-aranrom","GLOBAL",2)
  StartDialogNoSet(Player1)
END


/* OK, now on to some fun blocks to play with. These are things Aran can blather on about. */


/* TALKS, FLOATING AND SMALL */
/* Covers both specific reactions, floaters, and any smalltalk reactions (could also be
 * called "after-the-fact interjections")
*/

/* Garden Booty call 

IF
  Global("c-arangardenmakeout","GLOBAL",1)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  CombatCounter(0)
  !See([ENEMY])
THEN
  RESPONSE #100
    // <<START CUTSCENE HERE>>
    StartDialogueNoSet(Player1)
END

*/

/* After-Vampification Talk, Canonical, 2nd Class. */
IF
  !InParty(Myself)
  Global("c-aranvamped","GLOBAL",4)
THEN
  RESPONSE #100
    SetGlobal("c-aranvamped","GLOBAL",5)
    StartDialogueNoSet(Player1)
END

/* Stronghold Commentary */

/* SoA Stronghold Commentary : PC Owns Keep */
IF
  Global("PCKeepOwner","GLOBAL",1)
  Global("c-silencearan","GLOBAL",0) // PID - set silencer
  Global("c-aranpckeep","LOCALS",0)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  CombatCounter(0)
  !See([ENEMY])
THEN
  RESPONSE #100
    SetGlobal("c-aranpckeep","LOCALS",1)
    StartDialogueNoSet(Player1)
END

/* Drunk Talks (incorporates Flirts if gender and romance variables set)  */
/* Using GLOBAL here so it can influence friendtalks */
IF
  GlobalLT("c-arandrunk","GLOBAL",6)  // shuts down sequence when finished
  InParty(Myself)
  CheckStatGT(Myself,50,INTOXICATION)  // Whoot - the room is moving about too much
  OR(13)
    AreaCheck("AR0313") // Sea's Bounty
    AreaCheck("AR0406") // Copper Coronet
    AreaCheck("AR0509") // Five Flagons
    AreaCheck("AR0522") // Five Flagons (Stronghold)
    AreaCheck("AR0704") // Mithrest Inn
    AreaCheck("AR1105") // Umar Inn
    AreaCheck("AR1602") // The Vulgar Monkey
    AreaCheck("AR2010") // Vyatri's Pub, Trademeet
    AreaCheck("AR0709") // Den of the Seven Vales 1st Floor
    AreaCheck("AR0513") // Calbor's Inn at Bridge District 1st Floor
    AreaCheck("AR0021") // Crooked Crane 1st Floor
    AreaCheck("AR1602") // Brynnlaw's Inn
    AreaCheck("C-AR01") // The Broken Sword (Aran's initial inn )
  OR(3)
    Global("c-arandrunk","GLOBAL",0)
    Global("c-arandrunk","GLOBAL",2)
    Global("c-arandrunk","GLOBAL",4)
  InMyArea(Player1)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  CombatCounter(0)
  !See([ENEMY])
THEN
  RESPONSE #100
    IncrementGlobal("c-arandrunk","GLOBAL",1)
END

IF
  GlobalLT("c-arandrunk","GLOBAL",6)  // shuts down sequence when finished
  !GlobalTimerNotExpired("c-aransmalltalk","GLOBAL") // Timer (game-time) has never been set or has expired
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  InMyArea(Player1)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  OR(13)
    AreaCheck("AR0313") // Sea's Bounty
    AreaCheck("AR0406") // Copper Coronet
    AreaCheck("AR0509") // Five Flagons
    AreaCheck("AR0522") // Five Flagons (Stronghold)
    AreaCheck("AR0704") // Mithrest Inn
    AreaCheck("AR1105") // Umar Inn
    AreaCheck("AR1602") // The Vulgar Monkey
    AreaCheck("AR2010") // Vyatri's Pub, Trademeet
    AreaCheck("AR0709") // Den of the Seven Vales 1st Floor
    AreaCheck("AR0513") // Calbor's Inn at Bridge District 1st Floor
    AreaCheck("AR0021") // Crooked Crane 1st Floor
    AreaCheck("AR1602") // Brynnlaw's Inn
    AreaCheck("C-AR01") // The Broken Sword (Aran's initial inn )
  CombatCounter(0)  // Not in combat
  !See([ENEMY])  // Can't see any enemies
  OR(3)
    Global("c-arandrunk","GLOBAL",1)
    Global("c-arandrunk","GLOBAL",3)
    Global("c-arandrunk","GLOBAL",5)
THEN
  RESPONSE #100
    PlaySong(0)
    PlaySound("c-arandf")
    StartDialogueNoSet(Player1)
END

/* Monster Reactions */

/* Commenting on some Monster Encounters, Working for The Man/Undead */
IF
  !GlobalTimerNotExpired("c-aransmalltalk","GLOBAL") // Timer (game-time) has never been set or has expired
  Global("c-silencearan","GLOBAL",0)  // a PID - set "silencer" for folks who hate unsolicited comments
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  InMyArea(Player1)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  OR(9)
    Global("c-aranlich","LOCALS",1)
    Global("c-aranshadelord","LOCALS",1)
    Global("c-arandragon","LOCALS",1)
    Global("c-aranbasilisk","LOCALS",1)
    Global("c-aranettercap","LOCALS",1)
    Global("c-arangolem","LOCALS",1)
    Global("c-aranzombie","LOCALS",1)
    Global("c-aranworkbod","LOCALS",1)
    Global("c-aranworkaran","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobalTimer("c-aransmalltalk","GLOBAL",300) // spaces comments
    StartDialogNoSet(Player1)
END


/* For catching general objects without regard to DVs, we can use a general catch all using the .ids entries -
 * [EA.GENERAL.RACE.CLASS]. An entry of 0 in a field will match any value.
 * For example: [ENEMY.0.0.MAGE] specifies all creatures that are enemies of the party, any general category, any race, mages.
 * Amber uses these to good effect, so I started by borrowing from that code, then readjusting and extending -
*/

/* Liches Are Scary  (Darios) */
IF
  Global("c-silencearan","GLOBAL",0)
  Global("c-aranlich","LOCALS",0)
  OR(2)
    Killed([0.0.LICH])
    Killed([0.0.DEMILICH])
   InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-aranlich","LOCALS",1)
END

/* Shade Lord (Darios)  */
IF
  Killed([0.UNDEAD.SHADOW.SHADOW.0.FEMALE]) // Shade Lord
  Global("c-silencearan","GLOBAL",0)
  Global("c-aranshadelord","LOCALS",0)
  OR(2)
    AreaCheck("AR1400") // Temple ruins
    AreaCheck("AR1404") // Temple ruins restored
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-aranshadelord","LOCALS",1)
END

/* SoA Scenery Talks : Shadow Dragon clobbered c-arshaddrag */
IF
  Global("c-arshaddrag","GLOBAL",0)
  AreaCheck("AR1402")
  Dead("ShaDra01")
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  InMyArea(Player1)
  !StateCheck(Player1,CD_STATE_NOTVALID) 
THEN
  RESPONSE #100
    SetGlobal("c-arshaddrag","GLOBAL",1)
END

IF
  Global("c-arshaddrag","GLOBAL",1)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  InMyArea(Player1)
  !StateCheck(Player1,CD_STATE_NOTVALID) 
THEN
  RESPONSE #100
    StartDialogueNoSet(Player1)
END

/* Aran Dragon-Slayer (Darios) */
IF
  Killed([0.0.DRAGON])
  !AreaCheck("AR2102") // Adalon's cave
  !AreaCheck("AR1402")
  Global("c-silencearan","GLOBAL",0)
  Global("c-arandragon","LOCALS",0)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arandragon","LOCALS",1)
END

/*  Basilisk Baiting */
IF
  Killed([0.0.BASILISK])
  Global("c-silencearan","GLOBAL",0)
  Global("c-aranbasilisk","LOCALS",0)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-aranbasilisk","LOCALS",1)
END

/* Poisonous Cloakwood Ettercaps */
IF
  Killed([0.0.ETTERCAP])
  Global("c-silencearan","GLOBAL",0)
  Global("c-aranettercap","LOCALS",0)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-aranettercap","LOCALS",1)
END

/* Golems are Big Boys */
IF
  Killed([0.0.GOLEM])
  Global("c-silencearan","GLOBAL",0)
  Global("c-arangolem","LOCALS",0)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arangolem","LOCALS",1)
END

/* Zombies: Looks Like Me After A Night On The Town */
IF
  Killed([0.0.ZOMBIE])
  Global("c-silencearan","GLOBAL",0)
  Global("c-aranzombie","LOCALS",0)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-aranzombie","LOCALS",1)
END

/* Real Great Employer, buddy. Someone pass me the Daystar. */
IF
  Global("WorkingForBodhi","GLOBAL",1)
  Global("c-silencearan","GLOBAL",0)
  Global("c-aranworkbod","LOCALS",0)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-aranworkbod","LOCALS",1)
END

/* Real Great Employer, buddy. But at least he's not undead. I think. */
IF
  Global("WorkingForAran","GLOBAL",1)
  Global("c-silencearan","GLOBAL",0)
  Global("c-aranworkaran","LOCALS",1)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-aranworkaran","LOCALS",1)
END

/* Commenting on Phaerie, Leader, Slaver Procession, and a few more */
IF
  !GlobalTimerNotExpired("c-aransmalltalk","GLOBAL") // Timer (game-time) has never been set or has expired
  Global("c-silencearan","GLOBAL",0)  // a PID - set "silencer" for folks who hate unsolicited comments
  OR(4)
    Global("c-aranphaere","LOCALS",1)
    Global("c-aranslaver","LOCALS",1)
    Global("c-aranleader","LOCALS",1)
    Global("c-aranpctired","LOCALS",1)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobalTimer("c-aransmalltalk","GLOBAL",300) // spaces comments
    StartDialogNoSet(Player1)
END

/* Phaere is a hawt chick (male PC); is no good for you (female PC); better not have touched you (Romance) */
IF
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  OR(2)
    Global("PhaereInnuendo","GLOBAL",2)
    Global("PhaereInnuendo","GLOBAL",3)
  Global("c-aranphaere","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("c-aranphaere","LOCALS",1)
END

/* Slums Slavers (Darios, extended) */
IF
  AreaCheck("AR0400")  // The Slums
  Global("c-aranslaver","LOCALS",0)
  OR(3)
  See("SlumsSlaver2")
  See("SlumsSlaver3")
  See("SlumsSlave1")
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-aranslaver","LOCALS",1)
END

/* Setting Aran as Leader */
IF
  Global("c-aranleader","LOCALS",0)
  Name("c-aran",Player1Fill)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-aranleader","LOCALS",1)
END

/* You look dead on your feet */
IF
  CheckStatGT(Player1,6,FATIGUE)
  Global("c-aranpctired","LOCALS",0)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-aranpctired","LOCALS",1)
END

/* Scenery Dialog : Graveyard */
IF
  AreaCheck("AR0800")
  Global("c-arangravecomment","LOCALS",0)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arangravecomment","LOCALS",1)
END

IF
  Global("c-arangravecomment","LOCALS",1)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    StartDialogueNoSet(Player1)
END 

IF
  Global("PlayerThiefGuild","GLOBAL",1)
  Global("c-aranguild","LOCALS",0)
  AreaCheck("AR0300")
THEN
  RESPONSE #100
    SetGlobal("c-aranguild","LOCALS",1)
END

/* Scenery Dialog : Temple Comments, Only If Not A Cleric (even minimal training would keep him from starting a holy fight) Firing */
IF
  !Class(Myself,CLERIC_ALL)
  !GlobalTimerNotExpired("c-aransmalltalk","GLOBAL") // Timer (game-time) has never been set or has expired
  Global("c-silencearan","GLOBAL",0)  // a PID - set "silencer" for folks who hate unsolicited comments
  OR(4)
    Global("c-aranoghma","LOCALS",1)
    Global("c-aranilmater","LOCALS",1)
    Global("c-aranhelm","LOCALS",1)
    Global("c-aranlath","LOCALS",1)
    // Global("c-arantalos","LOCALS",1)
    Global("c-aranumberlee","LOCALS",1)
    Global("c-aranwaukeen","LOCALS",1)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobalTimer("c-aransmalltalk","GLOBAL",300) // spaces comments
    StartDialogNoSet(Player1)
END

/* Scenery Dialog : Temple Comments, Only If Not A Cleric (even minimal training would keep him from starting a holy fight)  */
IF
  !Class(Myself,CLERIC_ALL)
  Global("c-silencearan","GLOBAL",0)
  Global("c-aranoghma","LOCALS",0)
  AreaCheck("AR0319") //  Temple of Oghma
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-aranoghma","LOCALS",1)
END

IF
  !Class(Myself,CLERIC_ALL)
  Global("c-silencearan","GLOBAL",0)
  Global("c-aranilmater","LOCALS",0)
  OR(2)
    AreaCheck("AR0408") //  Temple of Ilmater
    AreaCheck("AR0703") //  Temple of Ilmater
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
  SetGlobal("c-aranilmater","LOCALS",1)
END

IF
  !Class(Myself,CLERIC_ALL)
  Global("c-silencearan","GLOBAL",0)
  Global("c-aranhelm","LOCALS",0)
  OR(2)
    AreaCheck("AR0512") //  Temple of Helm
    AreaCheck("AR0901") //  Temple of Helm
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-aranhelm","LOCALS",1)
END

IF
  !Class(Myself,CLERIC_ALL)
  Global("c-silencearan","GLOBAL",0)
  Global("c-aranlath","LOCALS",0)
  AreaCheck("AR0902") //  Temple of Lathander
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-aranlath","LOCALS",1)
END

/*
IF
  !Class(Myself,CLERIC_ALL)
  Global("c-silencearan","GLOBAL",0)
  Global("c-arantalos","LOCALS",0)
  AreaCheck("AR0904") //  Temple of Talos
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arantalos","GLOBAL",1)
END
*/

IF
  !Class(Myself,CLERIC_ALL)
  Global("c-silencearan","GLOBAL",0)
  Global("c-aranumberlee","LOCALS",0)
  AreaCheck("AR1604") //  Temple of Umberlee
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-aranumberlee","LOCALS",1)
END

IF
  !Class(Myself,CLERIC_ALL)
  Global("c-silencearan","GLOBAL",0)
  Global("c-aranwaukeen","LOCALS",0)
  OR(2)
    AreaCheck("AR1010") //  Temple of Waukeen
    AreaCheck("AR2008") //  Temple of Waukeen
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-aranwaukeen","LOCALS",1)
END

/*  Gavin Raised From The Dead */
IF
  GlobalGT("B!GavRaised","GLOBAL",1)
  Global("c-argavinraised","GLOBAL",0)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-argavinraised","GLOBAL",1)
    StartDialogueNoSet(Player1)
END

/* Scenery DisplayStringHead : Childish Jokes Are Almost Always Funny  */
IF
  Global("c-silencearan","GLOBAL",0)
  GlobalTimerExpired("c-arananomensilly","GLOBAL")
  OR(2)
    GlobalGT("c-arananomen","GLOBAL",0)
    GlobalGT("c-anomenaran","GLOBAL",0)
  Global("c-arananomenf","LOCALS",0)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  InParty("Anomen")
  !StateCheck("Anomen",CD_STATE_NOTVALID)
  !StateCheck("Anomen",CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    DisplayStringHead(Myself,~*BUUURRPPPP*~)
    Wait(2)
    DisplayStringHead("Anomen",~Control yourself, Whitehand. That is churlish behavior.~)
    Wait(2)
    DisplayStringHead(Myself,~Sir, Yes Sir. No more loud burpin', Sir.~)
    Wait(3)
    DisplayStringHead(Myself,~*fffbbbbbt*~)
    Wait(2)
    SetGlobal("c-arananomenf","LOCALS",1)
    SetGlobalTimer("c-aransmalltalk","GLOBAL",300)
END

/* Scenery Dialog : Inked or Stolen Letters 1 */
IF
  GlobalTimerExpired("c-aranlettertalk","GLOBAL")
  Global("c-arannosecrets","GLOBAL",1)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arannosecrets","GLOBAL",2)
    StartDialogueNoSet(Player1)
END

 /* Scenery Dialog : Inked or Stolen Letters 1 */
IF
  GlobalTimerExpired("c-aranlettertalk","GLOBAL")
  Global("c-arlettertaken","GLOBAL",1)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
THEN
  RESPONSE #100
    SetGlobal("c-arlettertaken","GLOBAL",2)
    StartDialogueNoSet(Player1)
END 

/* from usual NPCs */
IF
  Allegiance(Myself,ENEMY)
  !InParty(Myself)
  Global("NPCFight","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("NPCFight","LOCALS",1)
    ChangeAIScript("",DEFAULT)
    ChangeAIScript("useitem",GENERAL)
    ChangeAIScript("c-aranx",SPECIFICS)
    SetDialog("")
    Continue()
END

IF
  Allegiance(Myself,NEUTRAL)
  AttackedBy([GOODCUTOFF],DEFAULT)
THEN
  RESPONSE #100
    ChangeAIScript("c-aranx",SPECIFICS)
    ChangeAIScript("useitem",GENERAL)
    ChangeAIScript("",DEFAULT)
    Enemy()
    Continue()
END

IF
  !Allegiance(Myself,ENEMY)
  !InParty(Myself)
  Global("NPCFight","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("NPCFight","LOCALS",0)
    ChangeAIScript("",GENERAL)
    ChangeAIScript("",SPECIFICS)
    Continue()
END