/* On initial join, leveling to get closer to PC's level - SoA only (ToB is too short to expect that most folks do the pickup/dropoff) */ 
/* rank 1 - no change */ 
IF
  Global("c-araninitiallevel","GLOBAL",0)
  XPLT(Player1,225001)
THEN
  RESPONSE #100
     SetGlobal("c-araninitiallevel","GLOBAL",1)
END
/* rank 2 - +150000 */ 
IF
  Global("c-araninitiallevel","GLOBAL",0)
  XPGT(Player1,225000)
  XPLT(Player1,450001)
THEN
  RESPONSE #100
     AddXPObject("c-aran",150000) 
     SetGlobal("c-araninitiallevel","GLOBAL",2)
END
/* rank 3 - +400000 */
IF
  Global("c-araninitiallevel","GLOBAL",0)
  XPGT(Player1,450000)
  XPLT(Player1,675001)
THEN
  RESPONSE #100
     AddXPObject("c-aran",400000) 
    SetGlobal("c-araninitiallevel","GLOBAL",3)
END
/* rank 4 - +625000 */
IF
  Global("c-araninitiallevel","GLOBAL",0)
  XPGT(Player1,675000)
  XPLT(Player1,900001)
THEN
  RESPONSE #100
     AddXPObject("c-aran",625000) 
     SetGlobal("c-araninitiallevel","GLOBAL",4)
END
/* rank 5 - +850000 */
IF
  Global("c-araninitiallevel","GLOBAL",0)
  XPGT(Player1,900000)
  XPLT(Player1,1125001)
THEN
  RESPONSE #100
     AddXPObject("c-aran",850000) 
     SetGlobal("c-araninitiallevel","GLOBAL",5)
END
/* rank 6 - +1050000 */
IF
  Global("c-araninitiallevel","GLOBAL",0)
  XPGT(Player1,1125000)
THEN
  RESPONSE #100
     AddXPObject("c-aran",1050000) 
     SetGlobal("c-araninitiallevel","GLOBAL",6)
END

/* tracking intimacy levels */
/* look for incrementing relationship to kissing */
IF
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	Global("c-aranintimate","GLOBAL",1) // we kissed...
	GlobalLT("c-aransex","GLOBAL",1) // not registered...
	Gender(Player1,FEMALE)
	!HasItemEquiped("belt05",Player1)
THEN
	RESPONSE #100
		SetGlobal("c-aransex","GLOBAL",1) // we kissed.
END
/* look for incrementing relationship to kissing + touching */
IF
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	Global("c-aranintimate","GLOBAL",2) // kissed and touched
	GlobalLT("c-aransex","GLOBAL",2) // not registered
	Gender(Player1,FEMALE)
	!HasItemEquiped("belt05",Player1)
THEN
	RESPONSE #100
		SetGlobal("c-aransex","GLOBAL",2) // we kissed and touched
END
/* look for incrementing relationship to petting */
IF
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	Global("c-aranintimate","GLOBAL",3) // we went further, but not the big one
	GlobalLT("c-aransex","GLOBAL",3) // not registered
	Gender(Player1,FEMALE)
	!HasItemEquiped("belt05",Player1)
THEN
	RESPONSE #100
		SetGlobal("c-aransex","GLOBAL",3) // we went further, but not the big one
END
/* look for incrementing relationship to full intimacy */
IF
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	Global("c-aranintimate","GLOBAL",4) // shared everything
	GlobalLT("c-aransex","GLOBAL",4)
	Gender(Player1,FEMALE)
	!HasItemEquiped("belt05",Player1)
THEN
	RESPONSE #100
		SetGlobal("c-aransex","GLOBAL",4) // shared everything
END
/* Watcher's Keep : Activate */
IF
	Global("c-aranwatchkeep","GLOBAL",0)
	AreaCheck("AR3000") 
	Global("OpenDungeonDoor5","GLOBAL",0)
	CombatCounter(0)
	!See([ENEMY])
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	InMyArea(Player1)
	!StateCheck(Player1,CD_STATE_NOTVALID) 
THEN
	RESPONSE #100
		SetGlobal("c-aranwatchkeep","GLOBAL",1)
END
/* Watcher's Keep : Initiate */
IF
	Global("c-aranwatchkeep","GLOBAL",1)
	CombatCounter(0)
	!See([ENEMY])
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	InMyArea(Player1)
	!StateCheck(Player1,CD_STATE_NOTVALID) 
THEN
	RESPONSE #100
		PlaySong(0)
		PlaySound("c-arnfth")
		StartDialogueNoSet(Player1)
END
/* Sparring, females ; Morning After talk : heavy making out or bedding */
IF
	Global("c-aranspar","GLOBAL",7)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	OR(27)
		AreaCheck("AR0085")
		AreaCheck("AR1100")
		AreaCheck("AR1101")
		AreaCheck("AR1102")
		AreaCheck("AR1104")
		AreaCheck("AR1105")
		AreaCheck("AR1106")
		AreaCheck("AR1107")
		AreaCheck("AR1200")
		AreaCheck("AR1204")
		AreaCheck("AR1300")
		AreaCheck("AR1304")
		AreaCheck("AR1400")
		AreaCheck("AR1404")
		AreaCheck("AR1700")
		AreaCheck("AR1800")
		AreaCheck("AR1900")
		AreaCheck("AR1901")
		AreaCheck("AR1902")
		AreaCheck("AR1904")
		AreaCheck("AR1905")
		AreaCheck("AR2500")
		AreaCheck("AR2600")
		AreaCheck("AR2602")
		AreaCheck("AR2603")
		AreaCheck("AR2700")
		AreaCheck("AR2800")
THEN
	RESPONSE #100
		SetGlobal("c-aranspar","GLOBAL",8)
		PlaySong(0)
		PlaySound("c-arnltl")
		StartDialogNoSet(Player1)
END
/* Sparring, females ; Morning After talk : kissing or making out */
IF
	Global("c-aranspar","GLOBAL",10)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	OR(27)
		AreaCheck("AR0085")
		AreaCheck("AR1100")
		AreaCheck("AR1101")
		AreaCheck("AR1102")
		AreaCheck("AR1104")
		AreaCheck("AR1105")
		AreaCheck("AR1106")
		AreaCheck("AR1107")
		AreaCheck("AR1200")
		AreaCheck("AR1204")
		AreaCheck("AR1300")
		AreaCheck("AR1304")
		AreaCheck("AR1400")
		AreaCheck("AR1404")
		AreaCheck("AR1700")
		AreaCheck("AR1800")
		AreaCheck("AR1900")
		AreaCheck("AR1901")
		AreaCheck("AR1902")
		AreaCheck("AR1904")
		AreaCheck("AR1905")
		AreaCheck("AR2500")
		AreaCheck("AR2600")
		AreaCheck("AR2602")
		AreaCheck("AR2603")
		AreaCheck("AR2700")
		AreaCheck("AR2800")
THEN
	RESPONSE #100
		SetGlobal("c-aranspar","GLOBAL",11)
		PlaySong(0)
		PlaySound("c-arnltl")
		StartDialogNoSet(Player1)
END
/* Sparring, females : Morning After : disable if it doesn't fire in the morning - identify by global set to 15 */
IF
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	OR(2)
	  Global("c-aranspar","GLOBAL",7)
	  Global("c-aranspar","GLOBAL",10)
	!AreaCheck("AR0085")
	!AreaCheck("AR1100")
	!AreaCheck("AR1101")
	!AreaCheck("AR1102")
	!AreaCheck("AR1104")
	!AreaCheck("AR1105")
	!AreaCheck("AR1106")
	!AreaCheck("AR1107")
	!AreaCheck("AR1200")
	!AreaCheck("AR1204")
	!AreaCheck("AR1300")
	!AreaCheck("AR1304")
	!AreaCheck("AR1400")
	!AreaCheck("AR1404")
	!AreaCheck("AR1700")
	!AreaCheck("AR1800")
	!AreaCheck("AR1900")
	!AreaCheck("AR1901")
	!AreaCheck("AR1902")
	!AreaCheck("AR1904")
	!AreaCheck("AR1905")
	!AreaCheck("AR2500")
	!AreaCheck("AR2600")
	!AreaCheck("AR2602")
	!AreaCheck("AR2603")
	!AreaCheck("AR2700")
	!AreaCheck("AR2800")
THEN
	RESPONSE #100
		SetGlobal("c-aranspar","GLOBAL",15)
END
/* On waking banter, after Underdark : bcs */ 
IF
	PartyRested()
	InParty(Myself)
	Global("c-aranwakeup","LOCALS",0)
	GlobalGT("Chapter","GLOBAL",%bg2_chapter_5%)
	!Global("c-aranspar","GLOBAL",7)
	CombatCounter(0)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	InMyArea(Player1)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	OR(27)
		AreaCheck("AR0085")
		AreaCheck("AR1100")
		AreaCheck("AR1101")
		AreaCheck("AR1102")
		AreaCheck("AR1104")
		AreaCheck("AR1105")
		AreaCheck("AR1106")
		AreaCheck("AR1107")
		AreaCheck("AR1200")
		AreaCheck("AR1204")
		AreaCheck("AR1300")
		AreaCheck("AR1304")
		AreaCheck("AR1400")
		AreaCheck("AR1404")
		AreaCheck("AR1700")
		AreaCheck("AR1800")
		AreaCheck("AR1900")
		AreaCheck("AR1901")
		AreaCheck("AR1902")
		AreaCheck("AR1904")
		AreaCheck("AR1905")
		AreaCheck("AR2500")
		AreaCheck("AR2600")
		AreaCheck("AR2602")
		AreaCheck("AR2603")
		AreaCheck("AR2700")
		AreaCheck("AR2800")
THEN
	RESPONSE #100
		SetGlobal("c-aranwakeup","LOCALS",1)
		PlaySong(0)
		PlaySound("c-arnfti")
		StartDialogNoSet(Player1)
END
/* If the party visits the Trademeet Bar, */
IF
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	InMyArea(Player1)
	TimeofDay(NIGHT)
	Global("c-aranrom","GLOBAL",2)
	Global("c-aranmalcer","GLOBAL",0)
	AreaCheck("AR2010")
THEN
	RESPONSE #100
		SetGlobal("c-aranmalcer","GLOBAL",1)
END
/* then set up a spawn when you go outside into AR2000... */
IF
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	InMyArea(Player1)
	Global("c-aranmalcer","GLOBAL",1)
	AreaCheck("AR2000")
THEN
	RESPONSE #100
		StartCutSceneMode()
			CreateCreature("c-malcer",[1874.2195],0)	
			CreateCreature("c-oskut",[1915.2181],0)	
			CreateCreature("c-taman",[1900.2096],0)
			SetGlobal("c-aranmalcer","GLOBAL",2)
		EndCutSceneMode()
END
/* ... and shut it down if you leave the area before things happen. */
IF
	InParty(Myself)
	Global("c-aranmalcer","GLOBAL",1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!AreaCheck("AR2010")
	!AreaCheck("AR2000")
THEN
	RESPONSE #100
		SetGlobal("c-aranmalcer","GLOBAL",0)
END
/* Check for Vyatri's Pub Encounter in romance, battle completed */
IF
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	InMyArea(Player1)
	Global("c-arbarfight","GLOBAL",1)
	Dead("c-malcer")	
	Dead("c-oskut")	
	Dead("c-taman")
	AreaCheck("AR2000")
THEN
	RESPONSE #100
		SetGlobal("c-arbarfight","GLOBAL",2)
END
/* then initiate conversation in AR2000... */
IF
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	InMyArea(Player1)
	Global("c-arbarfight","GLOBAL",2)
	AreaCheck("AR2000")
THEN
	RESPONSE #100
		StartDialogueNoSet(Player1)
		
END
/* ... and shut it down if you leave the area before it fires. */
IF
	InParty(Myself)
	Global("c-arbarfight","GLOBAL",2)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!AreaCheck("AR2000")
THEN
	RESPONSE #100
		SetGlobal("c-arbarfight","GLOBAL",3)  // 0 = not initiated; 1 = initiated; 2 = fired; 3 = talk done or player left area before it fired.
END

/* Closing Reaction Blocks (Backup) based on Berelide's work */

/* Backing out RE Reactions */

/* Romantic Encounters: Weathermistress Ada */
IF
	InParty(Myself)
	Global("RE_AdaSex","GLOBAL",1)
	Global("c-arnREAda","LOCALS",0)
	!AreaCheck("AR0904")
	!AreaCheck("AR0900")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnREAda","LOCALS",3)
END
/* Weathermistress Ada Comment */
IF
	InParty(Myself)
	Global("RE_AdaSex","GLOBAL",1)
	Global("c-arnREAda","LOCALS",0)
	AreaCheck("AR0904")
	AreaCheck("AR0900")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnREAda","LOCALS",1) // NOT IN!
END
/* Romantic Encounters: Anishai */
IF
	InParty(Myself)
	Global("RE_AnishaiFlirt","GLOBAL",1)
	Global("c-arnREAni","LOCALS",0)
	!AreaCheck("AR0303")
	!AreaCheck("AR0304")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnREAnishai","LOCALS",3)
END
/* Romantic Encounters: Anishai Comment */
IF
	InParty(Myself)
	Global("RE_AnishaiFlirt","GLOBAL",1)
	Global("c-arnREAni","LOCALS",0)
	!AreaCheck("AR0303")
	!AreaCheck("AR0304")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnREAnishai","LOCALS",1) // NOT IN
END
/* Romantic Encounters: Aran Linvail */
IF
	InParty(Myself)
	Global("RE_AranFlirt","GLOBAL",1)
	Global("c-arnREAran","LOCALS",0)
	Gender(Player1,FEMALE)
	!AreaCheck("AR0307")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnREAran","LOCALS",9)
END
/* Romantic Encounters: Aran Linvail Comment */
IF
	InParty(Myself)
	Global("RE_AranFlirt","GLOBAL",1)
	Global("c-arnREAran","LOCALS",0)
	Gender(Player1,FEMALE)
	!AreaCheck("AR0307")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnREAran","LOCALS",9)
END
/* Romantic Encounters: Bjornin	*/
IF
	InParty(Myself)
	Global("RE_BjorninFlirt","GLOBAL",1)
	Global("c-arnREBjorn","LOCALS",0)
	Gender(Player1,FEMALE)
	!AreaCheck("AR0903")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnREBjorn","LOCALS",9)
END
/* Romantic Encounters: Bjornin Comment	*/
IF
	InParty(Myself)
	Global("RE_BjorninFlirt","GLOBAL",1)
	Global("c-arnREBjorn","LOCALS",0)
	Gender(Player1,FEMALE)
	!AreaCheck("AR0903")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnREBjorn","LOCALS",9)
END
/* Romantic Encounters: Bodhi	*/
IF
	InParty(Myself)
	Global("RE_BodhiFlirt","GLOBAL",1)
	Global("c-arnREBodhi","LOCALS",0)
	!AreaCheck("AR0801")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnREBodhi","LOCALS",9)
END
/* Romantic Encounters: Bodhi Comment */
IF
	InParty(Myself)
	Global("RE_BodhiFlirt","GLOBAL",1)
	Global("c-arnREBodhi","LOCALS",0)
	!AreaCheck("AR0801")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnREBodhi","LOCALS",9)
END
/* Romantic Encounters: Chanelle */
IF
	InParty(Myself)
	Global("RE_ChanelleFlirt","GLOBAL",1)
	Global("c-arnREChanelle","LOCALS",0)
	Gender(Player1,FEMALE)
	!AreaCheck("AR1307")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnREChanelle","LOCALS",9)
END
/* Romantic Encounters: Chanelle Comment */
IF
	InParty(Myself)
	Global("RE_ChanelleFlirt","GLOBAL",1)
	Global("c-arnREChanelle","LOCALS",0)
	Gender(Player1,FEMALE)
	!AreaCheck("AR1307")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnREChanelle","LOCALS",9)
END
/* Romantic Encounters: Coran	*/
IF
	InParty(Myself)
	Global("RE_CoranSex","GLOBAL",1)
	Global("c-arnRECoran","LOCALS",0)
	!AreaCheck("AR2600")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnRECoran","LOCALS",9)
END
/* Romantic Encounters: Coran Comment */
IF
	InParty(Myself)
	Global("RE_CoranSex","GLOBAL",1)
	Global("c-arnRECoran","LOCALS",0)
	!AreaCheck("AR2600")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnRECoran","LOCALS",9)
END
/* Romantic Encounters: Desharik	*/
IF
	InParty(Myself)
	Global("RE_DesharikFlirt","GLOBAL",1)
	Global("c-arnREDesharik","LOCALS",0)
	!AreaCheck("AR1601")
	!AreaCheck("AR1515")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnREDesharik","LOCALS",9)
END
/* Romantic Encounters: Desharik Comment */
IF
	InParty(Myself)
	Global("RE_DesharikFlirt","GLOBAL",1)
	Global("c-arnREDesharik","LOCALS",0)
	!AreaCheck("AR1601")
	!AreaCheck("AR1515")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnREDesharik","LOCALS",9)
END
/* Romantic Encounters: Edwin	*/
IF
	InParty(Myself)
	Global("RE_EdwinSex","GLOBAL",1)
	Global("c-arnREEdwin","LOCALS",0)
	!AreaCheck("AR1100")
	!AreaCheck("AR1200")
	!AreaCheck("AR1300")
	!AreaCheck("AR1304")
	!AreaCheck("AR1400")
	!AreaCheck("AR1404")
	!AreaCheck("AR1500")
	!AreaCheck("AR1600")
	!AreaCheck("AR1700")
	!AreaCheck("AR1800")
	!AreaCheck("AR1900")
	!AreaCheck("AR2000")
	!AreaCheck("AR2500")
	!AreaCheck("AR2600")
	!AreaCheck("AR2700")
	!AreaCheck("AR2800")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnREEdwin","LOCALS",9)
END
/* ? Edwin ? */

/* Romantic Encounters: Eldoth	*/
IF
	InParty(Myself)
	Global("RE_EldothFlirt","GLOBAL",1)
	Global("c-arnREEldoth","LOCALS",0)
	!AreaCheck("AR0709")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnREEldoth","LOCALS",9)
END
/* Romantic Encounters: Eldoth Comment */
IF
	InParty(Myself)
	Global("RE_EldothFlirt","GLOBAL",1)
	Global("c-arnREEldoth","LOCALS",0)
	!AreaCheck("AR0709")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnREEldoth","LOCALS",9)
END
/* Romantic Encounters: Gaelan Bayle */
IF
	InParty(Myself)
	Global("RE_GaelanFlirt","GLOBAL",1)
	Global("c-arnREGaelan","LOCALS",0)
	!AreaCheck("AR0311")
	!AreaCheck("AR0400")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnREGaelan","LOCALS",9)
END
/* Romantic Encounters: Gaelan Bayle Comment */
IF
	InParty(Myself)
	Global("RE_GaelanFlirt","GLOBAL",1)
	Global("c-arnREGaelan","LOCALS",0)
	!AreaCheck("AR0311")
	!AreaCheck("AR0400")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnREGaelan","LOCALS",9)
END
/* Romantic Encounters: Garren Windspear	*/
IF
	InParty(Myself)
	Global("RE_GarrenFlirt","GLOBAL",1)
	Global("c-arnREGarren","LOCALS",0)
	!AreaCheck("AR1204")
	!AreaCheck("AR1200")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnREGarren","LOCALS",9)
END
/* Romantic Encounters: Garren Windspear Comment */
IF
	InParty(Myself)
	Global("RE_GarrenFlirt","GLOBAL",1)
	Global("c-arnREGarren","LOCALS",0)
	!AreaCheck("AR1204")
	!AreaCheck("AR1200")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnREGarren","LOCALS",9)
END
/* Romantic Encounters: Jarlaxle */
IF
	InParty(Myself)
	Global("RE_JarlaxleFlirt","GLOBAL",1)
	Global("c-arnREJarlaxle","LOCALS",0)
	!AreaCheck("AR2208")
	!AreaCheck("AR2200")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnREJarlaxle","LOCALS",9)
END
/* Romantic Encounters: Jarlaxle Comment */
IF
	InParty(Myself)
	Global("RE_JarlaxleFlirt","GLOBAL",1)
	Global("c-arnREJarlaxle","LOCALS",0)
	!AreaCheck("AR2208")
	!AreaCheck("AR2200")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnREJarlaxle","LOCALS",9)
END
/* Romantic Encounters: Laran	*/
IF
	InParty(Myself)
	Global("RE_LaranFlirt","GLOBAL",1)
	Global("c-arnRELaran","LOCALS",0)
	!AreaCheck("AR0704")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnRELaran","LOCALS",9)
END
/* Romantic Encounters: Laran Comment */
IF
	InParty(Myself)
	Global("RE_LaranFlirt","GLOBAL",1)
	Global("c-arnRELaran","LOCALS",0)
	!AreaCheck("AR0704")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnRELaran","LOCALS",9)
END
/* Romantic Encounters: Logan	*/
IF
	InParty(Myself)
	Global("RE_LoganFlirt","GLOBAL",1)
	Global("c-arnRELogan","LOCALS",0)
	!AreaCheck("AR2007")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnRELogan","LOCALS",9)
END
/* Romantic Encounters: Logan Comment */
IF
	InParty(Myself)
	Global("RE_LoganFlirt","GLOBAL",1)
	Global("c-arnRELogan","LOCALS",0)
	!AreaCheck("AR2007")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnRELogan","LOCALS",9)
END
/* Romantic Encounters: Mekrath */
IF
	InParty(Myself)
	Global("RE_MekrathFlirt","GLOBAL",1)
	Global("c-arnREMekrath","LOCALS",0)
	!AreaCheck("AR0705")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnREMekrath","LOCALS",9)
END
/* Romantic Encounters: Mekrath Comment */
IF
	InParty(Myself)
	Global("RE_MekrathFlirt","GLOBAL",1)
	Global("c-arnREMekrath","LOCALS",0)
	!AreaCheck("AR0705")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnREMekrath","LOCALS",9)
END
/* Romantic Encounters: Noober	*/
IF
	InParty(Myself)
	Global("RE_NooberFlirt","GLOBAL",1)
	Global("c-arnRENoober","LOCALS",0)
	!AreaCheck("AR0513")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnRENoober","LOCALS",9)
END
/* Romantic Encounters: Noober Comment */
IF
	InParty(Myself)
	Global("RE_NooberFlirt","GLOBAL",1)
	Global("c-arnRENoober","LOCALS",0)
	!AreaCheck("AR0513")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnRENoober","LOCALS",9)
END

/* Romantic Encounters: Renal less */
IF
	InParty(Myself)
	Global("RE_RenalFlirt","GLOBAL",1)
	Global("c-arnRERenalFlirt","LOCALS",0)
	!AreaCheck("AR0306")
	!AreaCheck("AR0305")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnRERenalFlirt","LOCALS",9)
END
/* Romantic Encounters: Renal Comment less */
IF
	InParty(Myself)
	Global("RE_RenalFlirt","GLOBAL",1)
	Global("c-arnRERenalFlirt","LOCALS",0)
	!AreaCheck("AR0306")
	!AreaCheck("AR0305")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnRERenalFlirt","LOCALS",9)
END
/* Romantic Encounters: Renal more */
IF
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	Global("RE_RenalSex","GLOBAL",1)
	Global("c-arnRERenal","LOCALS",0)
	!AreaCheck("AR0021")	 // Crooked Crane, 1st floor
	!AreaCheck("AR0313")	 // Sea's Bounty, 1st floor
	!AreaCheck("AR0406")	 // Copper Coronet
	!AreaCheck("AR0509")	 // Five Flagons, 1st floor
	!AreaCheck("AR0513")	 // Delosar's, 1st floor
	!AreaCheck("AR0522")	 // Five Flagons, 1st floor (stronghold)
	!AreaCheck("AR0704")	 // Mithrest Inn
	!AreaCheck("AR0709")	 // Den of the Seven Vales
THEN
	RESPONSE #100
		SetGlobal("c-arnRERenal","LOCALS",9)
END
/* Romantic Encounters: Renal Comment more */
IF
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	Global("RE_RenalSex","GLOBAL",1)
	Global("c-arnRERenal","LOCALS",0)
	!AreaCheck("AR0021")	 // Crooked Crane, 1st floor
	!AreaCheck("AR0313")	 // Sea's Bounty, 1st floor
	!AreaCheck("AR0406")	 // Copper Coronet
	!AreaCheck("AR0509")	 // Five Flagons, 1st floor
	!AreaCheck("AR0513")	 // Delosar's, 1st floor
	!AreaCheck("AR0522")	 // Five Flagons, 1st floor (stronghold)
	!AreaCheck("AR0704")	 // Mithrest Inn
	!AreaCheck("AR0709")	 // Den of the Seven Vales
THEN
	RESPONSE #100
		SetGlobal("c-arnRERenal","LOCALS",9)
END
/* Romantic Encounters: Ribald	*/
IF
	InParty(Myself)
	Global("RE_RibaldFlirt","GLOBAL",1)
	Global("c-arnRERibaldFlirt","LOCALS",0)
	!AreaCheck("AR0702")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnRERibaldFlirt","LOCALS",9)
END
/* Romantic Encounters: Ribald Sex	*/
IF
	InParty(Myself)
	Global("RE_RibaldSex","GLOBAL",1)
	Global("c-arnRERibald","LOCALS",0)
	!AreaCheck("AR0702")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnRERibald","LOCALS",9)
END
/* Romantic Encounters: Ribald RA2	*/
IF
	InParty(Myself)
	Global("RE_RibaldRomanceActive","GLOBAL",2)
	Global("c-arnRERibaldRA2","LOCALS",0)
	!AreaCheck("AR0702")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnRERibaldRA","LOCALS",9)
END
/* Romantic Encounters: Ryan Trawl	*/
IF
	InParty(Myself)
	Global("RE_RyanFlirt","GLOBAL",1)
	Global("c-arnRERyan","LOCALS",0)
	!AreaCheck("AR0903")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnRERyan","LOCALS",9)
END
/* Romantic Encounters: Saemon Havarian	*/
IF
	InParty(Myself)
	Global("RE_SaemonFlirt","GLOBAL",1)
	Global("c-arnRESaemon","LOCALS",0)
	!Global("Chapter","GLOBAL",%bg2_chapter_4%)
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnRESaemon","LOCALS",9)
END
/* Romantic Encounters: Solaufein	*/
IF
	InParty(Myself)
	Global("RE_SolaufeinFlirt","GLOBAL",1)
	Global("c-arnRESolaufein","LOCALS",0)
	!Global("Chapter","GLOBAL",%bg2_chapter_4%)
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnRESolaufein","LOCALS",9)
END
/* Romantic Encounters: Talak	*/
IF
	InParty(Myself)
	Global("RE_TalakFlirt","GLOBAL",1)
	Global("c-arnRETalak","LOCALS",0)
	!Global("Chapter","GLOBAL",%bg2_chapter_5%)
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnRETalak","LOCALS",9)
END
/* Romantic Encounters: Talak	*/
IF
	InParty(Myself)
	Global("RE_TeosFlirt","GLOBAL",1)
	Global("c-arnRETeos","LOCALS",0)
	!AreaCheck("AR0411")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnRETeos","LOCALS",9)
END
/* Romantic Encounters: Yoshimo	*/
IF
	InParty(Myself)
	Global("RE_YoshimoSex","GLOBAL",1)
	Global("c-arnREYoshimo","LOCALS",0)
	!AreaCheck("AR0021")		 // Crooked Crane, 1st floor
	!AreaCheck("AR0313")		 // Sea's Bounty, 1st floor
	!AreaCheck("AR0406")		 // Copper Coronet
	!AreaCheck("AR0509")		 // Five Flagons, 1st floor
	!AreaCheck("AR0513")		 // Delosar's, 1st floor
	!AreaCheck("AR0522")		 // Five Flagons, 1st floor (stronghold)
	!AreaCheck("AR0704")		 // Mithrest Inn
	!AreaCheck("AR0709")		 // Den of the Seven Vales
	!AreaCheck("AR1105")		 // Imnesvale Inn
	!AreaCheck("AR1602")		 // Vulgar Monkey
	!AreaCheck("AR2010")		 // Trademeet Inn
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnREYoshimo","LOCALS",9)
END
/* Romantic Encounters: Cernd	*/
IF
	InParty(Myself)
	Global("RE_CerndFlirt","GLOBAL",1)
	Global("c-arnRECernd","LOCALS",0)
	!AreaCheck("AR1900")
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arnRECernd","LOCALS",9)
END
/* BCS Blocks for Scroll Creation */
/* c-arSCRL15 Aran PID: Create Scroll of Protection from Petrification */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL15","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL15","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL15",Myself,1,1,1)
		DisplayStringHead(Myself,@13019)
	EndCutSceneMode()
END
/* c-arSCRL1B Aran PID: Create Scroll of Agannazar's Scorcher */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL1B","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL1B","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL1B",Myself,1,1,1)
		DisplayStringHead(Myself,@13020)
	EndCutSceneMode()
END
/* c-arSCRL1C Aran PID: Create Scroll of Ghoul Touch */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL1C","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL1C","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL1C",Myself,1,1,1)
		DisplayStringHead(Myself,@13021)
	EndCutSceneMode()
END
/* c-arSCRL1D Aran PID: Create Scroll of Clairvoyance */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL1D","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL1D","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL1D",Myself,1,1,1)
		DisplayStringHead(Myself,@13022)
	EndCutSceneMode()
END
/* c-arSCRL1E Aran PID: Create Scroll of Dispel Magic */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL1E","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL1E","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL1E",Myself,1,1,1)
		DisplayStringHead(Myself,@13023)
	EndCutSceneMode()
END
/* c-arSCRL1F Aran PID: Create Scroll of Flame Arrow */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL1F","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL1F","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL1F",Myself,1,1,1)
		DisplayStringHead(Myself,@13024)
	EndCutSceneMode()
END
/* c-arSCRL1G Aran PID: Create Scroll of Fireball */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL1G","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL1G","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL1G",Myself,1,1,1)
		DisplayStringHead(Myself,@13025)
	EndCutSceneMode()
END
/* c-arSCRL1H Aran PID: Create Scroll of Haste */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL1H","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL1H","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL1H",Myself,1,1,1)
		DisplayStringHead(Myself,@13026)
	EndCutSceneMode()
END
/* c-arSCRL1I Aran PID: Create Scroll of Hold Person */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL1I","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL1I","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL1I",Myself,1,1,1)
		DisplayStringHead(Myself,@13027)
	EndCutSceneMode()
END
/* c-arSCRL1J Aran PID: Create Scroll of Invisibility 10' radius */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL1J","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL1J","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL1J",Myself,1,1,1)
		DisplayStringHead(Myself,@13028)
	EndCutSceneMode()
END
/* c-arSCRL1K Aran PID: Create Scroll of Lightning Bolt */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL1K","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL1K","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL1K",Myself,1,1,1)
		DisplayStringHead(Myself,@13029)
	EndCutSceneMode()
END
/* c-arSCRL1M Aran PID: Create Scroll of NonDetection */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL1M","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL1M","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL1M",Myself,1,1,1)
		DisplayStringHead(Myself,@13030)
	EndCutSceneMode()
END
/* c-arSCRL1N Aran PID: Create Scroll of Protection from Normal Missiles */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL1N","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL1N","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL1N",Myself,1,1,1)
		DisplayStringHead(Myself,@13031)
	EndCutSceneMode()
END
/* c-arSCRL1O Aran PID: Create Scroll of Slow */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL1O","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL1O","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL1O",Myself,1,1,1)
		DisplayStringHead(Myself,@13032)
	EndCutSceneMode()
END
/* c-arSCRL1P Aran PID: Create Scroll of Skull Trap */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL1P","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL1P","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL1P",Myself,1,1,1)
		DisplayStringHead(Myself,@13033)
	EndCutSceneMode()
END
/* c-arSCRL1Q Aran PID: Create Scroll of Vampiric Touch */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL1Q","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL1Q","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL1Q",Myself,1,1,1)
		DisplayStringHead(Myself,@13034)
	EndCutSceneMode()
END
/* c-arSCRL1S Aran PID: Create Scroll of Dire Charm */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL1S","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL1S","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL1S",Myself,1,1,1)
		DisplayStringHead(Myself,@13035)
	EndCutSceneMode()
END
/* c-arSCRL1T Aran PID: Create Scroll of Ghost Armor */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL1T","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL1T","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL1T",Myself,1,1,1)
		DisplayStringHead(Myself,@13036)
	EndCutSceneMode()
END
/* c-arSCRL1U Aran PID: Create Scroll of Confusion */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL1U","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL1U","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL1U",Myself,1,1,1)
		DisplayStringHead(Myself,@13037)
	EndCutSceneMode()
END
/* c-arSCRL1V Aran PID: Create Scroll of Stoneskin */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL1V","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL1V","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL1V",Myself,1,1,1)
		DisplayStringHead(Myself,@13038)
	EndCutSceneMode()
END
/* c-arSCRL1W Aran PID: Create Scroll of Fireshield (Blue) */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL1W","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL1W","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL1W",Myself,1,1,1)
		DisplayStringHead(Myself,@13039)
	EndCutSceneMode()
END
/* c-arSCRL1X Aran PID: Create Scroll of Ice Storm */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL1X","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL1X","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL1X",Myself,1,1,1)
		DisplayStringHead(Myself,@13040)
	EndCutSceneMode()
END
/* c-arSCRL1Y Aran PID: Create Scroll of Improved Invisibility */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL1Y","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL1Y","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL1Y",Myself,1,1,1)
		DisplayStringHead(Myself,@13041)
	EndCutSceneMode()
END
/* c-arSCRL1Z Aran PID: Create Scroll of Minor Globe of Invulnerability */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL1Z","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL1Z","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL1Z",Myself,1,1,1)
		DisplayStringHead(Myself,@13042)
	EndCutSceneMode()
END
/* c-arSCRL2E Aran PID: Create Scroll of Cloudkill */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL2E","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL2E","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL2E",Myself,1,1,1)
		DisplayStringHead(Myself,@13043)
	EndCutSceneMode()
END
/* c-arSCRL2F Aran PID: Create Scroll of Cone of Cold */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL2F","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL2F","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL2F",Myself,1,1,1)
		DisplayStringHead(Myself,@13044)
	EndCutSceneMode()
END
/* c-arSCRL2H Aran PID: Create Scroll of Shadow Door */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL2H","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL2H","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL2H",Myself,1,1,1)
		DisplayStringHead(Myself,@13045)
	EndCutSceneMode()
END
/* c-arSCRL3G Aran PID: Create Scroll of Vocalize */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL3G","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL3G","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL3G",Myself,1,1,1)
		DisplayStringHead(Myself,@13046)
	EndCutSceneMode()
END
/* c-arSCRL5G Aran PID: Create Scroll of Remove Curse */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL5G","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL5G","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL5G",Myself,1,1,1)
		DisplayStringHead(Myself,@13047)
	EndCutSceneMode()
END
/* c-arSCRL5H Aran PID: Create Scroll of Emotion */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL5H","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL5H","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL5H",Myself,1,1,1)
		DisplayStringHead(Myself,@13048)
	EndCutSceneMode()
END
/* c-arSCRL5I Aran PID: Create Scroll of Greater Malison */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL5I","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL5I","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL5I",Myself,1,1,1)
		DisplayStringHead(Myself,@13049)
	EndCutSceneMode()
END
/* c-arSCRL5J Aran PID: Create Scroll of Otiluke's Resilient Sphere */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL5J","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL5J","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL5J",Myself,1,1,1)
		DisplayStringHead(Myself,@13050)
	EndCutSceneMode()
END
/* c-arSCRL5K Aran PID: Create Scroll of Spirit Armor */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL5K","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL5K","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL5K",Myself,1,1,1)
		DisplayStringHead(Myself,@13051)
	EndCutSceneMode()
END
/* c-arSCRL5N Aran PID: Create Scroll of Domination */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL5N","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL5N","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL5N",Myself,1,1,1)
		DisplayStringHead(Myself,@13052)
	EndCutSceneMode()
END

/* c-arSCRL5P Aran PID: Create Scroll of Chaos */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL5P","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL5P","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL5P",Myself,1,1,1)
		DisplayStringHead(Myself,@13053)
	EndCutSceneMode()
END
/* c-arSCRL5Q Aran PID: Create Scroll of Feeblemind */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL5Q","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL5Q","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL5Q",Myself,1,1,1)
		DisplayStringHead(Myself,@13054)
	EndCutSceneMode()
END
/* c-arSCRL5T Aran PID: Create Scroll of Protection from Electricity */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL5T","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL5T","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL5T",Myself,1,1,1)
		DisplayStringHead(Myself,@13055)
	EndCutSceneMode()
END
/* c-arSCRL5U Aran PID: Create Scroll of Reflected Image */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL5U","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL5U","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL5U",Myself,1,1,1)
		DisplayStringHead(Myself,@13056)
	EndCutSceneMode()
END
/* c-arSCRL66 Aran PID: Create Scroll of Grease */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL66","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL66","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL66",Myself,1,1,1)
		DisplayStringHead(Myself,@13057)
	EndCutSceneMode()
END
/* c-arSCRL67 Aran PID: Create Scroll of Armor */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL67","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL67","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL67",Myself,1,1,1)
		DisplayStringHead(Myself,@13058)
	EndCutSceneMode()
END
/* c-arSCRL68 Aran PID: Create Scroll of Burning Hands */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL68","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL68","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL68",Myself,1,1,1)
		DisplayStringHead(Myself,@13059)
	EndCutSceneMode()
END
/* c-arSCRL69 Aran PID: Create Scroll of Charm Person */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL69","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL69","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL69",Myself,1,1,1)
		DisplayStringHead(Myself,@13060)
	EndCutSceneMode()
END
/* c-arSCRL6D Aran PID: Create Scroll of Find Familiar */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL6D","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL6D","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL6D",Myself,1,1,1)
		DisplayStringHead(Myself,@13061)
	EndCutSceneMode()
END
/* c-arSCRL6E Aran PID: Create Scroll of Power Word, Sleep */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL6E","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL6E","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL6E",Myself,1,1,1)
		DisplayStringHead(Myself,@13062)
	EndCutSceneMode()
END
/* c-arSCRL6F Aran PID: Create Scroll of Ray of Enfeeblement */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL6F","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL6F","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL6F",Myself,1,1,1)
		DisplayStringHead(Myself,@13063)
	EndCutSceneMode()
END
/* c-arSCRL6G Aran PID: Create Scroll of Minor Spell Deflection */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL6G","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL6G","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL6G",Myself,1,1,1)
		DisplayStringHead(Myself,@13064)
	EndCutSceneMode()
END
/* c-arSCRL6H Aran PID: Create Scroll of Protection from Fire */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL6H","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL6H","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL6H",Myself,1,1,1)
		DisplayStringHead(Myself,@13065)
	EndCutSceneMode()
END
/* c-arSCRL6I Aran PID: Create Scroll of Protection from Cold */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL6I","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL6I","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL6I",Myself,1,1,1)
		DisplayStringHead(Myself,@13066)
	EndCutSceneMode()
END
/* c-arSCRL6J Aran PID: Create Scroll of Spell Thrust */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL6J","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL6J","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL6J",Myself,1,1,1)
		DisplayStringHead(Myself,@13067)
	EndCutSceneMode()
END
/* c-arSCRL6K Aran PID: Create Scroll of Detect Illusion */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL6K","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL6K","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL6K",Myself,1,1,1)
		DisplayStringHead(Myself,@13068)
	EndCutSceneMode()
END
/* c-arSCRL6L Aran PID: Create Scroll of Hold Undead */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL6L","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL6L","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL6L",Myself,1,1,1)
		DisplayStringHead(Myself,@13069)
	EndCutSceneMode()
END
/* c-arSCRL6M Aran PID: Create Scroll of Enchanted Weapon */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL6M","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL6M","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL6M",Myself,1,1,1)
		DisplayStringHead(Myself,@13070)
	EndCutSceneMode()
END
/* c-arSCRL6N Aran PID: Create Scroll of Fireshield (Red) */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL6N","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL6N","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL6N",Myself,1,1,1)
		DisplayStringHead(Myself,@13071)
	EndCutSceneMode()
END
/* c-arSCRL6O Aran PID: Create Scroll of Secret Word */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL6O","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL6O","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL6O",Myself,1,1,1)
		DisplayStringHead(Myself,@13072)
	EndCutSceneMode()
END
/* c-arSCRL6P Aran PID: Create Scroll of Minor Sequencer */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL6P","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL6P","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL6P",Myself,1,1,1)
		DisplayStringHead(Myself,@13073)
	EndCutSceneMode()
END
/* c-arSCRL6S Aran PID: Create Scroll of Spell Immunity */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL6S","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL6S","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL6S",Myself,1,1,1)
		DisplayStringHead(Myself,@13074)
	EndCutSceneMode()
END
/* c-arSCRL6T Aran PID: Create Scroll of Protection from Normal Weapons */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL6T","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL6T","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL6T",Myself,1,1,1)
		DisplayStringHead(Myself,@13075)
	EndCutSceneMode()
END
/* c-arSCRL6U Aran PID: Create Scroll of Breach */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL6U","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL6U","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL6U",Myself,1,1,1)
		DisplayStringHead(Myself,@13076)
	EndCutSceneMode()
END
/* c-arSCRL6V Aran PID: Create Scroll of Lower Resistance */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL6V","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL6V","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL6V",Myself,1,1,1)
		DisplayStringHead(Myself,@13077)
	EndCutSceneMode()
END
/* c-arSCRL6W Aran PID: Create Scroll of Oracle */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL6W","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL6W","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL6W",Myself,1,1,1)
		DisplayStringHead(Myself,@13078)
	EndCutSceneMode()
END
/* c-arSCRL6Y Aran PID: Create Scroll of Protection from Acid */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL6Y","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL6Y","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL6Y",Myself,1,1,1)
		DisplayStringHead(Myself,@13079)
	EndCutSceneMode()
END
/* c-arSCRL6Z Aran PID: Create Scroll of Phantom Blade */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL6Z","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL6Z","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL6Z",Myself,1,1,1)
		DisplayStringHead(Myself,@13080)
	EndCutSceneMode()
END
/* c-arSCRL70 Aran PID: Create Scroll of Color Spray */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL70","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL70","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL70",Myself,1,1,1)
		DisplayStringHead(Myself,@13081)
	EndCutSceneMode()
END
/* c-arSCRL71 Aran PID: Create Scroll of Blindness */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL71","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL71","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL71",Myself,1,1,1)
		DisplayStringHead(Myself,@13082)
	EndCutSceneMode()
END
/* c-arSCRL72 Aran PID: Create Scroll of Friends */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL72","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL72","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL72",Myself,1,1,1)
		DisplayStringHead(Myself,@13083)
	EndCutSceneMode()
END
/* c-arSCRL75 Aran PID: Create Scroll of Identify */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL75","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL75","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL75",Myself,1,1,1)
		DisplayStringHead(Myself,@13084)
	EndCutSceneMode()
END
/* c-arSCRL76 Aran PID: Create Scroll of Infravision */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL76","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL76","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL76",Myself,1,1,1)
		DisplayStringHead(Myself,@13085)
	EndCutSceneMode()
END
/* c-arSCRL77 Aran PID: Create Scroll of Magic Missile */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL77","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL77","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL77",Myself,1,1,1)
		DisplayStringHead(Myself,@13086)
	EndCutSceneMode()
END
/* c-arSCRL78 Aran PID: Create Scroll of Protection from Evil */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL78","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL78","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL78",Myself,1,1,1)
		DisplayStringHead(Myself,@13087)
	EndCutSceneMode()
END
/* c-arSCRL79 Aran PID: Create Scroll of Shield */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL79","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL79","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL79",Myself,1,1,1)
		DisplayStringHead(Myself,@13088)
	EndCutSceneMode()
END
/* c-arSCRL7D Aran PID: Create Scroll of Minor Spell Turning */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL7D","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL7D","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL7D",Myself,1,1,1)
		DisplayStringHead(Myself,@13089)
	EndCutSceneMode()
END
/* c-arSCRL7F Aran PID: Create Scroll of Globe of Invulnerability */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL7F","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL7F","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL7F",Myself,1,1,1)
		DisplayStringHead(Myself,@13090)
	EndCutSceneMode()
END
/* c-arSCRL7G Aran PID: Create Scroll of Tenser's Transformation */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL7G","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL7G","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL7G",Myself,1,1,1)
		DisplayStringHead(Myself,@13091)
	EndCutSceneMode()
END
/* c-arSCRL7H Aran PID: Create Scroll of Flesh to Stone */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL7H","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL7H","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL7H",Myself,1,1,1)
		DisplayStringHead(Myself,@13092)
	EndCutSceneMode()
END
/* c-arSCRL7I Aran PID: Create Scroll of Death Spell */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL7I","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL7I","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL7I",Myself,1,1,1)
		DisplayStringHead(Myself,@13093)
	EndCutSceneMode()
END
/* c-arSCRL7J Aran PID: Create Scroll of Protection from Magic */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL7J","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL7J","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL7J",Myself,1,1,1)
		DisplayStringHead(Myself,@13094)
	EndCutSceneMode()
END
/* c-arSCRL7K Aran PID: Create Scroll of Mislead */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL7K","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL7K","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL7K",Myself,1,1,1)
		DisplayStringHead(Myself,@13095)
	EndCutSceneMode()
END
/* c-arSCRL7L Aran PID: Create Scroll of Pierce Magic */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL7L","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL7L","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL7L",Myself,1,1,1)
		DisplayStringHead(Myself,@13096)
	EndCutSceneMode()
END
/* c-arSCRL7M Aran PID: Create Scroll of True Sight */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL7M","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL7M","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL7M",Myself,1,1,1)
		DisplayStringHead(Myself,@13097)
	EndCutSceneMode()
END
/* c-arSCRL7O Aran PID: Create Scroll of Protection from Magical Weapons */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL7O","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL7O","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL7O",Myself,1,1,1)
		DisplayStringHead(Myself,@13098)
	EndCutSceneMode()
END
/* c-arSCRL7P Aran PID: Create Scroll of Power Word, Silence */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL7P","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL7P","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL7P",Myself,1,1,1)
		DisplayStringHead(Myself,@13099)
	EndCutSceneMode()
END
/* c-arSCRL7Q Aran PID: Create Scroll of Improved Haste */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL7Q","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL7Q","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL7Q",Myself,1,1,1)
		DisplayStringHead(Myself,@13100)
	EndCutSceneMode()
END
/* c-arSCRL7R Aran PID: Create Scroll of Death Fog */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL7R","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL7R","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL7R",Myself,1,1,1)
		DisplayStringHead(Myself,@13101)
	EndCutSceneMode()
END
/* c-arSCRL7S Aran PID: Create Scroll of Chain Lightning */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL7S","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL7S","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL7S",Myself,1,1,1)
		DisplayStringHead(Myself,@13102)
	EndCutSceneMode()
END
/* c-arSCRL7T Aran PID: Create Scroll of Disintegrate */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL7T","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL7T","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL7T",Myself,1,1,1)
		DisplayStringHead(Myself,@13103)
	EndCutSceneMode()
END
/* c-arSCRL7U Aran PID: Create Scroll of Contingency */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL7U","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL7U","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL7U",Myself,1,1,1)
		DisplayStringHead(Myself,@13104)
	EndCutSceneMode()
END
/* c-arSCRL7V Aran PID: Create Scroll of Spell Deflection */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL7V","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL7V","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL7V",Myself,1,1,1)
		DisplayStringHead(Myself,@13105)
	EndCutSceneMode()
END
/* c-arSCRL80 Aran PID: Create Scroll of Shocking Grasp */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL80","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL80","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL80",Myself,1,1,1)
		DisplayStringHead(Myself,@13106)
	EndCutSceneMode()
END
/* c-arSCRL81 Aran PID: Create Scroll of Sleep */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL81","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL81","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL81",Myself,1,1,1)
		DisplayStringHead(Myself,@13107)
	EndCutSceneMode()
END
/* c-arSCRL82 Aran PID: Create Scroll of Chill Touch */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL82","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL82","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL82",Myself,1,1,1)
		DisplayStringHead(Myself,@13108)
	EndCutSceneMode()
END
/* c-arSCRL83 Aran PID: Create Scroll of Chromatic Orb */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL83","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL83","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL83",Myself,1,1,1)
		DisplayStringHead(Myself,@13109)
	EndCutSceneMode()
END
/* c-arSCRL84 Aran PID: Create Scroll of Larloch's Minor Drain */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL84","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL84","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL84",Myself,1,1,1)
		DisplayStringHead(Myself,@13110)
	EndCutSceneMode()
END
/* c-arSCRL85 Aran PID: Create Scroll of Blur */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL85","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL85","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL85",Myself,1,1,1)
		DisplayStringHead(Myself,@13111)
	EndCutSceneMode()
END
/* c-arSCRL86 Aran PID: Create Scroll of Detect Evil */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL86","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL86","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL86",Myself,1,1,1)
		DisplayStringHead(Myself,@13112)
	EndCutSceneMode()
END
/* c-arSCRL87 Aran PID: Create Scroll of Detect Invisibility */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL87","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL87","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL87",Myself,1,1,1)
		DisplayStringHead(Myself,@13113)
	EndCutSceneMode()
END
/* c-arSCRL89 Aran PID: Create Scroll of Horror */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL89","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL89","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL89",Myself,1,1,1)
		DisplayStringHead(Myself,@13114)
	EndCutSceneMode()
END
/* c-arSCRL8C Aran PID: Create Scroll of Stone to Flesh */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL8C","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL8C","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL8C",Myself,1,1,1)
		DisplayStringHead(Myself,@13115)
	EndCutSceneMode()
END
/* c-arSCRL8X Aran PID: Create Scroll of Spell Shield */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL8X","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL8X","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL8X",Myself,1,1,1)
		DisplayStringHead(Myself,@13116)
	EndCutSceneMode()
END
/* c-arSCRL90 Aran PID: Create Scroll of Invisibility */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL90","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL90","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL90",Myself,1,1,1)
		DisplayStringHead(Myself,@13117)
	EndCutSceneMode()
END
/* c-arSCRL91 Aran PID: Create Scroll of Knock */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL91","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL91","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL91",Myself,1,1,1)
		DisplayStringHead(Myself,@13118)
	EndCutSceneMode()
END
/* c-arSCRL92 Aran PID: Create Scroll of Know Alignment */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL92","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL92","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL92",Myself,1,1,1)
		DisplayStringHead(Myself,@13119)
	EndCutSceneMode()
END
/* c-arSCRL93 Aran PID: Create Scroll of Luck */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL93","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL93","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL93",Myself,1,1,1)
		DisplayStringHead(Myself,@13120)
	EndCutSceneMode()
END
/* c-arSCRL94 Aran PID: Create Scroll of Resist Fear */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL94","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL94","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL94",Myself,1,1,1)
		DisplayStringHead(Myself,@13121)
	EndCutSceneMode()
END
/* c-arSCRL95 Aran PID: Create Scroll of Melf's Acid Arrow */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL95","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL95","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL95",Myself,1,1,1)
		DisplayStringHead(Myself,@13122)
	EndCutSceneMode()
END
/* c-arSCRL96 Aran PID: Create Scroll of Mirror Image */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL96","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL96","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL96",Myself,1,1,1)
		DisplayStringHead(Myself,@13123)
	EndCutSceneMode()
END

/* c-arSCRL97 Aran PID: Create Scroll of Stinking Cloud */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL97","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL97","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL97",Myself,1,1,1)
		DisplayStringHead(Myself,@13124)
	EndCutSceneMode()
END
/* c-arSCRL98 Aran PID: Create Scroll of Strength */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL98","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL98","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL98",Myself,1,1,1)
		DisplayStringHead(Myself,@13125)
	EndCutSceneMode()
END
/* c-arSCRL99 Aran PID: Create Scroll of Web */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRL99","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRL99","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRL99",Myself,1,1,1)
		DisplayStringHead(Myself,@13126)
	EndCutSceneMode()
END
/* c-arSCRLA1 Aran PID: Create Scroll of Wizard Eye */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRLA1","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRLA1","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRLA1",Myself,1,1,1)
		DisplayStringHead(Myself,@13127)
	EndCutSceneMode()
END
/* c-arSCRLA2 Aran PID: Create Scroll of Deafness */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRLA2","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRLA2","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRLA2",Myself,1,1,1)
		DisplayStringHead(Myself,@13128)
	EndCutSceneMode()
END
/* c-arSCRLA3 Aran PID: Create Scroll of Glitterdust */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRLA3","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRLA3","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRLA3",Myself,1,1,1)
		DisplayStringHead(Myself,@13129)
	EndCutSceneMode()
END
/* c-arSCRLA5 Aran PID: Create Scroll of Melf's Minute Meteors */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRLA5","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRLA5","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRLA5",Myself,1,1,1)
		DisplayStringHead(Myself,@13130)
	EndCutSceneMode()
END
/* c-arSCRLA6 Aran PID: Create Scroll of Spook */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRLA6","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRLA6","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRLA6",Myself,1,1,1)
		DisplayStringHead(Myself,@13131)
	EndCutSceneMode()
END
/* c-arSCRLA8 Aran PID: Create Scroll of Contagion */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRLA8","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRLA8","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRLA8",Myself,1,1,1)
		DisplayStringHead(Myself,@13132)
	EndCutSceneMode()
END
/* c-arSCRLAJ Aran PID: Create Scroll of Farsight */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRLAJ","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRLAJ","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRLAJ",Myself,1,1,1)
		DisplayStringHead(Myself,@13133)
	EndCutSceneMode()
END
/* c-arSCRLAL Aran PID: Create Scroll of Sunfire */
IF
	GlobalTimerExpired("c-aranscribing","GLOBAL")
	Global("c-aranscribe","GLOBAL",1)
	Global("c-arSCRLAL","LOCALS",1)
	InParty(Myself)
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	StartCutSceneMode()
		SetGlobal("c-arSCRLAL","LOCALS",0)
		SetGlobal("c-aranscribe","GLOBAL",0)
		GiveItemCreate("SCRLAL",Myself,1,1,1)
		DisplayStringHead(Myself,@13134)
	EndCutSceneMode()
END

/* Player Stronghold Reactions */

/* Gaining Stronghold Responses : set from .bcs */
/* 1 possible if played without mods, 2 or 3 for multiclass PC's with mods, all of them if one of the multi-stronghold tweaks are installed */

/* Easter Egg for Multi-stronghold folks who get all strongholds at once */
IF
	Global("c-aranas","LOCALS",0)
	GlobalGT("JoinLathander","GLOBAL",0) 
	GlobalGT("JoinTalos","GLOBAL",0) 
	GlobalGT("JoinHelm","GLOBAL",0) 
	GlobalGT("PaladinOrder","GLOBAL",0) 
	GlobalGT("Playhouse","GLOBAL",0) 
	GlobalGT("PCKeepOwner","GLOBAL",0) 
	GlobalGT("PlayerThiefGuild","GLOBAL",0) 
	GlobalGT("DruidStrongHold","GLOBAL",0) 
	GlobalGT("PCSphere","GLOBAL",0) 
	GlobalGT("RangerProtector","GLOBAL",0)	 
THEN
	RESPONSE #100
		SetGlobal("c-aranas","LOCALS",1)
		RealSetGlobalTimer("c-aranstrong","GLOBAL",20)
END
/* Got All Strongholds : Initiate */
IF
	RealGlobalTimerExpired("c-aranstrong","GLOBAL")
	Global("c-aranas","LOCALS",1)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	!See([ENEMY])
	!ActuallyInCombat()
THEN
	RESPONSE #100
		PlaySong(0)
		PlaySound("c-arnfth")
		StartDialogueNoSet(Player1)
END
/* Bards : Activate */
IF
	Global("Playhouse","GLOBAL",1)
	Global("c-aranbs","LOCALS",0)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	!See([ENEMY])
	!ActuallyInCombat()
THEN
	RESPONSE #100
		SetGlobal("c-aranbs","LOCALS",1)
		RealSetGlobalTimer("c-aranstrong","GLOBAL",20)
END

/* Bards : Initiate */
IF
	Global("c-aranbs","LOCALS",1)
	RealGlobalTimerExpired("c-aranstrong","GLOBAL")
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	!See([ENEMY])
	!ActuallyInCombat()
THEN
	RESPONSE #100
		PlaySong(0)
		PlaySound("c-arnfth")
		StartDialogueNoSet(Player1)
END
/* Clerics : Activate */
IF
	Global("c-arancs","LOCALS",0)
	OR(3)
		Global("JoinLathander","GLOBAL",1)
		Global("JoinTalos","GLOBAL",1)
		Global("JoinHelm","GLOBAL",1)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	!ActuallyInCombat()
	!See([ENEMY])
THEN
	RESPONSE #100
		SetGlobal("c-arancs","LOCALS",1)
		RealSetGlobalTimer("c-aranstrong","GLOBAL",20)
END
/* Clerics : Initiate */
IF
	Global("c-arancs","LOCALS",1)
	RealGlobalTimerExpired("c-aranstrong","GLOBAL")
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	!See([ENEMY])
	!ActuallyInCombat()
THEN
	RESPONSE #100
		PlaySong(0)
		PlaySound("c-arnfth")
		StartDialogueNoSet(Player1)
END
/* Druids : Activate */
IF
	Global("DruidStronghold","GLOBAL",1)
	Global("c-arands","LOCALS",0)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	!ActuallyInCombat()
	!See([ENEMY])
THEN 
	RESPONSE #100
		SetGlobal("c-arands","LOCALS",1)
		RealSetGlobalTimer("c-aranstrong","GLOBAL",20)
END
/* Druids : Activate */
IF
	Global("c-arands","LOCALS",1)
	RealGlobalTimerExpired("c-aranstrong","GLOBAL")
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	!See([ENEMY])
	!ActuallyInCombat()
THEN
	RESPONSE #100
		PlaySong(0)
		PlaySound("c-arnfth")
		StartDialogueNoSet(Player1)
END
/* Fighters : Activate */
IF
	Global("PCKeepOwner","GLOBAL",1)
	Global("c-aranfs","LOCALS",0)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	!ActuallyInCombat()
	!See([ENEMY])
THEN
	RESPONSE #100
		SetGlobal("c-aranfs","LOCALS",1)
		SetGlobalTimer("c-aranhometalk","GLOBAL",FIVE_DAYS)
		RealSetGlobalTimer("c-aranstrong","GLOBAL",20)
END

/* Fighters : Initiate */
IF
	Global("c-aranfs","LOCALS",1)
	RealGlobalTimerExpired("c-aranstrong","GLOBAL")
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	!See([ENEMY])
	!ActuallyInCombat()
THEN
	RESPONSE #100
		PlaySong(0)
		PlaySound("c-arnfth")
		StartDialogueNoSet(Player1)
END

/* Stronghold Commentary */

/* SoA Stronghold Commentary : PC Owns Keep */
IF
	Global("PCKeepOwner","GLOBAL",1)
	Global("c-silencearan","GLOBAL",0) // PID - set silencer
	Global("c-aranpckeep","LOCALS",0)
	GlobalTimerExpired("c-aranhometalk","GLOBAL")
	!AreaCheck("AR1305")
	!AreaCheck("AR1306")
	!AreaCheck("AR1307")
	!AreaCheck("AR0021")		 // Crooked Crane, 1st floor
	!AreaCheck("AR0313")		 // Sea's Bounty, 1st floor
	!AreaCheck("AR0406")		 // Copper Coronet
	!AreaCheck("AR0509")		 // Five Flagons, 1st floor
	!AreaCheck("AR0513")		 // Delosar's, 1st floor
	!AreaCheck("AR0522")		 // Five Flagons, 1st floor (stronghold)
	!AreaCheck("AR0704")		 // Mithrest Inn
	!AreaCheck("AR0709")		 // Den of the Seven Vales
	!AreaCheck("AR1105")		 // Imnesvale Inn
	!AreaCheck("AR1602")		 // Vulgar Monkey
	!AreaCheck("AR2010")		 // Trademeet Inn
	!AreaCheck("C-AR01")		 // The Broken Sword	
	Global("c-silencearan","GLOBAL",0) // PID - set silencer
	Global("c-aranpckeep","LOCALS",0)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	CombatCounter(0)
	!See([ENEMY])
THEN
	RESPONSE #100
		SetGlobal("c-aranpckeep","LOCALS",1)
		StartDialogueNoSet(Player1)
END

/* Mages : Activate */
IF
	GlobalGT("GettingApprentices","GLOBAL",0)
	Global("c-aranms","LOCALS",0)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	!ActuallyInCombat()
	!See([ENEMY])
THEN
	RESPONSE #100
		SetGlobal("c-aranms","LOCALS",1)
		RealSetGlobalTimer("c-aranstrong","GLOBAL",20)
END

/* Mages : Initiate */
IF
	Global("c-aranms","LOCALS",1)
	RealGlobalTimerExpired("c-aranstrong","GLOBAL")
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	!See([ENEMY])
	!ActuallyInCombat()
THEN
	RESPONSE #100
		PlaySong(0)
		PlaySound("c-arnfth")
		StartDialogueNoSet(Player1)
END

/* Paladins : Activate */
IF
	Global("PaladinOrder","GLOBAL",1)
	Global("c-aranps","LOCALS",0)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	!ActuallyInCombat()
	!See([ENEMY])
THEN
	RESPONSE #100
		SetGlobal("c-aranps","LOCALS",1)
		RealSetGlobalTimer("c-aranstrong","GLOBAL",20)
END

/* Paladins : Initiate */
IF
	Global("c-aranps","LOCALS",1)
	RealGlobalTimerExpired("c-aranstrong","GLOBAL")
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	!See([ENEMY])
	!ActuallyInCombat()
THEN
	RESPONSE #100
	PlaySong(0)
	PlaySound("c-arnfth")
	StartDialogueNoSet(Player1)
END

/* Rangers : Activate */
IF
	Global("RangerProtector","GLOBAL",1)
	Global("c-aranrs","LOCALS",0)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	!ActuallyInCombat()
	!See([ENEMY])
THEN
	RESPONSE #100
		SetGlobal("c-aranrs","LOCALS",1)
		RealSetGlobalTimer("c-aranstrong","GLOBAL",20)
END

/* Rangers : Initiate */
IF
	Global("c-aranrs","LOCALS",1)
	RealGlobalTimerExpired("c-aranstrong","GLOBAL")
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	!See([ENEMY])
	!ActuallyInCombat()
THEN
	RESPONSE #100
	PlaySong(0)
	PlaySound("c-arnfth")
	StartDialogueNoSet(Player1)
END

/* Harpers are Not Always Good For Business : Activate */
/* LUSETTE 11 ~Begone, and hopefully your next dealings with the Harpers will be more pleasant.~ */
IF
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  !See([ENEMY])
  !ActuallyInCombat()
  Global("LyrosJob","GLOBAL",3)
  Global("c-aranlyrosjob","LOCALS",0)
THEN 
	RESPONSE #100
		SetGlobal("c-aranlyrosjob","LOCALS",1)
END
/* Harpers are Not Always Good For Business : Initiate */
IF
  Global("c-aranlyrosjob","LOCALS",1)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  !See([ENEMY])
  !ActuallyInCombat()
THEN 
	RESPONSE #100
		StartDialogNoSet(Player1)
END

/* Saerileth Commentary SoA : Are you sure about this romance? : Activate */
IF
  InParty("Saerileth")
  InMyArea("Saerileth")
  !StateCheck("Saerileth",CD_STATE_NOTVALID)
  InParty(Myself)
  !StateCheck(Myself,CD_STATE_NOTVALID)
  CombatCounter(0)
  Global("SaerilethRomanceActive","GLOBAL",2)
  Global("c-aranpcsaerrom","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("c-aranpcsaerrom","GLOBAL",1)
END

/* Saerileth Commentary SoA : Are you sure about this romance? : Initiate */
IF
	GlobalTimerExpired("c-aransmalltalk","GLOBAL") // Timer (game-time) has expired
	Global("c-silencearan","GLOBAL",0)	// a PID - set "silencer" for folks who hate unsolicited comments
	Global("c-aranpcsaerrom","GLOBAL",1)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		StartDialogNoSet(Player1)
END

/* SoA Scenery: Acknowledging Sheri from Romantic Encounters */
/* OK, look for Sheri D'Avignon at the Mithrest Inn... */
IF
    InParty(Myself)
    !StateCheck(Myself,CD_STATE_NOTVALID)
    AreaCheck("AR0704")
    Global("c-aranRE_Sheri","GLOBAL",0)
THEN
    RESPONSE #100
        SetGlobal("c-aranRE_Sheri","GLOBAL",1)
END
/* trigger the comment (Dialog handles Exists("RE_Sheri) | Exists("RE_Sheri) */
IF
	!See([ENEMY])
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	InMyArea(Player1)
	!StateCheck(Player1,CD_STATE_NOTVALID) 
    AreaCheck("AR0704")
    Global("c-aranRE_Sheri","GLOBAL",1)
THEN
    RESPONSE #100
		StartDialogueNoSet(Player1)
END
/* Rollback if player moves out of AR0704 before it triggers or other things happen to delay this */
IF
    InParty(Myself)
    !StateCheck(Myself,CD_STATE_NOTVALID)
    !AreaCheck("AR0704")
    Global("c-aranRE_SheriTalk","GLOBAL",1)
THEN
    RESPONSE #100
        SetGlobal("c-aranRE_SheriTalk","GLOBAL",0)
END

/* FRIEND TALKS
 * OK let's start with the Friend Talks. The idea here is to set the friendtalks up on a BCS <> DLG "bounce", so
 * 1. set the talk variable to 1 and set a timer.
 * 2. set a block that sees that the timer has expired, and initiates dialog.
 * 3. the game looks for the variable (1), and sees the dialog, and fires it.
 * 4. The dialog line advances the variable to (2), and sets a new timer.
 * 5. The BCS here looks for the timer to expire and the even variable (2), advancing to (3) when the timer expires
 * Then when it sees the conditions are right, repeat sequence from 3.
*/

/* Friend Talks Sequence */

/* Friend Talks Setup	*/
IF
	Global("c-aranfriendsetup","GLOBAL",0)	 // Not evaluated true yet
	InParty(Myself)						// Aran is here
	!StateCheck(Myself,CD_STATE_NOTVALID)	// Aran is ok
THEN
	RESPONSE #100								// 100% of the time
		SetGlobalTimer("c-aransmalltalk","GLOBAL",60)
		SetGlobalTimer("c-aranblush","GLOBAL",TEN_DAYS) // set up delay for embarrassment banters 
		SetGlobalTimer("c-aranisdrunk","GLOBAL",10)  // initializes drunk talk timer
		SetGlobal("c-aranfriendsetup","GLOBAL",1)
		RealSetGlobalTimer("c-aranfriendtimer","GLOBAL",180)	// Minimum Real Time until SoA_FT_1 is called, unlless the player initiates PID and triggers it 
		RealSetGlobalTimer("c-aranstrong","GLOBAL",180) // tee up stronghold spacer timer 
END

/* Aran's FriendTalks Aim, c-aranfriendbg2, %ARAN_FTT% : available any time */
/* This block takes the even variables set in dialog, and advances them to the odd */
IF
	GlobalLT("c-aranfriendbg2","GLOBAL",38)	// shuts down sequence when finished
	RealGlobalTimerExpired("c-aranfriendtimer","GLOBAL")	// Timer Expired
	!Global("Chapter","GLOBAL",%bg2_chapter_5%) // Not in Underdark - specialized talks for that
	OR(14)
		Global("c-aranfriendbg2","GLOBAL",0)	// set up SoA_FT_1
		Global("c-aranfriendbg2","GLOBAL",2)	// set up SoA_FT_2
		Global("c-aranfriendbg2","GLOBAL",4)	// set up SoA_FT_3
		Global("c-aranfriendbg2","GLOBAL",6)	// set up SoA_FT_4
		Global("c-aranfriendbg2","GLOBAL",8)	// set up SoA_FT_5
		Global("c-aranfriendbg2","GLOBAL",10) 	// set up SoA_FT_6
		Global("c-aranfriendbg2","GLOBAL",12) 	// set up SoA_FT_7
		Global("c-aranfriendbg2","GLOBAL",14) 	// set up SoA_FT_8
		Global("c-aranfriendbg2","GLOBAL",16) 	// set up SoA_FT_9
		Global("c-aranfriendbg2","GLOBAL",18) 	// set up SoA_FT_10
		Global("c-aranfriendbg2","GLOBAL",20) 	// set up SoA_FT_11
		Global("c-aranfriendbg2","GLOBAL",22) 	// set up SoA_FT_12	
		Global("c-aranfriendbg2","GLOBAL",24)   // set up SoA_FT_13
		Global("c-aranfriendbg2","GLOBAL",26)   // set up SoA_FT_14		
THEN
	RESPONSE #100
		IncrementGlobal("c-aranfriendbg2","GLOBAL",1)	// move up from even to odd
END

/* Aran's FriendTalks Aim, c-aranfriendbg2, %ARAN_FTT% : delays some talks to be only available after chapter 5 is over */
/* This block takes the even variables set in dialog, and advances them to the odd */
IF
	GlobalGT("c-aranfriendbg2","GLOBAL",26)
	GlobalLT("c-aranfriendbg2","GLOBAL",38)	// shuts down sequence when finished
	RealGlobalTimerExpired("c-aranfriendtimer","GLOBAL")	// Timer Expired
	GlobalGT("Chapter","GLOBAL",%bg2_chapter_5%) // Not in Underdark, and must fire post-losing-soul
	OR(5) 
		Global("c-aranfriendbg2","GLOBAL",28) // set up SoA_FT_15
		Global("c-aranfriendbg2","GLOBAL",30) // set up SoA_FT_16
		Global("c-aranfriendbg2","GLOBAL",32) // set up SoA_FT_17
		Global("c-aranfriendbg2","GLOBAL",34) // set up SoA_FT_18
		Global("c-aranfriendbg2","GLOBAL",36) // set up SoA_FT_19
	//	Global("c-aranfriendbg2","GLOBAL",38) // set up SoA_FT_20 // not written
THEN
	RESPONSE #100
		IncrementGlobal("c-aranfriendbg2","GLOBAL",1)	// move up from even to odd
END

/* Aran's FriendTalks Fire, c-aranfriendbg2, %ARAN_FTT% */
/* This block takes the odd variables set by the last block, and tries to fire them off.	*/
IF
	GlobalLT("c-aranfriendbg2","GLOBAL",38)	// shuts down sequence when finished
	RealGlobalTimerExpired("c-aranfriendtimer","GLOBAL")	// Timer Expired
	!Global("Chapter","GLOBAL",%bg2_chapter_5%) // Not in Underdark - specialized talks for that
	InParty(Myself)						// Aran is here
	!StateCheck(Myself,CD_STATE_NOTVALID)	// Aran is ok
	!StateCheck(Player1,CD_STATE_NOTVALID) // Player1 is ok
	!ActuallyInCombat()
	!See([ENEMY])	// Can't see any enemies
	OR(19)
		Global("c-aranfriendbg2","GLOBAL",1)	// fire SoA_FT_1
		Global("c-aranfriendbg2","GLOBAL",3)	// fire SoA_FT_2
		Global("c-aranfriendbg2","GLOBAL",5)	// fire SoA_FT_3
		Global("c-aranfriendbg2","GLOBAL",7)	// fire SoA_FT_4
		Global("c-aranfriendbg2","GLOBAL",9)	// fire SoA_FT_5
		Global("c-aranfriendbg2","GLOBAL",11)	// fire SoA_FT_6
		Global("c-aranfriendbg2","GLOBAL",13)	// fire SoA_FT_7
		Global("c-aranfriendbg2","GLOBAL",15)	// fire SoA_FT_8
		Global("c-aranfriendbg2","GLOBAL",17)	// fire SoA_FT_9
		Global("c-aranfriendbg2","GLOBAL",19)	// fire SoA_FT_10
		Global("c-aranfriendbg2","GLOBAL",21)	// fire SoA_FT_11
		Global("c-aranfriendbg2","GLOBAL",23)	// fire SoA_FT_12
		Global("c-aranfriendbg2","GLOBAL",25)	// fire SoA_FT_13
		Global("c-aranfriendbg2","GLOBAL",27)	// fire SoA_FT_14
		Global("c-aranfriendbg2","GLOBAL",29)	// fire SoA_FT_15
		Global("c-aranfriendbg2","GLOBAL",31)	// fire SoA_FT_16
		Global("c-aranfriendbg2","GLOBAL",33)	// fire SoA_FT_17
		Global("c-aranfriendbg2","GLOBAL",35)	// fire SoA_FT_18
		Global("c-aranfriendbg2","GLOBAL",37)	// fire SoA_FT_19
	//	Global("c-aranfriendbg2","GLOBAL",31)	// fire SoA_FT_20 NOT WRITTEN
THEN
	RESPONSE #100
		PlaySong(0)	// play a blank reference, stoping the soundtrack
		PlaySound("c-arnfth") // play a .wav or .wavc file
		StartDialogueNoSet(Player1)	// Yo, we are talkin', here...
END


/* Aran's Underdark FriendTalks Aim, c-aranfriendud, %ARAN_FTT% : Setup */
/* This block sets up the underdark talks */
IF
	Global("Chapter","GLOBAL",%bg2_chapter_5%) // In Underdark - specialized talks
	Global("c-aranfriendsetud","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("c-aranfriendsetud","GLOBAL",1)
		RealSetGlobalTimer("c-aranfriendtimer","GLOBAL",600) // 15 minutes real-time minimum
END

/* Aran's Underdark FriendTalks Aim, c-aranfriendud, %ARAN_FTT% */
/* This block takes the even variables set in dialog, and advances them to the odd */

IF
	Global("Chapter","GLOBAL",%bg2_chapter_5%) // In Underdark - specialized talks
	GlobalLT("c-aranfriendud","GLOBAL",9)	// shuts down sequence when finished
	RealGlobalTimerExpired("c-aranfriendtimer","GLOBAL")	// Timer Expired
	OR(5)
		Global("c-aranfriendud","GLOBAL",0)	// set up SoA_UDFT_1
		Global("c-aranfriendud","GLOBAL",2)	// set up SoA_UDFT_2
		Global("c-aranfriendud","GLOBAL",4)	// set up SoA_UDFT_3
		Global("c-aranfriendud","GLOBAL",6)	// set up SoA_UDFT_4
		Global("c-aranfriendud","GLOBAL",8)	// set up SoA_UDFT_5
THEN
	RESPONSE #100
		IncrementGlobal("c-aranfriendud","GLOBAL",1)	// move up from even to odd
END

/* Aran's UnderDark FriendTalks Fire, c-aranfriendbg2, %ARAN_FTT%, Underdark */
/* This block takes the odd variables set by the last block, and tries to fire them off.	*/
IF
	GlobalLT("c-aranfriendud","GLOBAL",10)	// shuts down sequence when finished
	RealGlobalTimerExpired("c-aranfriendtimer","GLOBAL")	// Timer Expired
	Global("Chapter","GLOBAL",%bg2_chapter_5%) // In Underdark
	InParty(Myself)						// Aran is here
	!StateCheck(Myself,CD_STATE_NOTVALID)	// Aran is ok
	!StateCheck(Player1,CD_STATE_NOTVALID) // Player1 is ok
	CombatCounter(0)	// Not in combat
	!See([ENEMY])	// Can't see any enemies
	OR(5)
		Global("c-aranfriendud","GLOBAL",1)	 // fire SoA_UDFT_1
		Global("c-aranfriendud","GLOBAL",3)	 // fire SoA_UDFT_2
		Global("c-aranfriendud","GLOBAL",5)	 // fire SoA_UDFT_3
		Global("c-aranfriendud","GLOBAL",7)	 // fire SoA_UDFT_4
		Global("c-aranfriendud","GLOBAL",9)	 // fire SoA_UDFT_5
THEN
	RESPONSE #100
		PlaySong(0)	// play a blank reference, stoping the soundtrack
		PlaySound("c-arnfti") // play a .wav or .wavc file
		StartDialogueNoSet(Player1)	// Yo, we are talkin', here...
END


/* ROMANCE TALKS */

/* 
 * Romance Match and Initiation (He is not picky...)
 * One new thing here - Aran is ok if a friend switches genders -
 * but not so much on the romance side. So, we add a blocking variable
 * to make sure nothing progresses while that silly Girdle is in place.
 * He can have some special lines to play during the FT sequence on that.
*/

IF
	Global("c-aranmatch","GLOBAL",0)		 // Not evaluated
	Gender(Player1,FEMALE)				 // Player1 is female
	InParty(Myself)						// Aran is here
	!StateCheck(Myself,CD_STATE_NOTVALID)	// Aran is ok
	!StateCheck(Player1,CD_STATE_NOTVALID) // Player1 is ok
	!HasItemEquiped("belt05",Player1)		 // Girdle of sex change not on Player1
THEN
	RESPONSE #100								// 100% of the time
		SetGlobal("c-aranmatch","GLOBAL",1)	// Matched
		SetGlobal("c-aranrom","GLOBAL",1)	// Aran is interested
END

/* Berelinde: Please consider staggering your flirts and your dialogues. Flirts are nice when they break up long stretches between LTs. 
 * cmorgan: OK, great idea - let's make it really complicated, and base the first timer on the player's choice of overall speed of progress...
 */
 /* no early flirt triggering */
 IF
	Global("c-aranmatch","GLOBAL",1)	// Matched
	Global("c-aransetupromtimers","GLOBAL",0) // Not evaluated
	GlobalGT("c-aranfriendbg2","GLOBAL",5) //	FT 3 has played
	Global("c-aranpcflirtstart","GLOBAL",0) // Player has not triggered lightweight flirts via early flirting in PID
	Gender(Player1,FEMALE)				 // Player1 is female
	InParty(Myself)						// Aran is here
	!StateCheck(Myself,CD_STATE_NOTVALID)	// Aran is ok
	!StateCheck(Player1,CD_STATE_NOTVALID) // Player1 is ok
	!HasItemEquiped("belt05",Player1)		 // Girdle of sex change not on Player1
THEN
	RESPONSE #100
 		SetGlobal("c-aransetupromtimers","GLOBAL",1)
		SetGlobal("c-aranpcflirtstart","GLOBAL",1)
 		RealSetGlobalTimer("c-aranromtimer","GLOBAL",%choseninitialrom%) // Minimum Real Time until first LT 
		RealSetGlobalTimer("c-aranflirttimer","GLOBAL",%choseninitialflirt%)  // Tee up flirt timer 
END

/* early flirt triggering */
 IF
	Global("c-aranmatch","GLOBAL",1)	// Matched
	Global("c-aransetupromtimers","GLOBAL",0) // Not evaluated
	GlobalGT("c-aranfriendbg2","GLOBAL",5) //	FT 3 has played
	Global("c-aranpcflirtstart","GLOBAL",1) // Player has already triggered lightweight flirts via early flirting in PID
	Gender(Player1,FEMALE)				 // Player1 is female
	InParty(Myself)						// Aran is here
	!StateCheck(Myself,CD_STATE_NOTVALID)	// Aran is ok
	!StateCheck(Player1,CD_STATE_NOTVALID) // Player1 is ok
	!HasItemEquiped("belt05",Player1)		 // Girdle of sex change not on Player1
THEN
	RESPONSE #100
 		SetGlobal("c-aransetupromtimers","GLOBAL",1)
 		RealSetGlobalTimer("c-aranromtimer","GLOBAL",%choseninitialrom%) // Minimum Real Time until first LT 
		RealSetGlobalTimer("c-aranflirttimer","GLOBAL",%choseninitialflirt%)  // Tee up flirt timer 
END

/* LOVE TALKS */
/* Romance Talks Sequence */

/* Aran's Romance LoveTalks Aim, c-aranbg2rom, %ARAN_LTT% */
/* This block takes the even variables set in dialog, and advances them to the odd */
IF
	GlobalLT("c-aranbg2rom","GLOBAL",15)	// shuts down sequence when finished
	RealGlobalTimerExpired("c-aranromtimer","GLOBAL")	// Timer Expired
	GlobalGT("c-aranfriendbg2","GLOBAL",5) //	FT 3 has played
	!Global("Chapter","GLOBAL",%bg2_chapter_5%) // Not in Underdark - specialized talks for that
	Global("c-aranmatch","GLOBAL",1) // romance matched
	!HasItemEquiped("belt05",Player1) // Not using Girdle of sex change
	OR(8)
		Global("c-aranbg2rom","GLOBAL",0)  // set up SoA_LT_1
		Global("c-aranbg2rom","GLOBAL",2)  // set up SoA_LT_2
		Global("c-aranbg2rom","GLOBAL",4)  // set up SoA_LT_3
		Global("c-aranbg2rom","GLOBAL",6)  // set up SoA_LT_4
		Global("c-aranbg2rom","GLOBAL",8)  // set up SoA_LT_5
		Global("c-aranbg2rom","GLOBAL",10) // set up SoA_LT_6
		Global("c-aranbg2rom","GLOBAL",12) // set up SoA_LT_7
		Global("c-aranbg2rom","GLOBAL",14) // set up SoA_LT_8
 //	 Global("c-aranbg2rom","GLOBAL",16) // set up SoA_LT_9 NOT WRITTEN
 //	 Global("c-aranbg2rom","GLOBAL",18) // set up SoA_LT_10 NOT WRITTEN
 //	 Global("c-aranbg2rom","GLOBAL",20) // set up SoA_LT_11	NOT WRITTEN	
 //	 Global("c-aranbg2rom","GLOBAL",22) // set up SoA_LT_12 NOT WRITTEN
 //	 Global("c-aranbg2rom","GLOBAL",24) // set up SoA_LT_13 NOT WRITTEN
 //	 Global("c-aranbg2rom","GLOBAL",26) // set up SoA_LT_14 NOT WRITTEN
 //	 Global("c-aranbg2rom","GLOBAL",28) // set up SoA_LT_15 NOT WRITTEN
 //	 Global("c-aranbg2rom","GLOBAL",30) // set up SoA_LT_16 NOT WRITTEN
THEN
	RESPONSE #100
		IncrementGlobal("c-aranbg2rom","GLOBAL",1)
END

/* Aran's Romance LoveTalks Fire, c-aranbg2rom, %ARAN_LTT% */
/* This block takes the odd variables set by the last block, and tries to fire them off.	*/
IF
	InParty(Myself)
	See(Player1)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	!StateCheck("c-aran",CD_STATE_NOTVALID)
	GlobalLT("c-aranbg2rom","GLOBAL",16)	// shuts down sequence when finished
	RealGlobalTimerExpired("c-aranromtimer","GLOBAL")	// Timer Expired
	!Global("Chapter","GLOBAL",%bg2_chapter_5%) // Not in Underdark - specialized talks for that
	!HasItemEquiped("belt05",Player1) // Not using Girdle of sex change
	CombatCounter(0)	// Not in combat
	!See([ENEMY])	// Can't see any enemies
	OR(8)
		Global("c-aranbg2rom","GLOBAL",1)  // fire SoA_LT_1
		Global("c-aranbg2rom","GLOBAL",3)  // fire SoA_LT_2
		Global("c-aranbg2rom","GLOBAL",5)  // fire SoA_LT_3
		Global("c-aranbg2rom","GLOBAL",7)  // fire SoA_LT_4
		Global("c-aranbg2rom","GLOBAL",9)  // fire SoA_LT_5
		Global("c-aranbg2rom","GLOBAL",11) // fire SoA_LT_6
		Global("c-aranbg2rom","GLOBAL",13) // fire SoA_LT_7
		Global("c-aranbg2rom","GLOBAL",15) // fire SoA_LT_8
 //	 Global("c-aranbg2rom","GLOBAL",17)	// fire SoA_LT_9 NOT WRITTEN
 //	 Global("c-aranbg2rom","GLOBAL",19)	// fire SoA_LT_10 NOT WRITTEN
 //	 Global("c-aranbg2rom","GLOBAL",21)	// fire SoA_LT_11 NOT WRITTEN
 //	 Global("c-aranbg2rom","GLOBAL",23)	// fire SoA_LT_12 NOT WRITTEN
 //	 Global("c-aranbg2rom","GLOBAL",25)	// fire SoA_LT_13 NOT WRITTEN
 //	 Global("c-aranbg2rom","GLOBAL",27)	// fire SoA_LT_14 NOT WRITTEN
 //	 Global("c-aranbg2rom","GLOBAL",29)	// fire SoA_LT_15 NOT WRITTEN
 //	 Global("c-aranbg2rom","GLOBAL",31)	// fire SoA_LT_16 NOT WRITTEN
THEN
	RESPONSE #100
		PlaySong(0)
		PlaySound("c-arnltu")
		StartDialogueNoSet(Player1)
END

/* NPC-Initiated Flirts: */

/* Set up flirting for initial entries - Set through PID flirting a bunch of times */
IF
	Global("c-aranpcflirtstart","GLOBAL",0)
	GlobalGT("c-aranearlyflirt","LOCALS",14)// try this value - may be too high or too low
	GlobalLT("c-aranfriendbg2","GLOBAL",7)
	GlobalLT("c-aranbg2rom","GLOBAL",7)
	OR(2)
		Global("c-aranrom","GLOBAL",1)
		Global("c-aranrom","GLOBAL",2)
	!HasItemEquiped("belt05",Player1)
THEN RESPONSE #100
	SetGlobal("c-aranpcflirtstart","GLOBAL",1)
	RealSetGlobalTimer("c-aranflirttimer","GLOBAL",%choseninitialflirt%)
END

/* Set Up Flirting After 3 FTs, if player has not taken a shortcut and flirted alot - done in romance talk setup. */

/* Player likes to flirt, 24 interactions by either Aran or PC without shutting him down */
IF
	Global("c-aranpcflirtstart","GLOBAL",1)
	OR(2)
		Global("c-aranrom","GLOBAL",1)
		Global("c-aranrom","GLOBAL",2)
	GlobalGT("c-aranflirt","GLOBAL",24)
	Gender(Player1,FEMALE)
	!HasItemEquiped("belt05",Player1)
THEN 
	RESPONSE #100
		SetGlobal("c-aranrom","GLOBAL",2)
		SetGlobal("c-aranpcflirtstart","GLOBAL",2)
		RealSetGlobalTimer("c-aranflirttimer","GLOBAL",%ARAN_FLIRT%)
END

/* Lightweight Flirts */
IF
	InParty(Myself)
	Global("c-aranpcflirtstart","GLOBAL",1)
	RealGlobalTimerExpired("c-aranflirttimer","GLOBAL")
	Global("c-aranflirtstop","GLOBAL",0)
	Global("c-aranfight","GLOBAL",0)
	OR(2)
		Global("c-aranrom","GLOBAL",1)
		Global("c-aranrom","GLOBAL",2)
	See(Player1)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	!StateCheck("c-aran",CD_STATE_NOTVALID)
	!HasItemEquiped("belt05",Player1)
	CombatCounter(0)
	!AreaCheck("AR2100") /* Underdark */
	!AreaCheck("AR2101") /* Beholder Cave in Underdark */
	!AreaCheck("AR2102") /* Adalon's Cave */
	!AreaCheck("AR2200") /* Ust Natha */
	!AreaCheck("AR2201") /* Temple in Ust Natha */
	!AreaCheck("AR2202") /* Inn in Ust Natha 1st Floor */
	!AreaCheck("AR2203") /* Inn in Ust Natha; 2nd Floor */
	!AreaCheck("AR2204") /* House in Ust Natha */
	!AreaCheck("AR2205") /* House in Ust Natha */
	!AreaCheck("AR2206") /* Qilue's House in Ust Natha */
	!AreaCheck("AR2207") /* Deirex's Tower in Ust Natha */
	!AreaCheck("AR2208") /* Jarlaxle's House wherever */
	!AreaCheck("AR2209") /* Jae'llat's House */
	!AreaCheck("AR2210") /* Deirex's Cave */
	!AreaCheck("AR2400") /* Mind Flayers in Underdark */
	!AreaCheck("AR2401") /* Cave Between Underdark and Exit from Underdark */
	!AreaCheck("AR2402") /* Kuo Toa in Underdark */
	!AreaCheck("AR1500") /* Spellhold */
	!AreaCheck("AR1501") /*  Cave (Spellhold Test) */
	!AreaCheck("AR1502") /*  Fire Room (Spellhold Test) */
	!AreaCheck("AR1503") /*  Spore Room (Spellhold Test) */
	!AreaCheck("AR1504") /*  Crushing Trap Room (Spellhold Test) */
	!AreaCheck("AR1505") /*  Lever Room (Spellhold Test) */
	!AreaCheck("AR1506") /*  Troll Cave (Spellhold Test) */
	!AreaCheck("AR1507") /*  Kobold Room (Spellhold Test) */
	!AreaCheck("AR1508") /*  Final Judgement Spellhold Test */
	!AreaCheck("AR1509") /*  Myconid Room (Spellhold Test) */
	!AreaCheck("AR1510") /*  Sahuagin Room (Spellhold Test) */
	!AreaCheck("AR1511") /*  Elven Table while Spellhold Test */
	!AreaCheck("AR1512") /*  Bodhi's Hunt Level 1 */
	!AreaCheck("AR1513") /*  Bodhi's Hunt Level 2 */
	!AreaCheck("AR1514") /*  Bodhi's Hunt Level 3 (1st Slayer Change Happens here) */
	!AreaCheck("AR1515") /*  Spellhold (Irenicus' Living Room) */
	!AreaCheck("AR1516") /*  Spellhold (Soultheft Level)  */
THEN 
	RESPONSE #100
		SetGlobal("c-aranlightflirt","GLOBAL",1)
		PlaySong(0)
		PlaySound("c-arnltu")
		StartDialogNoSet(Player1)
END

/* Heavyweight Flirts */
IF
	InParty(Myself)
	Global("c-aranpcflirtstart","GLOBAL",2)
	RealGlobalTimerExpired("c-aranflirttimer","GLOBAL")
	Global("c-aranflirtstop","GLOBAL",0)
	Global("c-aranfight","GLOBAL",0)
	OR(2)
		Global("c-aranrom","GLOBAL",1)
		Global("c-aranrom","GLOBAL",2)
	InMyArea(Player1)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	!StateCheck("c-aran",CD_STATE_NOTVALID)
	!HasItemEquiped("belt05",Player1)
	CombatCounter(0)
	!AreaCheck("AR2100") /* Underdark */
	!AreaCheck("AR2101") /* Beholder Cave in Underdark */
	!AreaCheck("AR2102") /* Adalon's Cave */
	!AreaCheck("AR2200") /* Ust Natha */
	!AreaCheck("AR2201") /* Temple in Ust Natha */
	!AreaCheck("AR2202") /* Inn in Ust Natha 1st Floor */
	!AreaCheck("AR2203") /* Inn in Ust Natha; 2nd Floor */
	!AreaCheck("AR2204") /* House in Ust Natha */
	!AreaCheck("AR2205") /* House in Ust Natha */
	!AreaCheck("AR2206") /* Qilue's House in Ust Natha */
	!AreaCheck("AR2207") /* Deirex's Tower in Ust Natha */
	!AreaCheck("AR2208") /* Jarlaxle's House wherever */
	!AreaCheck("AR2209") /* Jae'llat's House */
	!AreaCheck("AR2210") /* Deirex's Cave */
	!AreaCheck("AR2400") /* Mind Flayers in Underdark */
	!AreaCheck("AR2401") /* Cave Between Underdark and Exit from Underdark */
	!AreaCheck("AR2402") /* Kuo Toa in Underdark */
	!AreaCheck("AR1500") /* Spellhold */
	!AreaCheck("AR1501") /*  Cave (Spellhold Test) */
	!AreaCheck("AR1502") /*  Fire Room (Spellhold Test) */
	!AreaCheck("AR1503") /*  Spore Room (Spellhold Test) */
	!AreaCheck("AR1504") /*  Crushing Trap Room (Spellhold Test) */
	!AreaCheck("AR1505") /*  Lever Room (Spellhold Test) */
	!AreaCheck("AR1506") /*  Troll Cave (Spellhold Test) */
	!AreaCheck("AR1507") /*  Kobold Room (Spellhold Test) */
	!AreaCheck("AR1508") /*  Final Judgement Spellhold Test */
	!AreaCheck("AR1509") /*  Myconid Room (Spellhold Test) */
	!AreaCheck("AR1510") /*  Sahuagin Room (Spellhold Test) */
	!AreaCheck("AR1511") /*  Elven Table while Spellhold Test */
	!AreaCheck("AR1512") /*  Bodhi's Hunt Level 1 */
	!AreaCheck("AR1513") /*  Bodhi's Hunt Level 2 */
	!AreaCheck("AR1514") /*  Bodhi's Hunt Level 3 (1st Slayer Change Happens here) */
	!AreaCheck("AR1515") /*  Spellhold (Irenicus' Living Room) */
	!AreaCheck("AR1516") /*  Spellhold (Soultheft Level)  */
THEN 
	RESPONSE #100
		SetGlobal("c-aranheavyflirt","GLOBAL",1)
		PlaySong(0)
		PlaySound("c-arnltl")
		StartDialogNoSet(Player1)
END

/* Bedroll... Flirt?	*/
/* Lots of Flirts means Player Wants Action */
IF
	InParty(Myself)
	GlobalGT("c-aranflirt","GLOBAL",30)
	Global("c-aranbedflirt","GLOBAL",0)
	Global("c-aranpcflirtstart","GLOBAL",2)
	Global("c-aranflirtstop","GLOBAL",0)
	Global("c-aranfight","GLOBAL",0)
	OR(2)
		Global("c-aranrom","GLOBAL",1)
		Global("c-aranrom","GLOBAL",2)
	InMyArea(Player1)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	!StateCheck("c-aran",CD_STATE_NOTVALID)
	CombatCounter(0)
	!AreaCheck("AR2100") /* Underdark */
	!AreaCheck("AR2101") /* Beholder Cave in Underdark */
	!AreaCheck("AR2102") /* Adalon's Cave */
	!AreaCheck("AR2200") /* Ust Natha */
	!AreaCheck("AR2201") /* Temple in Ust Natha */
	!AreaCheck("AR2202") /* Inn in Ust Natha 1st Floor */
	!AreaCheck("AR2203") /* Inn in Ust Natha; 2nd Floor */
	!AreaCheck("AR2204") /* House in Ust Natha */
	!AreaCheck("AR2205") /* House in Ust Natha */
	!AreaCheck("AR2206") /* Qilue's House in Ust Natha */
	!AreaCheck("AR2207") /* Deirex's Tower in Ust Natha */
	!AreaCheck("AR2208") /* Jarlaxle's House wherever */
	!AreaCheck("AR2209") /* Jae'llat's House */
	!AreaCheck("AR2210") /* Deirex's Cave */
	!AreaCheck("AR2400") /* Mind Flayers in Underdark */
	!AreaCheck("AR2401") /* Cave Between Underdark and Exit from Underdark */
	!AreaCheck("AR2402") /* Kuo Toa in Underdark */
	!AreaCheck("AR1500") /* Spellhold */
	!AreaCheck("AR1501") /*  Cave (Spellhold Test) */
	!AreaCheck("AR1502") /*  Fire Room (Spellhold Test) */
	!AreaCheck("AR1503") /*  Spore Room (Spellhold Test) */
	!AreaCheck("AR1504") /*  Crushing Trap Room (Spellhold Test) */
	!AreaCheck("AR1505") /*  Lever Room (Spellhold Test) */
	!AreaCheck("AR1506") /*  Troll Cave (Spellhold Test) */
	!AreaCheck("AR1507") /*  Kobold Room (Spellhold Test) */
	!AreaCheck("AR1508") /*  Final Judgement Spellhold Test */
	!AreaCheck("AR1509") /*  Myconid Room (Spellhold Test) */
	!AreaCheck("AR1510") /*  Sahuagin Room (Spellhold Test) */
	!AreaCheck("AR1511") /*  Elven Table while Spellhold Test */
	!AreaCheck("AR1512") /*  Bodhi's Hunt Level 1 */
	!AreaCheck("AR1513") /*  Bodhi's Hunt Level 2 */
	!AreaCheck("AR1514") /*  Bodhi's Hunt Level 3 (1st Slayer Change Happens here) */
	!AreaCheck("AR1515") /*  Spellhold (Irenicus' Living Room) */
	!AreaCheck("AR1516") /*  Spellhold (Soultheft Level)  */
THEN
	RESPONSE #100
		SetGlobal("c-aranbedflirt","GLOBAL",1)
		SetGlobal("c-aranrom","GLOBAL",2)
		StartDialogNoSet(Player1)
END


/* OK, now on to some fun blocks to play with. These are things Aran can blather on about. */


/* TALKS, FLOATING AND SMALL */
/* Covers both specific reactions, floaters, and any smalltalk reactions (could also be
 * called "after-the-fact interjections")
*/

/* Garden Booty call 

IF
	Global("c-arangardenmakeout","GLOBAL",1)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	CombatCounter(0)
	!See([ENEMY])
THEN
	RESPONSE #100
		// <<START CUTSCENE HERE>>
		StartDialogueNoSet(Player1)
END

*/

/* After-Vampification Talk, Canonical, 2nd Class. */
IF
	!InParty(Myself)
	Global("c-aranvamped","GLOBAL",4)
THEN
	RESPONSE #100
		SetGlobal("c-aranvamped","GLOBAL",5)
		StartDialogueNoSet(Player1)
END

/* Drunk Talks (incorporates Flirts if gender and romance variables set)	*/
/* Using GLOBAL here so it can influence friendtalks */
IF
	GlobalLT("c-arandrunk","GLOBAL",3)	// shuts down sequence when finished
	InParty(Myself)
	CheckStatGT("c-aran",40,INTOXICATION)	// Whoot - the room is moving about too much
	GlobalTimerExpired("c-aranisdrunk","GLOBAL")
	OR(13)
		AreaCheck("AR0313") // Sea's Bounty
		AreaCheck("AR0406") // Copper Coronet
		AreaCheck("AR0509") // Five Flagons
		AreaCheck("AR0522") // Five Flagons (Stronghold)
		AreaCheck("AR0704") // Mithrest Inn
		AreaCheck("AR1105") // Umar Inn
		AreaCheck("AR1602") // The Vulgar Monkey
		AreaCheck("AR2010") // Vyatri's Pub, Trademeet
		AreaCheck("AR0709") // Den of the Seven Vales 1st Floor
		AreaCheck("AR0513") // Calbor's Inn at Bridge District 1st Floor
		AreaCheck("AR0021") // Crooked Crane 1st Floor
		AreaCheck("AR1602") // Brynnlaw's Inn
		AreaCheck("C-AR01") // The Broken Sword (Aran's initial inn )
	OR(2)
		Global("c-arandrunk","GLOBAL",0)
		Global("c-arandrunk","GLOBAL",2)
		// Global("c-arandrunk","GLOBAL",4)
	InMyArea(Player1)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	CombatCounter(0)
	!See([ENEMY])
THEN
	RESPONSE #100
		IncrementGlobal("c-arandrunk","GLOBAL",1)
END

IF
	GlobalLT("c-arandrunk","GLOBAL",4)	// shuts down sequence when finished
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	InMyArea(Player1)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	OR(13)
		AreaCheck("AR0313") // Sea's Bounty
		AreaCheck("AR0406") // Copper Coronet
		AreaCheck("AR0509") // Five Flagons
		AreaCheck("AR0522") // Five Flagons (Stronghold)
		AreaCheck("AR0704") // Mithrest Inn
		AreaCheck("AR1105") // Umar Inn
		AreaCheck("AR1602") // The Vulgar Monkey
		AreaCheck("AR2010") // Vyatri's Pub, Trademeet
		AreaCheck("AR0709") // Den of the Seven Vales 1st Floor
		AreaCheck("AR0513") // Calbor's Inn at Bridge District 1st Floor
		AreaCheck("AR0021") // Crooked Crane 1st Floor
		AreaCheck("AR1602") // Brynnlaw's Inn
		AreaCheck("C-AR01") // The Broken Sword (Aran's initial inn )
	CombatCounter(0)	// Not in combat
	!See([ENEMY])	// Can't see any enemies
	OR(2)
		Global("c-arandrunk","GLOBAL",1)
		Global("c-arandrunk","GLOBAL",3)
		// Global("c-arandrunk","GLOBAL",5)
THEN
	RESPONSE #100
		PlaySong(0)
		PlaySound("c-arandf")
		StartDialogueNoSet(Player1)
END

/* Monster Reactions */

/* Commenting on some Monster Encounters, Working for The Man/Undead */
/* For catching general objects without regard to DVs, we can use a general catch all using the .ids entries -
 * [EA.GENERAL.RACE.CLASS]. An entry of 0 in a field will match any value.
 * For example: [ENEMY.0.0.MAGE] specifies all creatures that are enemies of the party, any general category, any race, mages.
 * Amber uses these to good effect, so I started by borrowing from that code, then readjusting and extending -
*/

/* Liches Are Scary (Darios) : Activate */
IF
	Global("c-silencearan","GLOBAL",0)
	Global("c-aranlich","LOCALS",0)
	OR(2)
		Killed([0.0.LICH])
		Killed([0.0.DEMILICH])
	 InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-aranlich","LOCALS",1)
END
/* Liches Are Scary (Darios) : Initiate */
IF
	Global("c-aranlich","LOCALS",1)
	Global("c-silencearan","GLOBAL",0)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	InMyArea(Player1)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		StartDialogNoSet(Player1)
END
/* Where's Buffy When You Need Her : Rollback */
IF
	Global("c-silencearan","GLOBAL",0)
	Global("c-aranseevamp","LOCALS",1)
	!See([0.0.VAMPIRE])
	!See([0.0.VAMPYRE])
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-aranseevamp","LOCALS",0)
END
/* Where's Buffy When You Need Her : Activate */
IF
	Global("c-silencearan","GLOBAL",0)
	Global("c-aranseevamp","LOCALS",0)
	OR(2)
	  See([0.0.VAMPIRE])
	  See([0.0.VAMPYRE])
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-aranseevamp","LOCALS",1)
END
/* Where's Buffy When You Need Her : Initiate */
IF
	Global("c-aranseevamp","LOCALS",1)
	Global("c-silencearan","GLOBAL",0)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	InMyArea(Player1)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		StartDialogNoSet(Player1)
END
/* See a Troll : Rollback */
IF
	Global("c-silencearan","GLOBAL",0)
	Global("c-arantroll","LOCALS",1)
	!See([0.0.TROLL])
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arantroll","LOCALS",0)
END
/* See a Troll : Activate */
IF
	Global("c-silencearan","GLOBAL",0)
	Global("c-arantroll","LOCALS",0)
	See([0.0.TROLL])
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arantroll","LOCALS",1)
END
/* See a Troll : Initiate */
IF
	Global("c-arantroll","LOCALS",1)
	Global("c-silencearan","GLOBAL",0)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	InMyArea(Player1)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		StartDialogNoSet(Player1)
END
/* Shade Lord (Darios) : Rollback */
IF
	Global("c-aranshadelord","LOCALS",1)
	!AreaCheck("AR1400") // Temple ruins
	!AreaCheck("AR1404") // Temple ruins restored
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-aranshadelord","LOCALS",0)
END
/* Shade Lord (Darios) : Activate */
IF
	Killed([0.UNDEAD.SHADOW.SHADOW.0.FEMALE]) // Shade Lord
	Global("c-silencearan","GLOBAL",0)
	Global("c-aranshadelord","LOCALS",0)
	OR(2)
		AreaCheck("AR1400") // Temple ruins
		AreaCheck("AR1404") // Temple ruins restored
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-aranshadelord","LOCALS",1)
END
/* Shade Lord (Darios) : Initiate */
IF
	Global("c-aranshadelord","LOCALS",1)
	Global("c-silencearan","GLOBAL",0)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	InMyArea(Player1)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		StartDialogNoSet(Player1)
END
/* SoA Scenery Talks : Shadow Dragon seen c-arshaddrag : Escape if not played */
IF
	Global("c-arshaddragseen","GLOBAL",1)
	InParty(Myself)
	!AreaCheck("AR1402")	
THEN
	RESPONSE #100
		SetGlobal("c-arshaddragseen","GLOBAL",5)
END
/* SoA Scenery Talks : Shadow Dragon seen c-arshaddrag : Activate */
IF
	Global("c-arshaddragseen","GLOBAL",0)
	AreaCheck("AR1402")
	See("ShaDra01")
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	InMyArea(Player1)
	!StateCheck(Player1,CD_STATE_NOTVALID) 
THEN
	RESPONSE #100
		SetGlobal("c-arshaddragseen","GLOBAL",1)
END
/* SoA Scenery Talks : Shadow Dragon seen c-arshaddrag : Initiate */
IF
	Global("c-arshaddragseen","GLOBAL",1)
	!ActuallyInCombat()
	!Dead("ShaDra01")
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	InMyArea(Player1)
	!StateCheck(Player1,CD_STATE_NOTVALID) 
THEN
	RESPONSE #100
		StartDialogueNoSet(Player1)
END
/* SoA Scenery Talks : Shadow Dragon clobbered c-arshaddrag : Activate */
IF
	Global("c-arshaddrag","GLOBAL",0)
	AreaCheck("AR1402")
	Dead("ShaDra01")
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	InMyArea(Player1)
	!StateCheck(Player1,CD_STATE_NOTVALID) 
THEN
	RESPONSE #100
		SetGlobal("c-arshaddrag","GLOBAL",1)
END
/* SoA Scenery Talks : Shadow Dragon clobbered c-arshaddrag : Initiate */
IF
	Global("c-arshaddrag","GLOBAL",1)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	InMyArea(Player1)
	!StateCheck(Player1,CD_STATE_NOTVALID) 
THEN
	RESPONSE #100
		StartDialogueNoSet(Player1)
END
/* SoA Scenery Talks : Shadow Dragon clobbered c-arshaddrag : Escape if not played */
IF
	Global("c-arshaddrag","GLOBAL",1)
	InParty(Myself)
	!AreaCheck("AR1402")
	Dead("ShaDra01")	
THEN
	RESPONSE #100
		SetGlobal("c-arshaddrag","GLOBAL",5)
END
/* SoA Scenery Talks :  Aran Dragon-Slayer (Darios) :  Activate */
IF
	Killed([0.0.DRAGON])
	!AreaCheck("AR2102") // Adalon's cave
	!AreaCheck("AR1402")
	Global("c-silencearan","GLOBAL",0)
	Global("c-arandragon","LOCALS",0)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arandragon","LOCALS",1)
END
/* SoA Scenery Talks :  Aran Dragon-Slayer (Darios) :  Initiate */
IF
	Global("c-silencearan","GLOBAL",0)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	InMyArea(Player1)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	Global("c-arandragon","LOCALS",1)
THEN
	RESPONSE #100
		StartDialogNoSet(Player1)
END
/* SoA Scenery Talks :  Basilisk Baiting  : Activate */
IF
	Global("c-silencearan","GLOBAL",0)
	Global("c-aranbasilisk","LOCALS",0)
	Killed([0.0.BASILISK])
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-aranbasilisk","LOCALS",1)
END
/* SoA Scenery Talks :  Basilisk Baiting  : Initiate */
IF
	Global("c-silencearan","GLOBAL",0)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	InMyArea(Player1)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	Global("c-aranbasilisk","LOCALS",1)
THEN
	RESPONSE #100
		StartDialogNoSet(Player1)
END
/* SoA Scenery Talks :  Poisonous Cloakwood Ettercaps : Activate  */
IF
	Killed([0.0.ETTERCAP])
	Global("c-silencearan","GLOBAL",0)
	Global("c-aranettercap","LOCALS",0)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-aranettercap","LOCALS",1)
END
/* SoA Scenery Talks :  Poisonous Cloakwood Ettercaps : Initiate  */
IF
	GlobalTimerExpired("c-aransmalltalk","GLOBAL") // Timer (game-time) has expired
	Global("c-silencearan","GLOBAL",0)	// a PID - set "silencer" for folks who hate unsolicited comments
	Global("c-aranettercap","LOCALS",1)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	InMyArea(Player1)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		StartDialogNoSet(Player1)
END
/* SoA Scenery Talks :  Golems are Big Boys : Activate */
IF
	Killed([0.0.GOLEM])
	Global("c-silencearan","GLOBAL",0)
	Global("c-arangolem","LOCALS",0)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arangolem","LOCALS",1)
END
/* SoA Scenery Talks :  Golems are Big Boys : Initiate */
IF
	GlobalTimerExpired("c-aransmalltalk","GLOBAL") // Timer (game-time) has expired
	Global("c-silencearan","GLOBAL",0)	// a PID - set "silencer" for folks who hate unsolicited comments
	Global("c-arangolem","LOCALS",1)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	InMyArea(Player1)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		StartDialogNoSet(Player1)
END
/* SoA Scenery Talks :  Zombies: Looks Like Me After A Night On The Town : Activate */
IF
	Killed([0.0.ZOMBIE])
	Global("c-silencearan","GLOBAL",0)
	Global("c-aranzombie","LOCALS",0)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-aranzombie","LOCALS",1)
END
/* SoA Scenery Talks :  Zombies: Looks Like Me After A Night On The Town : Initiate */
IF
	GlobalTimerExpired("c-aransmalltalk","GLOBAL") // Timer (game-time) has expired
	Global("c-silencearan","GLOBAL",0)	// a PID - set "silencer" for folks who hate unsolicited comments
	Global("c-aranzombie","LOCALS",1)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	InMyArea(Player1)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		StartDialogNoSet(Player1)
END
/* SoA Scenery Talks :  Real Great Employer, <CHARNAME>. Someone pass me the Daystar. : Activate  */
IF
	Global("WorkingForBodhi","GLOBAL",1)
	Global("c-silencearan","GLOBAL",0)
	Global("c-aranworkbod","LOCALS",0)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-aranworkbod","LOCALS",1)
END
/* SoA Scenery Talks :  Real Great Employer, <CHARNAME>. Someone pass me the Daystar. : Initiate  */
IF
	Global("c-silencearan","GLOBAL",0)	// a PID - set "silencer" for folks who hate unsolicited comments
	Global("c-aranworkbod","LOCALS",1)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	InMyArea(Player1)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		StartDialogNoSet(Player1)
END
/* SoA Scenery Talks :  Real Great Employer, <CHARNAME>. But at least he's not undead. I think. : Activate */
IF
	Global("WorkingForAran","GLOBAL",1)
	Global("c-silencearan","GLOBAL",0)
	Global("c-aranworkaran","LOCALS",0)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-aranworkaran","LOCALS",1)
END
/* SoA Scenery Talks :  Real Great Employer, <CHARNAME>. But at least he's not undead. I think. : Initiate  */
IF
	GlobalTimerExpired("c-aransmalltalk","GLOBAL") // Timer (game-time) has expired
	Global("c-silencearan","GLOBAL",0)	// a PID - set "silencer" for folks who hate unsolicited comments
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	InMyArea(Player1)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	Global("c-aranworkaran","LOCALS",1)
THEN
	RESPONSE #100
		StartDialogNoSet(Player1)
END
/* SoA Scenery Talks :  Phaere is a hawt chick (male PC); is no good for you (female PC); better not have touched you (Romance) */
IF
	Global("c-aranphaere","LOCALS",0)
	Global("c-silencearan","GLOBAL",0)	// a PID - set "silencer" for folks who hate unsolicited comments
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	OR(2)
		Global("PhaereInnuendo","GLOBAL",2)
		Global("PhaereInnuendo","GLOBAL",3)
THEN
	RESPONSE #100
		SetGlobal("c-aranphaere","LOCALS",1)
END
/* SoA Scenery Talks :  Commenting on Phaerie */
IF
	GlobalTimerExpired("c-aransmalltalk","GLOBAL") // Timer (game-time) has expired
	Global("c-silencearan","GLOBAL",0)	// a PID - set "silencer" for folks who hate unsolicited comments
	Global("c-aranphaere","LOCALS",1)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		StartDialogNoSet(Player1)
END

/* SoA Scenery Talks :  Slums Slavers (Darios, extended) : Escape if not played */
IF
	Global("c-silencearan","GLOBAL",0)	// a PID - set "silencer" for folks who hate unsolicited comments
	Global("c-aranslaver","LOCALS",1)
	InParty(Myself)
	!AreaCheck("AR0400")	// The Slums
THEN
	RESPONSE #100
		SetGlobal("c-aranslaver","LOCALS",9)
END
/* SoA Scenery Talks : Slums Slavers (Darios, extended) : Activate */
IF	
	Global("c-silencearan","GLOBAL",0)	// a PID - set "silencer" for folks who hate unsolicited comments
	Global("c-aranslaver","LOCALS",0)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	AreaCheck("AR0400")	// The Slums
	OR(3)
		See("SlumsSlaver2")
		See("SlumsSlaver3")
		See("SlumsSlave1")
THEN
	RESPONSE #100
		SetGlobal("c-aranslaver","LOCALS",1)
END
/* SoA Scenery Talks :  Slums Slavers (Darios, extended) : Initiate */
IF
	Global("c-silencearan","GLOBAL",0)	// a PID - set "silencer" for folks who hate unsolicited comments
	Global("c-aranslaver","LOCALS",1)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		StartDialogNoSet(Player1)
END
/* SoA Scenery Talks  : Graveyard  : Rollback */
IF
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	!AreaCheck("AR0800")
	Global("c-arangravecomment","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("c-arangravecomment","LOCALS",0)
END
/* SoA Scenery Talks  : Graveyard  : Activate */
IF
	Global("c-silencearan","GLOBAL",0)	// a PID - set "silencer" for folks who hate unsolicited comments
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	AreaCheck("AR0800")
	Global("c-arangravecomment","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("c-arangravecomment","LOCALS",1)
END
/* SoA Scenery Talks  : Graveyard  : Initiate */
IF
	Global("c-silencearan","GLOBAL",0)	// a PID - set "silencer" for folks who hate unsolicited comments
	Global("c-arangravecomment","LOCALS",1)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		StartDialogueNoSet(Player1)
END 
/* SoA Commentary/Reactions, called from .bcs : Auntie Is a PITA :  set from ICT */
/* SoA Scenery Talks  : Auntie Is a PITA  : Initiate */
IF
	Global("c-aranoldbat","GLOBAL",1)
	AreaCheck("AR1303")
	!See("DELCIA")
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		StartDialogueNoSet(Player1)
END 
/* SoA Scenery Talks  : Auntie Is a PITA  : Rollback */
IF
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	!AreaCheck("AR1303")
	Global("c-aranoldbat","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("c-aranoldbat","GLOBAL",2)
END

/* SoA Scenery Talks  :  Git the Guild  : Activate  
IF
	Global("PlayerThiefGuild","GLOBAL",1)
	Global("c-aranguild","LOCALS",0)
	AreaCheck("AR0300")
THEN
	RESPONSE #100
		SetGlobal("c-aranguild","LOCALS",1)
END

SoA Scenery Talks  :  Git the Guild  : Initiate  
IF
	Global("PlayerThiefGuild","GLOBAL",1)
	Global("c-aranguild","LOCALS",0)
	AreaCheck("AR0300")
THEN
	RESPONSE #100
		SetGlobal("c-aranguild","LOCALS",1)
END
talk not written in yet
*/


/* SoA Scenery Talks (no rollback needed) : Setting Aran as Leader : Activate */
IF
	Global("c-silencearan","GLOBAL",0)	// a PID - set "silencer" for folks who hate unsolicited comments
	Global("c-aranleader","LOCALS",0)
	Name("c-aran",Player1Fill)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-aranleader","LOCALS",1)
END
/* SoA Scenery Talks (no rollback needed) : Setting Aran as Leader : Initiate */
IF
	Global("c-silencearan","GLOBAL",0)	// a PID - set "silencer" for folks who hate unsolicited comments
	Global("c-aranleader","LOCALS",1)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		StartDialogNoSet(Player1)
END
/* SoA Scenery Talks (no rollback needed) : You look dead on your feet : Activate */
IF
	Global("c-silencearan","GLOBAL",0)	// a PID - set "silencer" for folks who hate unsolicited comments
	CheckStatGT(Player1,6,FATIGUE)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	Global("c-aranpctired","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("c-aranpctired","LOCALS",1)
END
/* SoA Scenery Talks (no rollback needed) : You look dead on your feet : Initiate */
IF
	GlobalTimerExpired("c-aransmalltalk","GLOBAL") // Timer (game-time) has expired
	Global("c-silencearan","GLOBAL",0)	// a PID - set "silencer" for folks who hate unsolicited comments
	Global("c-aranpctired","LOCALS",1)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		StartDialogNoSet(Player1)
END


/* Scenery Dialog : Temple Comments, Only If Not A Cleric (even minimal training would keep him from starting a holy fight) */
/* Temple Comment : Oghma : Rollback */
IF
	Global("c-aranoghma","LOCALS",1)
	!AreaCheck("AR0319") // Temple of Oghma
	InParty(Myself)
THEN
	RESPONSE #100
		SetGlobal("c-aranoghma","LOCALS",0)
END
/* Temple Comment : Oghma : Activate */
IF
	Global("c-silencearan","GLOBAL",0)
	Global("c-aranoghma","LOCALS",0)
	AreaCheck("AR0319") // Temple of Oghma
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-aranoghma","LOCALS",1)
END
/* Temple Comment : Oghma : Initiate */
IF
	GlobalTimerExpired("c-aransmalltalk","GLOBAL") // Timer (game-time) has expired
	Global("c-silencearan","GLOBAL",0)	// a PID - set "silencer" for folks who hate unsolicited comments
	Global("c-aranoghma","LOCALS",1)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		StartDialogNoSet(Player1)
END
/* Temple Comment : Ilmater : Rollback */
IF
	Global("c-aranilmater","LOCALS",1)
	!AreaCheck("AR0408") // Temple of Ilmater
	!AreaCheck("AR0703") // Temple of Ilmater
	InParty(Myself)
THEN
	RESPONSE #100
		SetGlobal("c-aranilmater","LOCALS",0)
END
/* Temple Comment : Ilmater : Activate */
IF
	Global("c-silencearan","GLOBAL",0)
	Global("c-aranilmater","LOCALS",0)
	OR(2)
		AreaCheck("AR0408") // Temple of Ilmater
		AreaCheck("AR0703") // Temple of Ilmater
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-aranilmater","LOCALS",1)
END
/* Temple Comment : Ilmater : Initiate */
IF
	GlobalTimerExpired("c-aransmalltalk","GLOBAL") // Timer (game-time) has expired
	Global("c-silencearan","GLOBAL",0)	// a PID - set "silencer" for folks who hate unsolicited comments
	Global("c-aranilmater","LOCALS",1)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		StartDialogNoSet(Player1)
END
/* Temple Comment : Helm : Rollback */
IF
	!Class(Myself,CLERIC_ALL)
	Global("c-aranhelm","LOCALS",1)
	!AreaCheck("AR0512") // Temple of Helm
	!AreaCheck("AR0901") // Temple of Helm
	InParty(Myself)
THEN
	RESPONSE #100
		SetGlobal("c-aranhelm","LOCALS",0)
END
/* Temple Comment : Helm : Activate */
IF
	Global("c-silencearan","GLOBAL",0)
	Global("c-aranhelm","LOCALS",0)
	OR(2)
		AreaCheck("AR0512") // Temple of Helm
		AreaCheck("AR0901") // Temple of Helm
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-aranhelm","LOCALS",1)
END
/* Temple Comment : Helm : Initiate */
IF
	GlobalTimerExpired("c-aransmalltalk","GLOBAL") // Timer (game-time) has expired
	Global("c-silencearan","GLOBAL",0)	// a PID - set "silencer" for folks who hate unsolicited comments
	Global("c-aranhelm","LOCALS",1)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		StartDialogNoSet(Player1)
END
/* Temple Comment : Lathander : Rollback */
IF
	Global("c-aranlath","LOCALS",1)
	!AreaCheck("AR0902") // Temple of Lathander
	InParty(Myself)
THEN
	RESPONSE #100
		SetGlobal("c-aranlath","LOCALS",0)
END
/* Temple Comment : Lathander : Activate */
IF
	Global("c-silencearan","GLOBAL",0)
	Global("c-aranlath","LOCALS",0)
	AreaCheck("AR0902") // Temple of Lathander
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-aranlath","LOCALS",1)
END
/* Temple Comment : Lathander : Initiate */
IF
	GlobalTimerExpired("c-aransmalltalk","GLOBAL") // Timer (game-time) has expired
	Global("c-silencearan","GLOBAL",0)	// a PID - set "silencer" for folks who hate unsolicited comments
	Global("c-aranlath","LOCALS",1)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		StartDialogNoSet(Player1)
END
/* Temple Comment : Umberlee : Rollback */
IF
	Global("c-aranumberlee","LOCALS",1)
	!AreaCheck("AR1604") // Temple of Umberlee
	InParty(Myself)
THEN
	RESPONSE #100
		SetGlobal("c-aranumberlee","LOCALS",0)
END
/* Temple Comment : Umberlee : Activate */
IF
	Global("c-silencearan","GLOBAL",0)
	Global("c-aranumberlee","LOCALS",0)
	AreaCheck("AR1604") // Temple of Umberlee
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-aranumberlee","LOCALS",1)
END
/* Temple Comment : Umberlee : Initiate */
IF
	GlobalTimerExpired("c-aransmalltalk","GLOBAL") // Timer (game-time) has expired
	Global("c-silencearan","GLOBAL",0)	// a PID - set "silencer" for folks who hate unsolicited comments
	Global("c-aranumberlee","LOCALS",1)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		StartDialogNoSet(Player1)
END
/* Temple Comment : Waukeen : Rollback */
IF
	Global("c-aranwaukeen","LOCALS",1)
	!AreaCheck("AR1010") // Temple of Waukeen
	!AreaCheck("AR2008") // Temple of Waukeen
	InParty(Myself)
THEN
	RESPONSE #100
		SetGlobal("c-aranwaukeen","LOCALS",0)
END
/* Temple Comment : Waukeen : Activate */
IF
	Global("c-silencearan","GLOBAL",0)
	Global("c-aranwaukeen","LOCALS",0)
	OR(2)
		AreaCheck("AR1010") // Temple of Waukeen
		AreaCheck("AR2008") // Temple of Waukeen
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-aranwaukeen","LOCALS",1)
END
/* Temple Comment : Waukeen : Initiate */
IF
	GlobalTimerExpired("c-aransmalltalk","GLOBAL") // Timer (game-time) has expired
	Global("c-silencearan","GLOBAL",0)	// a PID - set "silencer" for folks who hate unsolicited comments
	Global("c-aranwaukeen","LOCALS",1)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		StartDialogNoSet(Player1)
END
/* SoA Scenery Talks (no rollback needed) : Gavin Raised From The Dead : Activate */
/* (but only if both are in the party when Gavin gets sliced and diced) */
IF 
	InPartyAllowDead("B!Gavin2")
	InParty(Myself)	
	Global("c-argavinraised","GLOBAL",0)
	Global("c-argavincheck","GLOBAL",0)
	OR(6)
		StateCheck("B!Gavin2",STATE_DEAD) 
		StateCheck("B!Gavin2",STATE_ACID_DEATH) 
		StateCheck("B!Gavin2",STATE_FLAME_DEATH) 
		StateCheck("B!Gavin2",STATE_EXPLODING_DEATH) 
		StateCheck("B!Gavin2",STATE_STONE_DEATH) 
		StateCheck("B!Gavin2",STATE_FROZEN_DEATH)
THEN
	RESPONSE #100
		SetGlobal("c-argavincheck","GLOBAL",1)
END
/* SoA Scenery Talks (no rollback needed) : Gavin Raised From The Dead : Initiate */
IF
	Global("c-argavincheck","GLOBAL",1)
	GlobalGT("B!GavRaised","GLOBAL",1)
	InParty("B!Gavin2")
	!StateCheck("B!Gavin2",CD_STATE_NOTVALID)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-argavinraised","GLOBAL",1)
		StartDialogueNoSet(Player1)
END
/* SoA Scenery Talks (no rollback needed) : Inked or Stolen Letters (no secrets) : Activate  */
IF
	GlobalTimerExpired("c-aranlettertalk","GLOBAL")
	Global("c-arannosecrets","GLOBAL",1)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arannosecrets","GLOBAL",2)
END
/* SoA Scenery Talks (no rollback needed) : Inked or Stolen Letters (no secrets) : Initiate */
IF
	Global("c-arannosecrets","GLOBAL",2)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		StartDialogNoSet(Player1)
END
/* SoA Scenery Talks (no rollback needed) : Inked or Stolen Letters : Activate */
IF
	GlobalTimerExpired("c-aranlettertalk","GLOBAL")
	Global("c-arlettertaken","GLOBAL",1)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-arlettertaken","GLOBAL",2)

END
/* SoA Scenery Talks (no rollback needed) : Inked or Stolen Letters : Initiate */
IF
	Global("c-arlettertaken","GLOBAL",2)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		StartDialogNoSet(Player1)
END
/* SoA Scenery Talks (no rollback needed) : Stronghold Gains and Losses : Activate */
IF
	Global("c-aranextort","LOCALS",1)
	GlobalTimerExpired("c-aranextorttalk","GLOBAL")
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("c-aranextort","GLOBAL",2)	
END 
/* SoA Scenery Talks (no rollback needed) : Stronghold Gains and Losses : Initiate */
IF
	Global("c-aranextort","GLOBAL",2)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		StartDialogueNoSet(Player1)
END
/* SoA Scenery Talks (no rollback needed) : Aran Apologizes */
IF
	GlobalTimerExpired("c-aranismad","GLOBAL")
	Global("c-aranfight","GLOBAL",1)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
	    SetGlobal("c-aranfight","GLOBAL",0)
		SetGlobal("c-aranapology","GLOBAL",1)
		StartDialogueNoSet(Player1)
END 
/* SoA Scenery Talks (no rollback needed) : Night Talk Reset : something else fired and blocked it */
IF
  Global("c-arannightvisit","GLOBAL",2)
  InParty("c-aran")
  !StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck("c-aran",CD_STATE_NOTVALID)
THEN  
  RESPONSE #100
	SetGlobal("c-arannightvisit","GLOBAL",1)
END
/* SoA Scenery Talks (no rollback needed) : DisplayStringHead : Childish Jokes Are Almost Always Funny */
IF
	Global("c-silencearan","GLOBAL",0)
	GlobalTimerExpired("c-arananomensilly","GLOBAL")
	OR(2)
		GlobalGT("c-arananomen","GLOBAL",0)
		GlobalGT("c-anomenaran","GLOBAL",0)
	Global("c-arananomenf","LOCALS",0)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	InParty("Anomen")
	!StateCheck("Anomen",CD_STATE_NOTVALID)
	!StateCheck("Anomen",CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@13137)
		Wait(2)
		DisplayStringHead("Anomen",@13138)
		Wait(2)
		DisplayStringHead(Myself,@13139)
		Wait(3)
		DisplayStringHead(Myself,@13140)
		Wait(2)
		SetGlobal("c-arananomenf","LOCALS",1)
		SetGlobalTimer("c-aransmalltalk","GLOBAL",300)
END
/* AI Script from usual NPCs */
/* IF enemy THEN let the game know and set up out-of-party condition CONTINUE */
IF
	Allegiance(Myself,ENEMY)
	!InParty(Myself)
	Global("NPCFight","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("NPCFight","LOCALS",1)
		ChangeAIScript("",DEFAULT)
		ChangeAIScript("useitem",GENERAL)
		ChangeAIScript("c-aranx",SPECIFICS)
		SetDialog("")
		Continue()
END
/* IF notenemy AND attacked THEN make me enemy and set up out-of-party condition CONTINUE */
IF
	Allegiance(Myself,NEUTRAL)
	AttackedBy([GOODCUTOFF],DEFAULT)
THEN
	RESPONSE #100
		ChangeAIScript("c-aranx",SPECIFICS)
		ChangeAIScript("useitem",GENERAL)
		ChangeAIScript("",DEFAULT)
		Enemy()
		Continue()
END
/* IF have been enemy but have been set to neutral THEN repair out-of-party condition to neutral CONTINUE */
IF
	!Allegiance(Myself,ENEMY)
	!InParty(Myself)
	Global("NPCFight","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("NPCFight","LOCALS",0)
		ChangeAIScript("",GENERAL)
		ChangeAIScript("",SPECIFICS)
		Continue()
END

