/* NightTalk: Stars, Constancy Thereof, ToB  */
IF
    Global("c-tobnightone","GLOBAL",0)
    OR(2)
        Global("c-arangoaded","GLOBAL",0)
        Global("c-arangoaded","GLOBAL",6)
    !Global("c-arannightvisit","GLOBAL",1)
    TimeofDay(NIGHT)
    AreaType(OUTDOOR)
    InParty(Myself)
    !StateCheck(Player1,CD_STATE_NOTVALID)
    !StateCheck(Myself,CD_STATE_NOTVALID)
THEN RESPONSE #100
    SetGlobal("c-tobnightone","GLOBAL",1)
    StartDialogueNoSet(Player1)
END

