DO ~ClearAllActions() StartCutSceneMode() StartCutScene("c-restco")~  /* Camping Out */
DO ~ClearAllActions() StartCutSceneMode() StartCutScene("c-restdg")~  /* Dungeon */
DO ~ClearAllActions() StartCutSceneMode() StartCutScene("c-restin")~  /* Inn */
DO ~ClearAllActions() StartCutSceneMode() StartCutScene("c-restpp")~  /* PocketPlane */


IF ~~ t1eb10.0f2 
SAY ~(Gavin folds you in his arms and eases you onto the bedroll. Tender kisses become more urgent, and the night sounds fade away.)~ 
IF ~!AreaCheck("AR0085") 
    !AreaCheck("AR1100") 
    !AreaCheck("AR1101") 
    !AreaCheck("AR1102") 
    !AreaCheck("AR1104") 
    !AreaCheck("AR1105") 
    !AreaCheck("AR1106") 
    !AreaCheck("AR1107") 
    !AreaCheck("AR1200") 
    !AreaCheck("AR1204") 
    !AreaCheck("AR1300") 
    !AreaCheck("AR1304") 
    !AreaCheck("AR1400") 
    !AreaCheck("AR1404") 
    !AreaCheck("AR1700") 
    !AreaCheck("AR1800") 
    !AreaCheck("AR1900") 
    !AreaCheck("AR1901") 
    !AreaCheck("AR1902") 
    !AreaCheck("AR1904") 
    !AreaCheck("AR1905") 
    !AreaCheck("AR2500") 
    !AreaCheck("AR2600") 
    !AreaCheck("AR2602") 
    !AreaCheck("AR2603")
    !AreaCheck("AR2700") 
    !AreaCheck("AR2800")~ THEN DO ~SetGlobal("B!GavSex","GLOBAL",1) 
      IncrementGlobal("B!GavLove","GLOBAL",19) 
      SetGlobal("B!GavSerious","GLOBAL",3) 
      SetGlobal("B!GavRA","GLOBAL",2) 
      ClearAllActions() 
      StartCutSceneMode() 
      StartCutScene("b!rest1")~ EXIT 
IF ~OR(27) 
    AreaCheck("AR0085") 
    AreaCheck("AR1100") 
    AreaCheck("AR1101") 
    AreaCheck("AR1102") 
    AreaCheck("AR1104") 
    AreaCheck("AR1105") 
    AreaCheck("AR1106") 
    AreaCheck("AR1107") 
    AreaCheck("AR1200") 
    AreaCheck("AR1204") 
    AreaCheck("AR1300") 
    AreaCheck("AR1304") 
    AreaCheck("AR1400") 
    AreaCheck("AR1404") 
    AreaCheck("AR1700") 
    AreaCheck("AR1800") 
    AreaCheck("AR1900") 
    AreaCheck("AR1901") 
    AreaCheck("AR1902") 
    AreaCheck("AR1904") 
    AreaCheck("AR1905") 
    AreaCheck("AR2500") 
    AreaCheck("AR2600") 
    AreaCheck("AR2602") 
    AreaCheck("AR2603")
    AreaCheck("AR2700") 
    AreaCheck("AR2800")~ THEN DO ~SetGlobal("B!GavSex","GLOBAL",1) 
      IncrementGlobal("B!GavLove","GLOBAL",19) 
      SetGlobal("B!GavSerious","GLOBAL",3) 
      SetGlobal("B!GavRA","GLOBAL",2) 
      ClearAllActions() 
      StartCutSceneMode() 
      StartCutScene("b!rest2")~ EXIT // camp
END  

